== 自立循環型住宅への省エネルギー効果の推計プログラム　Ver3.0

=== 「自立循環型住宅への省エネルギー効果の推計プログラム」とは
　建築物省エネ法に基づくプログラム（以下、「省エネ基準プログラム」）では、効果が定量化されているものの、竣工検査で確認ができない、あるいは省エネ基準のスコープ外である等の様々な理由により、評価していない項目があります。
 
　そこで、自立循環型住宅への省エネルギー効果の推計プログラム（以下、「自立循環プログラム」）では、デザインツールとして活用できるよう、居住人数や立地状況の反映、結果シートのビジュアル化など、省エネ基準プログラムから設定や評価項目を拡張して運用しています。
 
　省エネ基準プログラムをベースに作成しているため、『自立循環型住宅への設計ガイドライン』とは異なる評価となっている項目もあります。

=== 基本情報

 ・住宅の名称 　○○○○邸（直接入力）
 
 ・居住人数　　　　 [人] (1～4人まで)
 
 ・住宅の建て方
　　　　・戸建住宅
　　　　・集合住宅
    ※計算に影響なし？
    
 ・居室の構成
　　　　・主たる居室とその他の居室、非居室
　　　　・それ以外の構成
    　　　　　・その他居室の有無
         　　　　　・有
　　　　　　　　　　・無
    　　　　　・非居室の有無
         　　　　　・有
　　　　　　　　　　・無
 
 NOTE: 上記「居室の構成」で、床面積の表示を切り替え

 ・自立循環型住宅の設計目標像
　　　　・伝統的自然生活指向
　　　　・自然生活指向
　　　　・設備生活指向
        ※結果シートに反映？

=== 床面積

 ・主たる居室
         m2(小数点以下2桁)
 ・その他の居室
         m2(小数点以下2桁)
 ・非居室　（自動計算）
 ・合計
         m2(小数点以下2桁)

=== 地域

 ・地域の区分
　　　・1地域
　　　・2地域
　　　・3地域
　　　・4地域
　　　・5地域
　　　・6地域
　　　・7地域
　　　・8地域

 ・年間日射地域区分
　　　・指定しない
　　　・指定する
　　　　　　　・A1区分(年間の日射量が特に少ない地域)
　　　　　　　・A2区分(年間の日射量が少ない地域)
　　　　　　　・A3区分(年間の日射量が中程度の地域)
　　　　　　　・A4区分(年間の日射量が多い地域)
　　　　　　　・A5区分(年間の日射量が特に多い地域)
 
  ・暖房期日射地域区分（未実装）
　　　・指定しない
　　　・指定する
　　　　　　　・H1区分(年間の日射量が特に少ない地域)
　　　　　　　・H2区分(年間の日射量が少ない地域)
　　　　　　　・H3区分(年間の日射量が中程度の地域)
　　　　　　　・H4区分(年間の日射量が多い地域)
　　　　　　　・H5区分(年間の日射量が特に多い地域)
       
 NOTE: 蓄熱利用と屋根空気集熱で利用。現在は地域区分の変化は未実装

=== 光熱費原単位（未実装）

 　　　・建物の種類
            ・オール電化
            ・都市ガス併用住宅
            ・LPガス併用住宅
 　　　・光熱費単価      
 　　　　　　・電気料金　　　　円/kwh
 　　　　  　・深夜電力料金　　　円/kwh
 　　　　  　・都市ガス　　　　円/m3
 　　　　  　・LPガス　　　　円/m3
 　　　　  　・灯油　　　　円/L
        
=== 自立循環型住宅とは
　気候や敷地特性などの住宅の立地条件および住まい方に応じて極力自然エネルギーを活用した上で、建物と設備機器の設計や選択に注意を払うことによって、居住性や利便性の水準を向上させつつも、居住時のエネルギー消費量を2010年頃の標準的な住宅と比較して、太陽光発電を含めずに50%にまで削減可能な、太陽光発電を含めるとゼロエネルギー化が可能な現時点において十分実用化できる住宅です。

=== 目指す室内環境性能
　省エネに加え、住まい手が「心地よい」と感じられる環境を形成することも重要です。ただし、住まい手が希求する「心地よい」環境は千差万別でかつ変容するものであり、寒さ、暑さ、暗さなどの生理的ストレスを皆無とすることが必ずしも至上目的ではありません。住まい手には希求する環境を選択する自由があり、その自由を保障して幅広い考え方を許容し、住まい手にふさわしい環境の質を備えた住宅の実現を自立循環型住宅は目指しています。
