== 基本情報 Cパート：

== 省エネルギー手法の解説（入力ガイド説明文）


== 基本情報

== 住宅の名称
NOTE: 手法解説は不要



[[shuho_bsc_tatekata]]
==== 住宅の建て方

・共同住宅、長屋その他の一戸建て住宅以外の住宅及び複合建築物を評価する場合は「共同住宅」を選択してください。



[[shuho_bsc_persons_input]]
==== 居住人数の入力

・住宅の居住人数を考慮した評価をすることが可能です。居住人数が不明な場合は「居住人数を入力しない」を選択してください。


== 居住人数
NOTE: 手法解説は不要

== 床面積


[[shuho_bsc_shukyoshitsu_menseki]]
==== 床面積

・一次エネルギー消費量は床面積に依存して計算するため、ここに入力する床面積は、基準一次エネルギー消費量および設計一次エネルギー消費量を算出する際の必須項目となります。居室ごとに消費量を計算する用途もあることから、「主たる居室」、「その他の居室」、床面積の「合計」（非居室は入力値から自動計算されます）を入力します。
居室及び非居室の床面積の計算は、当該住戸又は当該住戸の部分における熱的境界の内側に存する床面積のうち、間仕切りや扉等で区切られた居室及び非居室ごとに計算します。ただし、下表 の場合はこの限りではありません。

・表1 床面積算出の特例

風除室、サンルーム・・・非密閉空気層とする場合の風除室及びサンルームの床面積は、床面積に算入しない。ただし、風除 室等を熱的境界に囲まれた空間とみなす場合は床面積に算入する。

出窓・・・外壁面からの突出が 500 ㎜未満、かつ、下端の床面からの高さが 300 ㎜以上である腰出窓の面積 は、床面積に算入しない。

小屋裏収納、床下収納・・・熱的境界の内側に存する小屋裏収納、床下収納のうち、建築基準法で定める延べ面積に算入されない小屋裏収納及び床下収納の面積は、床面積に算入しない。

物置等・・・居室に面する部位が断熱構造となっている物置、車庫その他これらに類する空間（以下、「物置等」 という。）の床面積は、床面積に算入しない。

・床面積の算出は、以下を参考に算出してください。

===== 1)「主たる居室」の床面積

「主たる居室」の面積は、リビング（居間）、ダイニング（食堂）及びキッチン（台所）の床面積の合計とする。また、これらの室は独立していても「主たる居室」として床面積を算出する。複数のリビング（居間）、ダイニング（食堂）及びキッチン（台所）がある場合には、全ての床面積の合計を「主たる居室」の面積とする。また、コンロその他調理する設備又は機器を設けた室は「キッチン（台所）」として扱い、「主たる居室」として床面積を算出する。

===== 2)「その他の居室」の床面積

「その他の居室」の面積は、「主たる居室」以外の寝室、洋室及び和室等の居室の床面積の合計とする。

===== 3)「非居室」の床面積

「非居室」の面積は、「主たる居室」及び「その他の居室」以外の浴室、トイレ、洗面所、廊下、玄関、間仕切り及び扉等で区切られた押し入れ並びにクローゼット等の収納等の床面積の合計とする。ただし、収納が居室に付随している場合は、それが属する居室の一部としてみなし、当該居室に分類して床面積の算定を行うことも可能とする。

===== 4) 床面積の合計

床面積の合計は、「主たる居室」、「その他の居室」及び「非居室」の床面積の合計とする。

===== 5) 吹抜け等の扱い

住戸内に吹抜け等を有する場合は、当該吹抜け部分に仮想床があるものとみなして、床面積を計算する。ここで「吹抜け等」とは、吹抜け及び天井の高さが 4.2m 以上の居室及び非居室を指し、「吹抜け」とは、複数の階をまたいで床を設けず上下方向に連続した空間を指す。仮想床の面積は、吹抜け等が存する「主たる居室」、「その他の居室」又は「非居室」の面積に加えることとする。天井の高さが 4.2m 以上の場合、高さ 2.1m の部分に仮想床があるものとみなして、当該居室又は非居室の床面積に仮想床の床面積を加えて計算する。天井の高さが 6.3m 以上の場合、高さ 2.1m 及び 4.2m の部分に仮想床があるものとみなして、当該居室又は非居室の床面積に仮想床の床面積を加えて計算する。以下同様に、天井高さが 2.1m 増えるごとに仮想床を設ける。

===== 6) 一体的空間の扱いについて

間仕切り壁や扉等がなく、水平方向及び垂直方向に空間的に連続する場合は、ひとつの室とみなして床面積を算出する。また、吹抜け等に面して開放された空間についても、当該吹抜け等が存する「主たる居室」、「その他の居室」又は「非居室」と一体であると判断し、床面積を算定することとする。なお、「主たる居室」と空間的に連続する「その他の居室」及び「非居室」は「主たる居室」に含めることとし、「その他の居室」と空間的に連続する「非居室」は「その他の居室」に含めることとして床面積を算出する。


== 地域

[[shuho_env_chiki]]
==== 地域の区分

・省エネルギー基準の地域の区分とは、全国を市町村単位別に主に外気条件を評価軸として8つの地域に分けた区分のことで、1～8の地域の区分として表しています。それぞれの地域において気候条件の差が大きく、暖房、冷房、給湯などの一次エネルギー消費量の結果が大きく異なってしまうため、気候条件の差を小さくし、適切に省エネルギー性能を評価することを目的として8区分に細分化されています。当該住戸の地域の区分は、こちらを参照してください。

NOTE: 参照先の資料の検討が必要


[[shuho_bsc_solarlv_specify]]
==== 年間日射地域区分

・水平面全天日射量の年間積算値を指標として日本全国を日射の少ない地域から多い地域まで5地域に分類した地域区分のことです。太陽光発電又は太陽熱利用給湯設備を採用する場合は年間日射地域区分を選択して下さい。当該住戸の年間日射地域区分は、こちらを参照してください。

NOTE: 参照先の資料の検討が必要

== 立地条件


[[shuho_bsc_gaibufusoku]]
==== 気象条件（外部風速）

・「自然風の利用」の評価に影響する立地条件です。

・自立循環型住宅のウェブサイトに掲載している気象データ資料（http://www.jjj-design.org/program/%e6%b0%97%e8%b1%a1%e3%83%87%e3%83%bc%e3%82%bf/
）等を参照し、建設地（またはその近傍）の終日の平均風速（地上6.5m位置）を選択してください。
　

[[shuho_bsc_kenpeiritu]]
==== 敷地周辺の建物密集度

・「自然風の利用」の評価に影響する立地条件です。

・「区域建蔽率」とは、建築基準法などで用いられる「建蔽率」を準用して、自立循環型住宅において自然風利用の可能性に関連する敷地周辺の密集度を判断するために定義された指標です。

・基準法で定められた建蔽率は「建築物の建築面積の敷地面積に対する割合」を表しますが、区域建蔽率は、建物に作用する風圧力に影響があると想定される建設地周囲の「一定区域内の建築物の建築面積の合計の当該区域面積に対する割合」を表すものとします。

・この区域面積には建築物が建つ敷地以外の道路や公園、水路などの面積を含むものとし、また、建築面積には周辺の建物とともに計画建物の建築面積を含むものとします。自然風利用の可能性への影響を考慮して、計画建物の周囲直径50ｍを区域建蔽率の算定区域とします。

・「区域建蔽率」の求め方は以下の通りです。

① 住宅地図などに、建設地を中心とする直径50ｍの円を作図する。

② ①で描いた円の内側に存する建物等の建築面積の合計値を算出する（円で区切られている建物等については、円の内側の部分のみが対象）。

③ ②で求めた値に計画建物の建築面積（想定値も可）を加算する。この値を区域建蔽率を求めるための区域内の建築物の建築面積とみなす。

④ ③の面積の区域面積（1963.5㎡）に対する割合を求める。この値が「区域建蔽率」となる。

TIP: 温暖地テキストP48 図 住宅における区域建蔽率の算定例


[[shuho_bsc_taiyokoriyo]]
==== 日照条件

・「昼光利用」の評価に影響する立地条件です。

NOTE: 昼光利用未実装


[[shuho_bsc_rinto_misshu]]
==== 敷地周辺の密集度

・「日遮熱制御」の評価に影響する立地条件です。

NOTE: 方位係数の補正は入力前に行うので選択肢としては不要？


[[shuho_bsc_mokuhyo]]
==== 自立循環型住宅の設計目標像

・以下の表やイメージを参照して、設計しようとする自立循環型住宅の目標像を設定してください。

TIP: 温暖地テキストP26 表７ ライフスタイルの指向の分類　
TIP: 温暖地テキストP27 表８ 自立循環型住宅の設計目標像（典型タイプ）と要素技術の適用イメージ　
TIP: 温暖地テキストP28，29 住宅タイプの参考例

・自立循環型住宅の設計目標像としては、タイプⅠ・Ⅱ・Ⅲの３つの住宅タイプが典型として考えられます。これらのタイプは、３つのライフスタイルの指向に対応するものとして、参考に掲げたものです。タイプごとにどの要素技術を優先して適用するかは変わってきますので、設計者はこれらのタイプを参考にして住宅の設計目標像を設定し、要素技術の適用優先度を考慮して、具体的な手法の検討を行うことが有効です。


== エネルギー料金単価

[[shuho_bsc_electricity_rate]]
==== 電気料金
・地域の電力会社のHP等を参考に、電気料金単価を入力してください。



