
== 自然風の利用・制御：


=== 自然風の利用・制御とは
夏期夜間や中間期など気象条件が温熱感覚上の体感改善に有効な場合に、外気を通風という形で積極的に取り入れ、冷房エネルギー消費の削減と快適性の向上を実現することを目的とした技術です。

===== 自立循環型住宅オプション（仮）
  ・立地の違いによる効果
  ・外部風速による効果
  ・卓越風向による効果（未実装）
  ・高窓の効果
  ・窓開けをしない場合（未実装）

=== 目標レベル
  ☆☆☆☆☆　目標レベルと参考仕様を記載
  ☆☆☆☆
  ☆☆☆
  ☆☆
  ☆
  
  モデル住宅による標準的なエネルギー消費量　3.9GJ（6地域）
  
TIP: 地域選択を反映させて切り替えられると良い。

  
=== 前提条件
==== 気象条件（外部風速）
  ・1m/s以下
  ・1～2m/s
  ・2m/s以上

==== 立地条件（敷地周辺の建物密集度）
  ・立地1：都市型の立地（区域建蔽率が20%超）
  ・立地2：郊外型の立地（区域建蔽率が20%以下）

=== 主たる居室　自然風利用の有無
  ・利用しない・評価しない
  ・省エネ手法を選択
        ・開口部面積 小の組み合せ
        ・開口部面積 大の組み合せ
        ・卓越風向に応じた開口部
        ・高窓の利用
  ・換気回数で評価
          ・換気回数　　 [回/h] (整数)
 
    
=== その他居室　自然風の利用の有無
  ・利用しない・評価しない
  ・省エネ手法を選択
        ・開口部面積 小の組み合せ
        ・開口部面積 大の組み合せ
        ・卓越風向に応じた開口部
        ・高窓の利用
  ・換気回数で評価
          ・換気回数　　 [回/h] (整数)

=== 設計上の配慮事項・暮らし方の留意点

==== 外構計画による環境調整
　住宅周辺に樹木等の植栽を配置するなど、外構を工夫して日射を遮蔽することで、室内に取り入れる風の温度を上げない効果が期待できます。また、日射の照り返しや暖まった地表面からの熱放射が抑えられるため、窓面等から流入する熱の抑制につながります。一方、大きな窓に面して、日射のあたるタイル敷きのテラスやアスファルト舗装の駐車場がある場合は、外部の温熱環境の悪化が室内環境に影響することになります。（温暖地版P51図a,b）

==== 開口部の大きさと通風の質
　風の「入口」と「出口」の大きさの関係によって、得られる通風の質は異なってきます。開口部面積は大きいほど効果がありますが、大きい開口部を1組確保する場合と、同等の開口部面積を複数の開口部で確保する場合には、効果に大きな差はありません。また、2つの開口部の大きさに差がある場合、風上側と風下側の窓の大小により、室内の気流性状が異なってきます。風上側の開口部を小さくした場合には、流入速度が増すことになり、風の通り道にいる人は、より強い冷涼感を得ることができます。風下側の開口部を小さくした場合には、流入速度の低下をまねきますが、室内の広い範囲でやわらかい風（穏やかな気流速度）を期待することができます。（温暖地版P51下図a,b：図版使用許諾必要）

==== 防犯、外部騒音への配慮
　窓閉鎖時に加え、通風時にも防犯性能が確保できる窓（夜間開放可能窓）の選定が必要です。開放ストッパー付き窓や面格子付き窓、通風雨戸や通風シャッター付き窓、細幅窓などが考えられます。また、騒音への対応として、設計当初から騒音源が明らかな場合は、それに面する開口部を小さくする方法や遮音性能の高い建具を使う方法で対応が可能な場合もあります。また、開き窓では騒音源と反対の方向（静かな方向）に開放するような開き勝手にすると、より遮音効果が得られます。
 
==== 住まい手の窓の開閉行動
　設計上、様々な工夫をしても、実際に住まい手が窓を開けなければ通風は確保できません。そこで重要になってくるのが、外気温が下がったことを、住まい手に知らせるしくみです。コンパクトな外気温度計が市販されているので、それらを利用して住まい手に窓の開閉行動を促す工夫をしてはどうでしょうか。
 
==== 室内通風性の向上
　室内開口部による通風を確保するためには、扉を開放することが最も容易ですが、プライバシー確保の難しさ、突然の強風による閉鎖等から、通風に適切な扉の開放状態を保てないおそれがあります。そのため、引戸や格子戸、欄間の採用やドアストッパーの設置といった通風を確保するための工夫を講じることが有効です。
