== 自然風の利用 Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野

== 省エネルギー手法の解説（入力ガイド説明文）

=== ⾃然⾵を利用しない・評価しない

=== 自然風の利用手法を選択して省エネルギー効果を評価する

==== 高窓の利用の有無

通風を確保するには、外壁開口部（高窓でない窓）を利用する他、高窓（建物の上端に近い壁の高所に設置する頂側窓や、屋根面に設置する天窓など）を利用することも可能です。ここでは、外壁開口部を利用する場合を手法1、高窓を利用する場合を手法3としています。

==== 【手法１】通風経路上の開口面積の確保

外気を室内に効果的に取り入れるためには、「入口」と「出口」の役割を果たす開口を異なる方位の壁面2面以上に設けることが必要です。2ヶ所の開口部と通風経路の取り方を手法1では2つの方法で考えます（開口部と通風経路の取り方）。通風経路①および②の経路上の開口部の面積が大きいほど、期待できる通風量（換気回数）が大きくなり、一般的に省エネルギー効果も大きくなります。手法1に必要とされる通風経路①と②の開口部面積の要件を各々2段階設定しました。開口部面積が小さい場合を手法1a、手法1aの開口部面積を2倍に大きくした場合を手法1bとしています（開口部面積の要件）。

NOTE: 開口部と通風経路の取り方 ・・・現プログラムのヘルプと同じ

NOTE: 開口部面積の要件 ・・・現プログラムのヘルプと同じ


==== 【手法３】高窓の利用

高窓を利用して通風を確保する場合、風の入口は外壁開口部、出口は高窓となることが多く、その通風経路の取り方を、手法3では2つの方法で考えます（高窓による通風経路確保の方法）。風下側に高窓を設置することで大きな風圧係数差を得ることができるため、小さい高窓面積でも効果があります。さらに、高所に窓を設置することで、内外温度差によって生じる空気密度の差を生かして安定的に通風量を確保できる効果も期待出来ます。また、夜間の防犯への配慮の観点からも有効といえます。（高窓を利用した通風経路上の開口部面積の要件）

NOTE: 高窓による通風経路確保の方法 ・・・現プログラムのヘルプと同じ

NOTE: 高窓を利用した通風経路上の開口部面積の要件 ・・・現プログラムのヘルプと同じ

=== 換気回数を選択して省エネルギー効果を評価する

換気回数を入力して省エネルギー効果を評価します。

NOTE: 省エネ基準の通風の換気回数の計算方法を抜粋
