
== 自然風の利用・制御：


=== 自然風の利用・制御とは
夏期夜間や中間期など気象条件が温熱感覚上の体感改善に有効な場合に、外気を通風という形で積極的に取り入れ、冷房エネルギー消費の削減と快適性の向上を実現することを目的とした技術です。

===== 自立循環型住宅オプション（仮）
  ・立地の違いによる効果（未実装）
  ・外部風速による効果（未実装）

=== 目標レベル
  ☆☆☆☆☆　目標レベルと参考仕様を記載
  ☆☆☆☆
  ☆☆☆
  ☆☆
  ☆
  
=== 前提条件
=== 気象条件（外部風速）
  ・1m/s以下
  ・1～2m/s
  ・2m/s以上

=== 立地条件（敷地周辺の建物密集度）
  ・立地1：都市型の立地（区域建蔽率が20%超）
  ・立地2：郊外型の立地（区域建蔽率が20%以下）

=== 主たる居室　自然風の利用の有無
  ・⾃然⾵を利用しない・評価しない
  ・自然風の利用手法を選択して省エネルギー効果を評価する
  ・換気回数を選択して省エネルギー効果を評価する
  
=== 主たる居室　高窓の利用の有無
  ・利用しない
  ・利用する
　　　　　　　　　　　　　　　　　　
=== 主たる居室　通風経路上の開口面積の確保
  ・開口部面積を確保していない
  ・開口部面積（小）の組み合わせを確保している（手法1a）
  ・開口部面積（大）の組み合わせを確保している（手法1b）

=== その他居室　自然風の利用の有無
  ・⾃然⾵を利用しない・評価しない
  ・自然風の利用手法を選択して省エネルギー効果を評価する
  ・換気回数を選択して省エネルギー効果を評価する
  
=== その他居室　高窓の利用の有無
  ・利用しない
  ・利用する
  
=== その他居室　通風経路上の開口面積の確保
  ・開口部面積を確保していない
  ・開口部面積（小）の組み合わせを確保している（手法1a）
  ・開口部面積（大）の組み合わせを確保している（手法1b）

=== 設計上の配慮事項・暮らし方の留意点

==== 設置方位と傾斜角
　方位による効率は、真南向きを利用効率を100%とすると、東西は85～89％程度、北は67～75％程度です。傾斜角は、10°（1 寸8 分勾配程度）から40°（8 寸4 分勾配程度）の範囲では、ほとんど差はありません。方位には多少注意が必要ですが、屋根の勾配について特別に配慮が必要になることはなく、好みのデザインの屋根に設置することが可能といえます（新築版P84図）

==== 局地的条件
　太陽光発電は、日影ではほとんど発電しません。そのため、北向きの傾斜地や山間部など、日照時間が短くなる場合や、降雪によって太陽電池モジュールが雪で覆われたままだと、期待される発電量が得られいため注意が必要です。また、近隣の将来状況も想定して検討する必要があります。

==== 太陽光発電システムの設置上の注意
　太陽電池モジュールを屋根に設置する場合、風の強い地域では、暴風による破損に注意が必要です。また、積雪地では、発電用の機器や部材が積雪による荷重に耐えるようにするとともに、太陽電池モジュールからの落雪に十分注意する必要があります。
