== 用語解説(簡易版）

[[guide_nw_takuetsu]]
==== 卓越風向：
地域・期間・時間帯に特有の風向

[[guide_nw_heikinfuusoku]]
==== 平均風速：
地上6.5ｍ（2階建戸建て住宅の軒高相当高さ）の風速の6月~9月の平均値。「自立循環型住宅ウェブサイト」の中で、自然風利用手法の検討を行うために整理した気象データを参照している。各地の風速、風向等の情報を確認できる。（温暖地版P46コラム図：図版使用許諾必要）


[[guide_bsc_gaibufusoku]]
==== 外部風速：

[[guide_nw_takamado]]
==== 高窓：
高所に設置する頂側窓や、屋根面に設置する天窓など。

[[guide_nw_fuuatsukeisuu]]
==== 風圧係数：
風上面と風下面で風が当たることにより発生する圧力の比率。住宅の形状や周辺状況によって大きく変わるため、正確に予測することは難しい。

[[guide_nw_tsuufuukeiro]]
==== 通風経路：
通風時に風が室内を通過する経路のこと。（温暖地版P49図1）

[[guide_nw_kuikikenpeiritsu]]
==== 区域建蔽率：
建築基準法等で用いられる「建蔽率」を準用して、『自立循環型住宅への設計ガイドライン』において自然風利用の可能性に関連する敷地周辺の密集度を判断するために定義された指標。計画建物の周囲直径50 ｍを区域建蔽率の算定区域とする。（温暖地版P48図）

[[guide_nw_ryuryokeisuu]]
==== 流量係数：
風の通りやすさを示す値。一般に風が開口面に垂直に流入流出する場合に大きく、斜めに流入流出するにつれ小さくなる。



== (修正前：詳細版→参考（使用しない））
== 用語解説
==== 卓越風向:
その地域・期間・時間帯に特有の風向

==== 平均風速：
「自立循環型住宅」のHPの「省エネルギー効果の推計」の「気象データ」で公開している各地の風速、風向の情報で確認できます。２階建戸建て住宅の軒高相当高さ（地上6.5ｍの位置）の風速を６月~９月の平均値で示しています。住宅全体で評価を行う場合は、終日の平均風速を参照するとよいでしょう。居室毎に効果を検討する場合には、居室の用途により参照する時間帯を選んでください。（「自立HP」の「省エネルギー効果の推計」の「気象データ」の「本データの使用方法」より）→図（温ガp46コラム図）

==== 風圧係数：
住宅の形状や周辺状況によって大きく変わるため、正確に予測することは難しく、密集住宅地ではとりわけ難しくなります。

（辻追記）風の持つ圧力に対する建物表面に作用する圧力の比率のこと。風圧係数0.5とは、風の持つ圧力の半分が建物表面を押す圧力を意味する。正圧と負圧の差（風圧係数差）が大きくなる２面に開口を設けると通風を確保しやすい。


==== 通風経路：
通風時に風が室内を通過する一連の(分岐しない)経路のこと。通風経路は、経路上の室内開口数により分類される（参考図）（省エネ基準解説書p.648）→図（温ガp49図１）

==== 区域建蔽率：
本書において自然風利用の可能性に関連する敷地周辺の密集度を判断するために定義された指標です。建物に作用する風圧力に影響があると想定される建設地周囲の「一定区域内の建築物の建築面積の合計の当該区域面積に対する割合」を表すものとします。計画建物の周囲直径50ｍを区域建蔽率の算定区域とします。当該区域面積に対する区域内の建築物の建築面積の合計の割合→図（温ガp48図）

==== 流量係数：
風の通りやすさを示す値です。一般に気流が開口面に垂直に流入流出する場合に大きく、斜めに流入流出するにつれ小さくなることが知られています（省エネ基準解説書p.662）
