== 用語解説(簡易版）
==== 太陽光発電：
太陽光で発電を行い、住宅内で消費する電力を自己生産するシステム。日中の余剰電力は売電できる。(温ガp.82)

==== 余剰電力：
太陽光で発電したが、住宅内で使われなかった電力。(温ガp.82)

==== 売電：
太陽光発電で発電した電力を、電力会社に買ってもらうこと。また買い取ってくれる制度のことを売電制度という。

==== 系統連系型システム：
商用電力系統と連系して電気を売買するシステム。(温ガp.82)

==== 太陽電池モジュール：
太陽電池の構成単位のうち、製品として流通する単位のこと。太陽電池は「セル」「モジュール」「ストリング」「アレイ」といった単位で扱われている。

==== 太陽電池アレイ：


==== 年間日射量地域区分：
１年間に取得する日射量によって、全国をA1~A5の５つの地域に区分したもの。太陽光発電、太陽熱給湯による省エネルギー効果の算出には、この区分を使用する。（温ガp.37）

==== 年間(推定)発電量：
年間日射量×損失等による総合効率×定格容量。(温ガp.86)

==== 設置方位：
太陽光発電パネルを設置する方位。→図（温ガp84図2上）

==== 傾斜角：
太陽光発電パネルを設置する部分の水平面に対する角度。→図（温ガp84図2下）

==== 電圧抑制：
系統の電圧がパワーコンディショナーからの発電電圧よりも高い場合に、系統連系がスムースに行われなくなってしまうこと。(温ガp.85)



== （修正前：詳細版）
== 用語解説
==== 太陽光発電：
日中に自然エネルギーである太陽光で発電を行い、住宅内で消費する電力を自己生産するシステム。日中の余剰電力は売電することができます。(温ガp.82)

==== 余剰電力：
太陽光で発電したが、住宅内で使われなかった電力(温ガp.82)

==== 売電：
太陽光発電で発電した電力を、電力会社に買ってもらうこと。また買い取ってくれる制度のことを売電制度という。（参照元：https://www.solar-partners.jp/what-is-feed-in-tariff-26859.html）
一般事業会社や個人などが発電した電力を電力会社に売ること。おもに家庭や事業所などが設置する太陽光発電システムや家庭用燃料電池などを通じて発電した電力のうち、自家消費をしない余剰分を電力会社に買い取ってもらう制度のことをいう。(参照元：https://kotobank.jp/word/%E5%A3%B2%E9%9B%BB-599096日本大百科全書（ニッポニカ）)

==== 系統連系型システム：
商用電力系統と連系して電気を売買するシステム(温ガp.82)

==== 太陽電池モジュール：
太陽電池の構成単位のうち、製品として流通する単位のこと。太陽電池は「セル」「モジュール」「ストリング」「アレイ」といった単位で扱われている。太陽電池セルは最小構成単位であり、電池のいわば素子である。このセルを配列してある程度の電力が得られる単位にまとめたものが太陽電池モジュールと呼ばれる。モジュールは強化や保護のためにガラスコーティングなどの加工が施され、単体で製品として扱われる。（参照元：https://www.weblio.jp/content/%E5%A4%AA%E9%99%BD%E9%9B%BB%E6%B1%A0%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB）

==== 年間日射量地域区分：
１年間に取得する日射量によって、全国をA1~A5の５つの地域に区分したもの。太陽光発電、太陽熱給湯による省エネルギー効果の算出には、この区分を使用します。設計する敷地がどの区分に属するかは、○図を参照してください。（温ガp.37） 

==== 年間(推定)発電量：
年間日射量×損失等による総合効率×定格容量(温ガp.86)

==== 設置方位：
真南の向きに設置した場合の利用効率を100%とすると、敷地周辺の状況にもよりますが、東西は85～89％程度、北は67～75％程度となります（屋根の傾斜角30°、5寸7分勾配程度の場合）。 (温ガp.84) →図（温ガp84図2上）

==== 傾斜角：
水平面より30°程度の場合が多くの地域で最も効率が高くなりますが、10（°1寸8分勾配程度）から40（°8寸4分勾配程度）の範囲では、ほとんど差はありません。(温ガp.84) →図（温ガp84図2下）

==== 電圧抑制：
系統の電圧がパワーコンディショナーからの発電電圧よりも高い場合に、系統連系がスムースに行われなくなってしまうこと。(温ガp.85)

