
== 太陽光発電マニュアル Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野

== 省エネルギー手法の解説（入力ガイド説明文）

=== 『太陽光発電の採用』

説明なし

[[shuho_pv_houinokazu]]
==== 『設置方位の数』

同じ方位に設置する場合でも、「太陽電池アレイ設置方式」や「パネルの設置傾斜角」等の仕様が異なる場合は、異なるパネルとして区別し入力して下さい。入力に際しては、「太陽電池アレイのシステム容量」の大きいものから順に入力し、パネル面数が4 を超える場合は評価対象外とします。

なお、太陽電池アレイの方位角、傾斜角、半導体の種類として結晶系か結晶系以外かの別及び設置方式が同一の複数の太陽電池アレイについては、各太陽電池アレイのシステム容量を合計することで、1 つの太陽電池アレイとみなしても構いません。

TIP: 省エネ基準ヘルプ

[[shuho_pv_pcs_koritsu]]
==== 『パワーコンディショナの定格負荷効率』

カタログや仕様書などを参照し、JIS C 8961「太陽光発電用パワーコンディショナの効率測定方法」に基づき測定された定格負荷効率を入力してください。

複数台のパワーコンディショナが設置される場合は、最も定格負荷効率の低いパワーコンディショナの値を入力してください。

TIP: 省エネ基準ヘルプを改変

[[shuho_pv_panel_youryo]]
==== 『太陽電池アレイのシステム容量』

「太陽電池アレイのシステム容量」とは、標準試験条件の状態に換算した太陽電池アレイの最大出力点における出力です。太陽電池アレイ容量とも言われます。カタログや仕様書などを参照し、太陽電池アレイのシステム容量を入力してください。
詳細は、国立研究開発法人建築研究所『平成28年省エネルギー基準に準拠したエネルギー消費性能の評価に関する技術情報（住宅）』https://www.kenken.go.jp/becc/house.html
を参照してください。

TIP: 省エネ基準ヘルプを改変

[[shuho_pv_panel_shurui]]
==== 『太陽電池アレイの種類』

太陽電池の種類を「結晶シリコン系太陽電池」と「結晶シリコン系以外の太陽電池」から選択して下さい。「結晶シリコン系以外の太陽電池」には、単結晶シリコン及び多結晶シリコン以外のアモルファス太陽電池や多接合太陽電池が該当します。

結晶シリコン系太陽電池であるかどうかは、カタログや仕様書などにより確認して下さい。

[[shuho_pv_panel_setti]]
==== 『太陽電池アレイ設置方式』

「太陽電池アレイ設置方式」とは、太陽電池アレイの取り付け方を示し、本評価では「架台設置形」「屋根置き形」「その他」に分類されています。下表を参考に、太陽電池アレイを屋根や屋上に設置する方式について選択して下さい。

※表ここから

架台設置形	太陽電池モジュールを、屋根と空隙を設けて間接に設置した太陽電池アレイで屋根置き形以外のものの場合

屋根置き形	太陽電池モジュールを、屋根と平行に空隙を設けて間接に設置した場合

その他	上記以外の設置方式で、屋根用アレイのうち「屋根材一体形」の場合、壁用アレイ及び窓用アレイ等の場合

※表ここまで

TIP: 省エネ基準ヘルプ

[[shuho_pv_panel_houi]]
==== 『パネル設置方位（方位角）』

太陽光発電受光面の法線方向の水平部分が真南に対し、東回りもしくは西回りに振れた角度で示しています。下図を参考に、設置方位角を選択して下さい。

NOTE: 省エネ基準ヘルプのイラストを追加

TIP: 省エネ基準ヘルプ　

[[shuho_pv_panel_keisha]]
==== 『パネル設置角度（傾斜角）』

太陽光発電が設置された傾斜角（水平面からの角度）を選択して下さい。90度を超える場合は90度を選択して下さい。

尺貫法から換算する場合は、下表を参考にしてください。

NOTE: 省エネ基準ヘルプの表を追加

TIP: 省エネ基準ヘルプ　
