== 蓄熱の利用 Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野

== 省エネルギー手法の解説（入力ガイド説明文）

[[shuho_sh_nisshanetsuriyo]]
==== 蓄熱の利用

蓄熱の利用の程度は、地域区分における暖房期の日射地域区分に応じて下表のように定められており、「可」と表記のある区分のみ評価可能です。「不可」に該当する区分の場合は、蓄熱の評価はできません。 当該住戸の暖房期日射地域区分は、こちら（http://house.app.lowenergy.jp/img/help/02_env_chiki_chikikubun.pdf）
を参照してください。

NOTE: 表：省エネ基準プログラム　蓄熱の利用ヘルプの表

上記表より「可」である地域において、蓄熱を「利用する」を選択できる要件は、蓄熱部位の熱容量が当該住戸の床面積当たり170kJ/(㎡K)以上の熱容量の増加が見込まれる材料を蓄熱部位に用いている場合に認められます。

TIP: 出典：省エネ基準ヘルプ

==== 熱容量の計算方法

蓄熱部位とは、蓄熱の利用に有効な熱容量を持つ部位をいい、天井、床（断熱区画内の床も含む）、壁（外気に接する壁及び間仕切壁）及び界壁・界床を対象とします。

蓄熱部位の計画

===== 1）蓄熱部位の材料

蓄熱部位に用いる材料には、次の特性をもつものが適しています。

①熱容量（容積比熱）が大きいこと。

②熱が伝わりやすいこと。

③表面からの熱の吸収・放散がすみやかに行われること。

蓄熱部位の熱容量が大きいほど、室温の変動が抑えられ安定します。つまり、熱容量が大きい材料を用いると、部屋は暖まりにくくなりますが、一旦暖まると冷めにくくする効果が現れます。


===== 2）熱容量の求め方

熱容量は次式で求められます。

熱容量（kJ/K）＝蓄熱部位の容積（㎥）×蓄熱材の容積比熱（kJ/（㎥･K））

ここで対象としている熱容量は、意図的に追加した材料を対象としています。通常の木造住宅の材料・仕様は熱容量の対象としていません。

参考として、主な材料の容積比熱を示します（表1）。

材料には蓄熱部位として計上できる「有効厚さ」が設定されています。材料の容積算定時において、材料の厚さが有効厚さ以上の場合は、有効厚さまでのみを計上することができます。これは、材料の厚さを有効厚さ以上としても、効果は比例して大きくならないためです。熱が伝わりやすい材料ほど、有効厚さは大きくなります。


材料の熱容量を求める例

====== ①面積12畳（19.87㎡）、厚さ150㎜のコンクリート床の熱容量

蓄熱部位の容積：19.87㎡×0.15m＝2.98㎥
熱容量：2.98㎥×2000kJ/(㎥･K)＝5960kJ/K

====== ②面積210㎡、厚さ70㎜の土壁の熱容量

蓄熱部位の容積：210㎡×0.07m＝14.7㎥
熱容量：14.7㎥×1100kJ/(㎥･K)＝16170kJ/K

====== ③面積100㎡、厚さ100㎜の軽量コンクリート（軽量2種）の熱容量

蓄熱部位の容積：100㎡×0.08m※＝8㎥（※有効厚さまで計上）
熱容量：8㎥×1600kJ/(㎥･K)＝12800kJ/K


NOTE: 表1主な材料の容積比熱と有効厚さ　改修版ガイドラインP181


===== 3）蓄熱部位の設計上の留意点

蓄熱の効果を確保するために、設計上次の事項に留意することが大切です。

====== ①蓄熱部位と日射の関係

蓄熱の効果は、蓄熱部位に日射が直接当たり日射受熱量が大きいほど顕著になりますが、日射が直接当たらない部位でも蓄熱効果を見込むことができます。日射熱を取り込むことで住宅全体の室温が上がれば、壁の蓄熱効果も期待できます。水平面で日射を受ける床は蓄熱部位としては有効ですが、家具が置かれたりするとその下の床は影になり、蓄熱効果は見込めません。将来的な家具の配置も見込んで、蓄熱範囲を検討することが重要です。

周辺環境の条件によっては、1階では日射の取得が難しい、または日射の取得できる時間が短い場合があります。その場合は主な居室を2階にすることで、日射熱の取得できる時間が長くなります。周辺環境をよく検討して平面計画をすることが大事です。

床に熱容量の大きい材料を敷いたサンルームを南側に設けるなど、住宅の一部に蓄熱部位を設けることがあります。このようなサンルームの設置による住宅全体の暖房エネルギーに対する効果は未検証ですが、冬期のサンルームの快適さは定性的には認められます。局部的な蓄熱部位の効果についての検証は今後の研究の成果が期待されます。

====== ②蓄熱部位の厚さ

蓄熱部位の厚さについては、材料の有効厚さ以上では蓄熱性能が変わらないことを意識して計画、例えば石やコンクリートなどを用いる場合、その厚さは150mm～200mmまでが有効です。蓄熱部位の厚さが薄い場合にも相応の蓄熱効果は得られます。蓄熱部位の仕上げ材には注意が必要です。床にコルクのような熱容量の小さい仕上げ材を使った場合、効果が減少するものがあります。

TIP: 出典：改修版テキスト P181,182


==== 熱容量の計算例

建物の蓄熱容量の計算方法はこちらの例を参照してください。

NOTE: @蓄熱容量の算出資料161110へのリンク

