== 用語解説

[[guide_thermalstorage_nisshanetsu]]
==== 日射熱：
建物が窓を通して取得する熱量のこと。日射熱を利用することは、暖房エネルギーの削減に有効。

[[guide_thermalstorage_passivesolar]]
==== パッシブソーラー暖房：
太陽熱を活用して、暖房エネルギーを削減する方法。地域の気候特性や立地などの条件に応じて、躯体・開口部の断熱仕様、日射熱取得をバランスよく計画する。

[[guide_thermalstorage_chikunetsubui]]
==== 蓄熱部位：
蓄熱の利用に有効な熱容量の素材で構成された部位。

[[guide_thermalstorage_shunetsumen]]
==== 集熱面：
日射熱を得る開口部のある面。真南に近い向きに面する開口部ほど集熱量は多くなる。集熱面の方位は、地域区分に係わらず真南から東または西に30°以内であることが最低条件。

[[guide_thermalstorage_fuzokubuzai]]
==== 付属部材：
紙障子、外付けブラインド、その他これらと同等以上の日射遮蔽性能を有し、開口部に取り付けられるもの。

[[guide_thermalstorage_nisshoushougai]]
==== 日照障害：
周囲に高い建物や常緑樹などがあることで、日射が遮蔽されること。日射の取得・利用が制限される。計画に対し、日照障害を引き起こす遮蔽物の有無を調べることが重要。

[[guide_thermalstorage_netsuyouryou]]
==== 熱容量[kJ/K]：
蓄熱部位の容積[㎥]×蓄熱材の容積比熱[kJ/(㎥･K)]。物体の温度を1K上げるのに必要な熱量。

[[guide_thermalstorage_yuukouatsusa]]
==== 有効厚さ：
蓄熱部位として計上できる材料の厚み。材料の厚さが有効厚さ以上の場合は、有効厚さまでのみを計上することができる。

[[guide_thermalstorage_yousekihinetsu]]
==== 容積比熱（kJ/㎥・℃）：
容積１㎥の物質の温度を1℃上げるのに必要な熱量。



== (修正前：詳細版）
== 用語解説
==== 日射熱：
建物が窓を通して取得する熱量のこと。日射熱を利用することは、暖房エネルギーの削減に有効な技術です。

==== パッシブソーラー暖房：
太陽熱を建築的に活用して、自然な暖房効果を得る方法。地域の気候特性や立地などの条件を勘案して、躯体・開口部の断熱仕様、日射熱取得のバランスを考えて設計を行うことが大切です。

==== 蓄熱部位：
蓄熱の利用に有効な熱容量を持つ部位をいい、天井、床（断熱区画内の床も含む）、壁（外気に接する壁 及び間仕切壁）及び界壁・界床を対象とします。(技術情報)

==== 集熱面：
真南に近い向きに面する開口部ほど集熱量は多くなります。日射熱利用による暖房効果を得るためには、集熱面となる開口部の方位は、地域区分に係わらず真南から東または西に30°以内であることが最低条件となります。

==== 付属部材：
紙障子、外付けブラインド及びその他これらと同等以上の日射遮蔽性能を有し、開口部に建築的に取り付 けられるものをいいます。(技術情報)

==== 日照障害の影響：
敷地の周囲に高い建==== 物や常緑樹などがあることなどにより、冬期において日射が遮蔽される場合に、日射の取得・利用が制限されます。設計に先立って、地形、樹木の影響なども含めて計画する建物に対し日照障害を引き起こす遮蔽物の有無を調べることが必要です。

==== 熱容量[kJ/K]：
蓄熱部位の容積[㎥]×蓄熱材の容積比熱[kJ/(㎥･K)]。熱容量の対象は、意図的に追加した材料を対象とします。

==== 有効厚さ：
材料には蓄熱部位として計上できる材料の厚み。材料の容積算定時において、材料の厚さが有効厚さ以上の場合は、有効厚さまでのみを計上することができます。有効厚さ以上の材料の蓄熱効果は小さいことを意味しています。熱が伝わりやすい材料ほど、有効厚さは大きくなります。
