== 空気集熱式太陽熱利用設備 Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野

== 省エネルギー手法の解説（入力ガイド説明文）

[[shuho_om_saiyou]]
==== 空気集熱式太陽熱利用設備の設置

空気集熱式太陽熱利用設備のうち、以下（1）～（4）の条件を全て満たし、（5）の表A.1に示す種類に該当する場合に、「設置する」を選択することができます。なお、評価対象住戸の建設される地域が8地域の場合は、空気集熱式太陽熱利用設備は評価できません。

（1）JIS A 4112またはSS－TS010に適合する空気集熱式集熱器（以下、集熱器と記す）で構成される集熱器群を有する。

（2）集熱部において太陽熱で温められた外気を、直接、または、蓄熱部とする床下を介して居室に給気する。

（3）集熱部において太陽熱で温められた外気を床下に給気する場合、床下を構成する部材の劣化対策として、防腐・防蟻処理等を施す際には、人体に影響のある薬剤は使用せず、揮発性の低い薬剤 等を選定するなどの配慮を行っている。

（4）床下を経由して外気を導入する換気方式を併用していない。また、空気集熱式太陽熱利用設備で給湯する場合に、液体集熱式太陽熱利用設備と併用して給湯を行っていない。

（5）集熱部の一部を給湯に利用するか否か、また空気搬送ファンや循環ポンプの動力を太陽光発電装置で賄っているかの組み合わせにより表A.1の番号1～8に示す8種類の空気集熱式太陽熱利用設備のいずれかに該当する。 *

NOTE: 表A.1…省エネ基準ヘルプを参照

空気集熱式太陽熱利用設備を設置する場合は、評価対象住戸が建設される地域の「年間日射地域区分」を確認して、該当する区分を選択して下さい（8地域以外）。

[[shuho_om_panelsuu]]
==== 集熱器群の数

「集熱器群」とは、評価対象に選んだ「集熱部」において同じ傾斜角で設置される、同一仕様の集熱器の集合のことを言います。ここでは、その集熱器群がいくつあるかを選択してください。例えば、同じ傾斜角で同一仕様の集熱器群を設置している場合は「1面」を選択してください。異なる2つの傾斜角で同一仕様のものを設置している場合は「2面」を選択することになります。

[[shuho_om_panel_houi]]
==== 集熱部の方位角

「集熱部」とは、同じ方位角で設置される集熱器群の集合のことを言います。

太陽熱集熱部の法線方向の水平部分が真南に対し、東回りもしくは西回りに振れた角度で示しています。下図を参考に、設置方位角を選択して下さい。

「集熱部」が複数ある場合は、面積が最も大きな集熱部の方位角を選択して下さい。最も面積が大きな集熱部が複数ある場合は、いずれか一つの集熱部を任意に選ぶことができます。

NOTE: 図…省エネ基準ヘルプを参照

[[shuho_om_fan_jirituunten_2]]
==== 空気搬送ファンの自立運転用太陽光発電装置の採用

「空気搬送ファンの自立運転用太陽光発電装置」とは、発電した電力を空気搬送ファンの動力として使用するための装置で、この装置を採用している場合は、空気搬送ファンが稼働する時刻において、その消費電力量はゼロになります。空気搬送ファンのために自立運転用太陽光発電装置を採用している場合は、「採用する」を選択してください。

[[shuho_om_fan_type]]
==== 空気搬送ファンの種別

空気を搬送するためのファンがDC（直流）ファンかAC（交流）ファンのどちらであるかを確認して選択してください。

[[shuho_om_fan_test]]
==== 機外静圧をゼロとした時の空気搬送ファンの風量

空気搬送ファンのカタログ等に記載されている機外静圧と風量の特性曲線から機外静圧をゼロとしたときの風量を読み取り、入力してください。

機外静圧と風量の特性曲線等が不明の場合は、空気集熱式太陽熱利用設備を設置された事業者（工務店もしくは製造メーカー）までお問合せください。

