

== 屋根空気集熱式ソーラーシステム：

=== 屋根空気集熱式ソーラーシステムとは
屋根空気集熱式ソーラーシステムは、太陽熱により屋根に設置した集熱部で空気を温め、その暖気を床下から居室へ搬送し、冬期には主に暖房に利用するシステムです。一方、中間期や夏期には暖気を給湯に利用します。また、集熱時は居室へ外気が給気されるため、適切な制御を行うことで、換気のエネルギー消費量をゼロとすることができます。

===== 自立循環型住宅オプション（仮）
  ・総発電量で評価

=== 目標レベル
  ☆☆☆☆☆　目標レベルと参考仕様を記載
  ☆☆☆☆
  ☆☆☆
  ☆☆
  ☆

=== 空気集熱式太陽熱利用設備の設置
  設置する
  設置しない

=== 集熱器群の数
  1面
  2面
  3面
  4面
  
=== 集熱部の設置方位角
=== 空気搬送ファンの自立運転用太陽光発電装置の採用
  採用しない
  採用する
  
=== 空気搬送ファンの種別
  DCファン
  ACファン
  
=== 機外静圧をゼロとした時の空気搬送ファンの風量
    [m3/h ] (小数点以下1桁)
  
=== 集熱した熱の給湯への利用
  利用する
  利用しない
  
=== 循環ポンプの自立運転用太陽光発電装置の採用
  採用しない
  採用する
  
=== 給湯部のタンク容量
    [L ] (整数)
    
=== 集熱後の空気を供給する空間
  床下空間
  床下空間以外の室内空間
  
=== 集熱後の空気を供給する床下の面積の割合
   [% ] (整数)
   
=== 床下空間の断熱
  断熱区画外
  断熱区画内
  
=== 集熱器群その1
=== 集熱器群の面積
    [m2 ] (小数点以下1桁)

=== 集熱器群の傾斜角

=== 集熱器群の仕様の入力
  入力しない
  入力する
  
=== 集熱器の集熱効率特性線図一次近似式の切片
   [m2 ] (小数点以下1桁)
   
=== 集熱器群の面積
   [m2 ] (小数点以下1桁)
   
=== 集熱器群の面積
   [m2 ] (小数点以下4桁)

=== 設計上の配慮事項・暮らし方の留意点

==== 設置方位と傾斜角
　方位による効率は、真南向きを利用効率を100%とすると、東西は85～89％程度、北は67～75％程度です。傾斜角は、10°（1 寸8 分勾配程度）から40°（8 寸4 分勾配程度）の範囲では、ほとんど差はありません。方位には多少注意が必要ですが、屋根の勾配について特別に配慮が必要になることはなく、好みのデザインの屋根に設置することが可能といえます（新築版P84図）

==== 局地的条件
　太陽光発電は、日影ではほとんど発電しません。そのため、北向きの傾斜地や山間部など、日照時間が短くなる場合や、降雪によって太陽電池モジュールが雪で覆われたままだと、期待される発電量が得られいため注意が必要です。また、近隣の将来状況も想定して検討する必要があります。

==== 太陽光発電システムの設置上の注意
　太陽電池モジュールを屋根に設置する場合、風の強い地域では、暴風による破損に注意が必要です。また、積雪地では、発電用の機器や部材が積雪による荷重に耐えるようにするとともに、太陽電池モジュールからの落雪に十分注意する必要があります。
