

== 屋根空気集熱式ソーラーシステム：

=== 屋根空気集熱式ソーラーシステムとは
屋根空気集熱式ソーラーシステムは、太陽熱により屋根に設置した集熱部で空気を温め、その暖気を床下から居室へ搬送し、冬期には主に暖房に利用するシステムです。一方、中間期や夏期には暖気を給湯に利用します。また、集熱時は居室へ外気が給気されるため、適切な制御を行うことで、換気のエネルギー消費量をゼロとすることができます。

===== 自立循環型住宅オプション（仮）
  ・総発電量で評価

=== 目標レベル
  ☆☆☆☆☆　目標レベルと参考仕様を記載
  ☆☆☆☆
  ☆☆☆
  ☆☆
  ☆

=== 空気集熱式太陽熱利用設備の設置
  設置する
  設置しない

=== 集熱器群の数
  1面
  2面
  3面
  4面
  
=== 集熱部の設置方位角
=== 空気搬送ファンの自立運転用太陽光発電装置の採用
  採用しない
  採用する
  
=== 空気搬送ファンの種別
  DCファン
  ACファン
  
=== 機外静圧をゼロとした時の空気搬送ファンの風量
    [m3/h ] (小数点以下1桁)
  
=== 集熱した熱の給湯への利用
  利用する
  利用しない
  
=== 循環ポンプの自立運転用太陽光発電装置の採用
  採用しない
  採用する
  
=== 給湯部のタンク容量
    [L ] (整数)
    
=== 集熱後の空気を供給する空間
  床下空間
  床下空間以外の室内空間
  
=== 集熱後の空気を供給する床下の面積の割合
   [% ] (整数)
   
=== 床下空間の断熱
  断熱区画外
  断熱区画内
  
=== 集熱器群その1
=== 集熱器群の面積
    [m2 ] (小数点以下1桁)

=== 集熱器群の傾斜角

=== 集熱器群の仕様の入力
  入力しない
  入力する
  
=== 集熱器の集熱効率特性線図一次近似式の切片
   [m2 ] (小数点以下1桁)
   
=== 集熱器群の面積
   [m2 ] (小数点以下1桁)
   
=== 集熱器群の面積
   [m2 ] (小数点以下4桁)

=== 設計上の配慮事項・暮らし方の留意点

==== 24時間換気の停止
　集熱空気を床下へ搬送する時間帯は、居室に十分な外気が導入されるので、24 時間換気は停止することができます。したがって、適切に24 時間換気システムと連動させることで、換気エネルギーの削減が可能になります。

==== 床下空間の配慮
　屋根空気集熱式ソーラーシステムは屋根、床下、居室の順に集熱空気を搬送するシステムですので、建物の気密性が重要になります。とくに、基礎と土台の取合部は、気密パッキン等を利用するなどして、気密性の確保につとめて下さい。集熱空気が居室に搬送される前に経由する床下空間は清浄に保つ必要があります。床下木部には、シロアリに強い樹種を用いることをおすすめしますが、やむを得ず薬剤を用いて処理する場合には、人体に影響の少ない薬剤を使用することを心がけてください。

==== プランの配慮
　暖房集熱時に、暖気が各居室に均等に行き渡るように、連続した空間構成とすることが望まれます。悪天候などで太陽集熱できない日が続く場合は、居室ごとに補助暖房を使うことになります。その際に、暖房が不要な居室は間仕切り扉などで区切れるように工夫しておくことで、暖房エネルギーを削減することができます。
