== 用語解説

==== 太陽熱温水器：
日射で水を直接加熱する方式で、簡便でイニシャルコストが低いメリットがありますが、冬期は凍結防止のため水抜きをする必要があるので集熱はできません。「集熱部」と「貯湯部」の2つから構成されます。（表３）(温ガp.112、119)

==== ソーラーシステム：
不凍液を循環させて集熱する方式で、冬期も集熱が可能ですが、設備が複雑になりイニシャルコストは高くなります。また、集熱中は不凍液の循環ポンプが常に電力を消費するため、消費電力は大きくなります。不凍液循環ポンプの消費電力が通常機種で80W程度あり、無視できない電力量になります。（表３）(温ガp.112、119)

==== 集熱部：
太陽熱を集める部分。できるだけ日当たりのよい場所に設置する必要があります。
集熱部の面積は集熱量の多少に最も影響します。太陽熱を集熱する部分の面積について、日本工業規格（JIS）では、太陽熱温水器については「有効集熱面積」（JISA4111）、ソーラーシステムについては「集熱体面積」（JISA4112）と別々に定義されていますが、自立循環型住宅では「有効集熱面積」に統一しています。(温ガp.112、117、120)

==== 貯湯部：
温められた湯を蓄える部分(温ガp.112)

==== 補助熱源：
悪天候時には集熱ができない時、貯湯分が足りなくなった場合などに備えた補助的に給湯する熱源。一般にガス・石油を燃料とする燃焼式となります。(温ガp.124)

==== 傾斜角：
積雪の影響を考慮しない場合、水平面に対して30°で年間集熱量が最大になります。ただし、傾斜角による集熱量の差はそれほど大きくありません。屋根勾配よりも急な角度に設置する場合は、架台が必要となります。(図３) (温ガp.122)

==== 年間日射量地域区分：
１年間に取得する日射量によって、全国をA1~A5の５つの地域に区分したもの。太陽光発電、太陽熱給湯による省エネルギー効果の算出には、この区分を使用します。設計する敷地がどの区分に属するかは、○図を参照してください。（温ガp.37）

==== 三方弁：
太陽熱と補助熱源を切り替えて使用する方式。(表6)

==== ソーラー接続ユニット：
太陽熱給湯装置と補助熱源の接続に用い、金剛や補助熱源の制御を行う装置。（温ガp.113）。設定温度に従って太陽熱と補助熱源を使い分ける。(図7)
