
=== 液体集熱式太陽熱利用設備とは
住宅におけるエネルギー消費のうち、給湯に費やされる割合はたいへん大きく、自然エネルギーである太陽熱を利用した給湯システムの導入は、省エネルギーの観点からは有効な手段となります。

=== 目標レベル
  ☆☆☆☆☆　暖房設備の目標レベルと参考仕様を記載
  ☆☆☆
  ☆

=== 液体集熱式太陽熱利用設備の設置
 ・設置する
 ・設置しない
 
=== 太陽熱給湯設備の種類
 ・太陽熱温水器(太陽熱給湯1)
 ・ソーラーシステム(太陽熱給湯2)
 
 
=== 太陽熱温水器（太陽熱給湯１）を設置する場合

=== 面積の入力方法
 ・集熱部面積又は集熱貯湯部総面積を入力する
 ・有効集熱面積を入力する
=== 集熱部面積又は集熱貯湯部総面積
   [m2 ] (小数点以下1桁)

=== 集熱部の設置方位角　　　[°]

=== 集熱部の設置傾斜角　　　[°]


=== ソーラーシステム（太陽熱給湯2）を設置する場合

=== 面積の入力方法
 ・集熱部面積又は集熱貯湯部総面積を入力する
 ・有効集熱面積を入力する
 
=== 集熱部の設置方位角　　　[°]

=== 集熱部の設置傾斜角　　　[°]

=== 貯湯タンクの容量　　　[L]

=== 設計上の配慮事項・暮らし方の留意点

==== 設置方位と傾斜角
　方位による効率は、真向きを利用効率を100%とすると、東西は85～89％程度、北は67～75％程度です。傾斜角は、10°（1 寸8 分勾配程度）から40°（8 寸4 分勾配程度）の範囲では、ほとんど差はありません。方位には多少注意が必要ですが、屋根の勾配について特別に配慮が必要になることはなく、好みのデザインの屋根に設置することが可能といえます（新築版P84図）

==== 局地的条件
　太陽光発電は、日影ではほとんど発電しません。そのため、北向きの傾斜地や山間部など、日照時間が短くなる場合や、降雪によって太陽電池モジュールが雪で覆われたままだと、期待される発電量が得られいため注意が必要です。また、近隣の将来状況も想定して検討する必要があります。

==== 太陽光発電システムの設置上の注意
　太陽電池モジュールを屋根に設置する場合、風の強い地域では、暴風による破損に注意が必要です。また、積雪地では、発電用の機器や部材が積雪による荷重に耐えるようにするとともに、太陽電池モジュールからの落雪に十分注意する必要があります。
