== 太陽熱給湯マニュアル Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野

== 省エネルギー手法の解説（入力ガイド説明文）

=== 液体集熱式太陽熱利用給湯設備の設置

・太陽熱を利用して給湯する装置のうち、規定する条件に適合する「太陽熱温水器」や「ソーラーシステム」を設置している場合に、「設置する」を選択することができます。ただし、空気集熱式太陽熱利用設備で給湯の一部を賄うものとは併用はできません（空気集熱式太陽熱利用設備を暖房のみに使用する場合はこの限りではありません）。

・太陽熱利用給湯設備を設置する場合は、評価対象住戸が建設される地域の「年間日射地域区分」を確認して、該当する区分を選択して下さい。


=== 設備の選択

・太陽熱温水器（太陽熱給湯1）とは、太陽熱を利用して給湯する装置のうち、JIS A4111 に規定される集熱部と貯湯部との間の熱輸送に自然循環作用を利用する自然循環形温水器、または集熱部と貯湯部とが一体となったくみ置形温水器で、JIS A4111「太陽熱温水器」に規定される集熱性能に適合している機器を評価対象とします。

・ソーラーシステム（太陽熱給湯2）とは、太陽熱を利用して給湯する装置のうち、JIS A4112 に規定される集熱媒体を強制循環する太陽集熱器と、JIS A4113 に規定される蓄熱媒体により熱エネルギーを顕熱として貯蔵する太陽蓄熱槽を組み合わせた機器の総称です。JIS A4112「太陽熱集熱器」に規定される集熱性能に適合している製品でかつ液体集熱式集熱器のみを評価対象とします。

NOTE: イラスト　hotwater010

=== 太陽熱温水器(太陽熱給湯1)を設置する場合

==== 面積の入力方法（太陽熱給湯1）

・「集熱部総面積又は集熱貯湯部総面積」とは、自然循環形温水器の場合は JISA4111 に規定される集熱部総面積、くみ置形温水器の場合は同じく JIS A4111 に規定される集熱貯湯部総面積になります。

・「有効集熱面積」とはISO 9488:1999の8.6節（aperture area）に規定される方法により算出した面積になります。

==== 集熱部の設置方位角

・太陽熱集熱部の法線方向の水平部分が真南に対し、東回りもしくは西回りに振れた角度で示しています。下図を参考に、設置方位角を選択して下さい。

NOTE: イラスト　hotwater011

==== 集熱部の設置傾斜角

・太陽熱集熱部が設置された傾斜角（水平面からの角度）を選択して下さい。90 度を超える場合は 90 度を選択して下さい。

・尺貫法から換算する場合は、下表を参考にしてください。

NOTE: 表　屋根勾配換算

==== 面積の入力方法（ソーラーシステム：太陽熱給湯2）

・「集熱器総面積」とは、JISA4112 に規定される集熱器総面積になります。

・「有効集熱面積」とはISO 9488:1999の8.6節（aperture area）に規定される方法により算出した面積になります。

==== 貯湯タンクの容量

・貯湯タンクの容量は、 JIS A 4113（太陽蓄熱槽）で規定される貯湯槽容量で確認することを前提とし、小数点第一位を四捨五入し整数値とした値で入力して下さい。ただし、JIS A 4113（太陽蓄熱槽）で規定される貯湯槽容量の代わりに、別途定める方法により計測した値を使用することもできます。

住宅・建築物の省エネルギー基準及び低炭素建築物の認定基準に関する技術情報
貯湯タンクの容量の確認方法については、「設計一次エネルギー消費量算定方法」の「7-2　太陽熱利用給湯設備　付録A ソーラーシステムのタンク容量」を参照して下さい。

・ソーラーシステムの貯湯タンクが複数ある場合はそれぞれの貯湯タンクのタンク容量を合計した値を入力して下さい。


