== 太陽熱給湯マニュアル Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野

== 省エネルギー手法の解説（入力ガイド説明文）

[[shuho_sw_saiyou]]
=== 液体集熱式太陽熱利用給湯設備の設置

・太陽熱を利用して給湯する装置のうち、規定する条件に適合する「太陽熱温水器」や「ソーラーシステム」を設置している場合に、「設置する」を選択することができます。ただし、空気集熱式太陽熱利用設備で給湯の一部を賄うものとは併用はできません（空気集熱式太陽熱利用設備を暖房のみに使用する場合はこの限りではありません）。

・太陽熱利用給湯設備を設置する場合は、評価対象住戸が建設される地域の「年間日射地域区分」を確認して、該当する区分を選択して下さい。

[[shuho_sw_sw]]
=== 設備の選択

現在流通している太陽熱給湯装置は、太陽熱温水器とソーラーシステムの2種類に主に分類でき、それぞれ一般的な仕様が概ね決まっています。日本において現状で一般的な太陽熱温水器・ソーラーシステムの仕様と特徴を下表に示します。これらの特性を十分に理解して、機種を選択することが重要です。

NOTE: 表：温暖地版テキストP119　表３

=== 太陽熱温水器(太陽熱給湯1)を設置する場合

[[shuho_sw_sr1_menseki]]
==== 面積の入力方法（太陽熱給湯1）

・「有効集熱面積」とは、集熱部（集熱パネル）の中で実際に太陽熱を集めることができる面積です。詳しくは「自立循環型住宅への設計ガイドライン（温暖地版）」P120を参照してください。

・集熱面積を大きくとることは太陽熱を十分に集める上で最も重要となります。集熱面積が2㎡程度と小さい機種もありますが、有効な集熱量を得るには3㎡程度の集熱面積は必要です。

TIP: 温暖地版ガイドラインP120

[[shuho_sw_sr1_angle]]
==== 集熱部の設置方位角

・太陽熱集熱部の法線方向の水平部分が真南に対し、東回りもしくは西回りに振れた角度で示しています。下図を参考に、設置方位角を選択して下さい。

NOTE: イラスト　hotwater011

・集熱部を設置する方位はできるだけ南向きとすることが望ましいですが、多少南からずれていても集熱できます。南向きに設置できない場合、東向きでは集熱が午前中に行われるため、給湯需要が集中する夜間までの放熱ロスが大きくなるので、西向きの方が有利です。北向きではほとんど集熱できません。

・将来的に隣接建物等の影とならない位置を選ぶことが必要です。

TIP: 温暖地版ガイドラインP122

[[shuho_sw_sr1_slope]]
==== 集熱部の設置傾斜角

・太陽熱集熱部が設置された傾斜角（水平面からの角度）を選択して下さい。90 度を超える場合は 90 度を選択して下さい。

・尺貫法から換算する場合は、下表を参考にしてください。

NOTE: 表　屋根勾配換算

・集熱部の設置角度（傾斜角）は、積雪の影響を考慮しない場合、水平面に対して30°で年間集熱量が最大になります。ただし、傾斜角による集熱量の差はそれほど大きくありません。

・積雪地では、傾斜角を大きくすることで冬期に雪が集熱パネルから容易に落ちるようになるため、集熱量の増加が期待できます。

[[shuho_sw_sr2_menseki]]
==== 面積の入力方法（ソーラーシステム：太陽熱給湯2）

・「有効集熱面積」とは、集熱部（集熱パネル）の中で実際に太陽熱を集めることができる面積です。詳しくは「自立循環型住宅への設計ガイドライン（温暖地版）」P120を参照してください。

・集熱面積を大きくとることは太陽熱を十分に集める上で最も重要となります。集熱面積が2㎡程度と小さい機種もありますが、有効な集熱量を得るには3㎡程度の集熱面積は必要です。

TIP: 温暖地版ガイドラインP120

[[shuho_sw_sr2_tankyouryo]]
==== 貯湯タンクの容量

・ソーラーシステムの場合は、貯湯槽の容量を選択できる場合があります。タンク容量が小さいとすぐに貯湯槽の温度が貯湯温度の上限に達してしまい、集熱量が制限されてしまいます。

・一般に、集熱面積4㎡に対して貯湯槽の容量は200L程度が適当とされています。

・ソーラーシステムの貯湯タンクが複数ある場合はそれぞれの貯湯タンクのタンク容量を合計した値を入力して下さい。

TIP: 温暖地版ガイドラインP124、省エネ基準プログラムヘルプ

