
=== 太陽熱給湯設備（液体集熱式太陽熱利用設備）とは
太陽熱を集める「集熱部」と温められた湯を蓄える「貯湯部」から構成された給湯に利用する機器です。住宅におけるエネルギー消費のうち、給湯に費やされる割合はたいへん大きく、自然エネルギーである太陽熱を利用した給湯システムの導入は、省エネルギーの観点からは有効な手段となります。

===== 自立循環型住宅オプション（仮）
  特になし

=== 目標レベル
  ☆☆☆☆☆　目標レベルと参考仕様を記載
  ☆☆☆☆
  ☆☆☆
  ☆☆
  ☆

=== 太陽熱給湯設備の設置
 ・設置する
 ・設置しない
 
=== 太陽熱給湯設備の種類
 ・太陽熱温水器(直接集熱)
 ・ソーラーシステム(間接集熱)
 
 
=== 太陽熱温水器（直接集熱）を設置する場合

=== 面積の入力方法
 ・集熱部面積又は集熱貯湯部総面積を入力する
 ・有効集熱面積を入力する
=== 集熱部面積又は集熱貯湯部総面積
   [m2 ] (小数点以下1桁)

=== 集熱部の設置方位角　　　[°]

=== 集熱部の設置傾斜角　　　[°]


=== ソーラーシステム（間接集熱）を設置する場合

=== 面積の入力方法
 ・集熱部面積又は集熱貯湯部総面積を入力する
 ・有効集熱面積を入力する
 
=== 集熱部の設置方位角　　　[°]

=== 集熱部の設置傾斜角　　　[°]

=== 貯湯タンクの容量　　　[L]

=== 設計上の配慮事項・暮らし方の留意点

==== 設置方位と傾斜角
　方位と傾斜角による効率は、真南向きで傾斜角30°が最もよいが、効率の劣る北面方位でも90%程度の効率、傾斜角も効率の劣る垂直面でも90%の効率と、方位や傾斜角に関して、特別に配慮が必要になることはなく、好みのデザインの屋根に設置することが可能といえます。

==== 計画上の配慮
　屋根上に設置した集熱部（集熱パネル）は、風による外力により、上方向に吹き上がる・横ずれを生じるなどの恐れがあるため、しっかりと固定して設置します。また、太陽熱温水器に関しては、冬期に凍結防止のため水抜きをする必要があるので、水抜きが容易にできるように配慮します。集熱部と貯湯部が分かれているソーラーシステムでは、配管からの熱損失を抑えるため、集熱部、貯湯部、給湯機の相互の距離がなるべく短くなるように配置する必要があります。

==== 効率の良い運転・制御方法の配慮
　太陽熱温水の温度が給湯設定温度より低温の場合にも、電源を切られた補助熱源は燃焼しないため給湯温度はなりゆきになりますが、台所・洗面所での湯消費には問題ない場合が少なくありません。給湯の温度が低すぎると感じた時だけ補助熱源の電源を入れるようにすると、非常に省エネになります。
