
== 断熱外皮計画 Aパート：
WEB プログラムのメニュー情報（要素技術を考えるにあたり大切な情報と、評価に必要な最低限の情報）


=== 断熱外皮計画とは
住宅の室内と室外との境界（外皮）における熱の出入りの抑制を目的としています。断熱化をはかった住宅は、無断熱の住宅に比べ、はるかに少ないエネルギーで冬期の室内温熱環境を快適にすることができます。また、外皮の高断熱化には漏気防止や結露対策が不可欠で、これらを適切に配慮した材料・層構成を選択することにより、快適な温熱環境と躯体性能の確保が可能になります。

===== 自立循環型住宅オプション（仮）
  ・開口部付属部材の夏冬変化
  ・豊富な開口部付属部材

=== 目標レベル
  ☆☆☆☆☆　目標レベルと参考仕様を記載
  ☆☆☆☆
  ☆☆☆
  ☆☆
  ☆
  
=== 外皮性能の評価方法
  評価方法の選択
  ・当該住戸の外皮面積を用いて外皮性能を評価する
  ・当該住戸の外皮面積を用いず外皮性能を評価する（別途計算）
  ・当該住戸の外皮面積を用いず外皮性能を評価する（ここで計算）
 
NOTE: 自立循環の簡易計算を追加できると良い
 
外皮面積の合計
  ・外皮面積の合計（m2）：  307.51　 (有効数値：小数点以下2桁)

=== 熱貫流率
  ・外皮平均熱貫流率(UA)：  0.87　 (有効数値：小数点以下2桁)

=== 床下空間を経由して外気を導入する換気方式の採用
  床下空間を経由して外気を導入する換気方式の採用
   ・利用しない
   ・通年利用する
外気が経由する床下の面積の割合 (%)：　　 (整数)
  床下空間の断熱
   ・断熱区間外
   ・断熱区間内
 
=== 設計上の配慮事項・暮らし方の留意点

==== ライフスタイルの指向などの確認
　室内温熱環境の質を表すものとして、室内の上下間や室間の温度むら（温度差）、暖房を止めた後の室温の低下が代表的な指標となります。人が感じる快・不快の境は、わずか1～2℃の差が大きく影響します。住まい手がどの程度の温熱環境を望んでいるのかを確認した上で、目標レベルを設定して下さい。

NOTE: 温暖地版P133図3、P134図4
 
==== 断熱計画の検討
　木造住宅の断熱方法は、充填断熱と外張断熱の2つに大別されます。また、高い断熱性能を求める場合は断熱材の厚みを確保するため、同じ部位で
充填断熱と外張断熱の両方を併用することもあります。それぞれ長所・短所がありますので、住宅の部位ごとに適した方法を選択することが大切です。
  
==== 防露措置の検討
　住宅内では、4人家族が生活している場合、人体からや生活行為によって、1 日に約3～5ℓの水分が発生します。冬期に、これらの水分が壁や屋根の内部に浸入しそのまま放置されると、冷やされて内部結露が生じてしまいます。これを防ぐために室内側には極力連続して防湿層を設置するなどの措置が必要となります。
