== 断熱外皮計画 Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野

== 省エネルギー手法の解説（入力ガイド説明文）

=== 外皮性能の評価方法

[[shuho_ip_houhou]]
==== 評価方法の選択

・当該住戸の外皮面積を用いて外皮性能を評価する」とは、当該住戸の屋根・天井、壁、窓、床などの外皮面積と各部位の断熱性能を用いて外皮性能（UA、ηAC、ηAH）を評価する方法です。一次エネルギー消費量の評価において、外皮性能評価時に算出した当該住戸の「外皮面積の合計」を用います。「当該住戸の外皮面積を用いず外皮性能を評価する（一戸建ての住宅で木造の単位住戸の評価に限る）」場合に比べて、外皮性能を適切に反映することができ、多くの場合に評価は高く算出されます。

・一戸建ての住宅で木造の単位住戸の評価に限り、「当該住戸の外皮面積を用いず外皮性能を評価する」方法が選択できます。当該住戸の屋根・天井、壁、床などの外皮面積を算出せず簡易評価式により外皮性能を評価する方法です。一次エネルギー消費量の評価では当該住戸の「床面積の合計」から推計値した値を用いますので「外皮面積の合計」を入力する必要はありません。既に別途エクセルや評価ツールなどを用いて事前に計算した外皮性能（UA、ηAC、ηAH）をお持ちの場合は、「当該住戸の外皮面積を用いず外皮性能を評価する（別途計算）」を選択して評価してください。各部位の熱貫流率や窓の日射取得率を直接入力して評価する場合は、「当該住戸の外皮面積を用いず外皮性能を評価する（ここで計算）」を選択して評価してください。

=== 断熱構造による住戸の種類

NOTE: 『当該住戸の外皮面積を用いず外皮性能を評価する（別途計算）』または『当該住戸の外皮面積を用いず外皮性能を評価する（ここで計算）』の場合に表示

[[shuho_ip_yuka_dannetsu]]
==== 住戸の種類の選択 

・「床断熱住戸」とは、玄関等及び浴室を除いた部分の外皮を床とする住戸、「基礎断熱住戸」とは、玄関等及び浴室を除いた部分の外皮を土間床等の外周部の基礎とする住戸のことです。

=== 外皮面積の合計

[[shuho_ip_sougaihi_menseki]]
==== 外皮面積の合計

・天井・屋根、壁、開口部、床等の外皮面積の合計のことです。

・計算した結果は、小数点第3位を四捨五入した小数点以下2桁で入力してください。

[[shuho_ip_u_roof]]
=== 熱貫流率と線熱貫流率

NOTE: 『当該住戸の外皮面積を用いず外皮性能を評価する（ここで計算）』の場合に解説を表示

・1）熱貫流率

・当該住戸の外皮の各部位における熱貫流率の値とします。各部位で複数の異なる仕様を有する場合は、熱貫流率に温度差係数を乗じた値が最も大きい部位の熱貫流率の値を入力してください。

・窓の熱貫流率の計算において、窓の面積（当該窓が2以上の場合においてはその合計の面積）が単位住戸の床面積に0.02を乗じた数値以下となるものは計算対象から除くことができます。

・床断熱住戸において浴室部分の外皮を床とする場合は、浴室の床の熱貫流率の値を入力し、浴室の床がない場合はその他の床の熱貫流率を浴室の床の熱貫流率として入力してください。

・床断熱住戸において浴室部分の外皮を土間床等の外周部の基礎とする場合は、浴室の基礎の熱貫流率の値を入力し、基礎断熱住戸においては、その他の基礎の熱貫流率を浴室の基礎の熱貫流率として入力してください。

・2）線熱貫流率

・当該住戸の外皮の各部位にける線熱貫流率の値とします。各部位で複数の異なる仕様を有する場合は、線熱貫流率に温度差係数を乗じた値が最も大きい部位の線熱貫流率の値を入力してください。

・床断熱住戸において浴室部分の外皮を土間床等の外周部の基礎とする場合は、土間床等の外周部の線熱貫流率の値を入力し、基礎断熱住戸においては、その他の土間床等の外周部の線熱貫流率を浴室の土間床等の外周部の線熱貫流率として入力してください。

[[shuho_ip_u_value]]
==== 外皮平均熱貫流率(UA) 

NOTE: 『当該住戸の外皮面積を用いて外皮性能を評価する』『当該住戸の外皮面積を用いず外皮性能を評価する（別途計算）』の場合に表示

・外皮平均熱貫流率とは、単位温度差あたりの外皮熱損失量のことで、室内外の温度差が1度のときの、外皮（天井・屋根、壁、床等）の熱損失量の合計を外皮面積の合計で除した値になります（単位はW／K）。

・なお、共同住宅の場合は、部位の熱損失量に界壁と界床の熱損失量も含みます。界壁とは、共同住宅等において隣接する住戸や共用部に接する壁のことです（戸境壁ともいう）。界床とは、共同住宅等において隣接する住戸及び共用部に接する床のことです（戸境床ともいう）。

・計算した結果は、小数点第3位以下を切り上げて、小数点以下2桁で入力してください。

### 床下空間を経由して外気を導入する換気方式の利用

・床下換気システムとは、床下空間を経由して外気を室内へ導入する換気方式を採用したシステムです。外気温度に比べて室温変動が緩やかな床下空間に外気を導入することにより、換気負荷を低減させ、暖冷房のエネルギー消費量を削減する効果が見込めます。

・床下空間を経由して外気を導入する換気方式の暖冷房負荷削減効果を評価するためには、以下の（1）～（4）のすべての要件を満たしていることが条件となります。

(1)	地盤に接する床下空間を経由して外気を室内へ供給し、かつ、当該住戸全般の換気量を確保する第一種又は第二種換気設備を有していること。

(2)	基礎断熱工法を採用しており、かつ、床下空間における基礎等の底盤中央部分は、地盤面との熱交換の妨げとなる断熱材等を配置しないこと。

(3)	こちらに記載されいている熱交換型換気設備との併用は認めない。

(4)	床下を構成する部材の劣化対策として、防腐・防蟻処理等を施す際には、人体に影響のある薬剤は使用せず、揮発性の低い薬剤等を選定するなどの配慮をすること。

・暖房の一部を空気集熱式太陽熱利用設備で賄う場合は「利用しない」を選択してください。



