== 用語解説
==== 外皮：
外気等（外気または外気に通じる床裏、小屋裏、天井裏等）に接する天井（小屋裏または天井裏が外気に通じていない場合には屋根）、壁、床及び開口部（省エネ基準解説書p.205）

==== 日射取得熱：　
窓から入ってくる日射の熱を得ること

==== 内部発熱：
生活の中で発生する熱

==== 自然室温：
暖房していない部屋の室温

==== 非暖房室： 
暖房していない部屋

==== 体感温度：
人が感じる温度

==== 平均放射温度：
周囲の窓・壁・床等の表面温度

==== 熱損失係数：
一般的に「Ｑ値」と呼ばれており、住宅の断熱性能を数値的に表す指標です。値が小さいほど断熱性能が高いことを表します。熱損失係数は、外壁、天井、床などの住宅の各部位から逃げる熱量（熱損失量）および換気・漏気にともなう熱損失量を計算し、住宅の延床面積で除して算出します。室内外の温度差が1℃の時、住宅内部から外部へ逃げ出す単位時間（秒）、床面積1㎡当たりの熱量（ジュール）です。

==== 外皮平均熱貫流率（UA値）：
外皮の断熱性の評価。住宅の内部から、床、外壁、屋根、開口部などを通過して外部へ逃げる熱量を外皮全体の面積で除した値。小さいほど熱が逃げにくく、省エネルギー性能が高いことを示します（参照：ホームズ君よくわかる省エネ）。内外の温度差が1度の場合の部位の熱損失量の合計を外皮等の面積で除した値。（省エネ基準解説書p.205）

==== 熱伝導率：
内外の温度差1度の場合において1㎡あたりに材料内を熱伝導により移動する熱量をワットで表した数値（省エネ基準解説書p.207）

==== 熱抵抗（Ｒ値）：
材料内および空気層を熱が流れる場合の抵抗をいい、内外の温度差が1度の場合において1㎡あたりに貫流する熱量の逆数をワットで表した数値（省エネ基準解説書p.207）

==== 熱貫流率（Ｕ値）：
内外の温度差1度の場合において1㎡あたり貫流する熱量をワットで表した数値。当該部位を熱の貫流する方向に構成している材料の種類、厚さ、熱狂により貫流する熱量等を勘案して算出するものとする（省エネ基準解説書p.207）。

==== 断熱層の基本構成：　→図（温ガp164図13）

==== 充填断熱：
柱・間柱の間、垂木の間、根太の間などの構造材の間に断熱材を充填する断熱工法をいいます。→図（温ガp141図９）

==== 外張断熱：
軸組、構造体の外側に断熱層を設ける断熱工法をいいます。→図（温ガp141図９）

==== 併用断熱：
住宅の部位ごとに適した方法を選択することが大切です。高い断熱性能を求める場合は断熱材の厚みを確保するため、同じ部位で充填断熱と外張断熱の両方を併用する（充填＋付加断熱工法とも呼ばれています）こともあります。

==== 天井断熱：
最上階や下屋の天井上に断熱材を敷設する断熱工法。熱的境界である天井面に断熱施工を施すことをいう（省エネ基準解説書p.206）
→図（図47天井断熱-1、図48天井断熱-2、図49天井垂木工法による天井断熱、図50ブローイング工法による天井断熱）

==== 屋根断熱：
屋根構造のなかに断熱材を仕込む断熱工法。垂木や登り梁の間に仕込む充填断熱と、野地板の上に敷きこむ外張断熱があります。→図（温ガp185図52屋根断熱）

==== 桁上断熱：
桁や小屋梁の上端を揃えて合板を張り、その上に断熱材を施工して外張断熱とする断熱手法。断熱材の種類や厚さが限定されない、容易に施工ができる、間仕切り壁の気流止め対策が不要になるなどの長所があります。→図（温ガp184図51桁上断熱）

==== 床断熱：
床下に断熱材を敷設する断熱工法。根太や大引の間に敷きこむ。→図（温ガp179図41ボード状断熱材の施工状況）

==== 基礎断熱：
基礎の立ちあがり部分に断熱をする工法。基礎の内側に張る場合と外側に張る場合がある。→図（温ガp180図42基礎断熱、図43基礎断熱（浴室土間部分））

==== 土間床断熱：
土間下に透水性の小さな断熱材を施工する。施工の容易さや確実さを考えると、玄関土間などには土間床断熱が適しています。→図（温ガp181図44土間床断熱）

==== 温度差係数：
部位の接する隣接空間等との想定される温度差を勘案し、当該部位の熱損失量を補正する係数（省エネ基準解説書p.205）

==== 換気熱損失：
換気による熱損失

==== 防露措置：
壁体内の結露防止対策。原則として、室内から躯体内への水蒸気の浸入を防止する（防湿）、躯体内の水分を速やかに排出する（排湿）の双方に配慮する。

==== 透湿抵抗比：
断熱層の外気側を境界線（透湿抵抗中心）として、断熱層から室内側の材料の透湿抵抗の総和を、断熱層より外気側の材料の透湿抵抗の総和で除した値。
透湿抵抗比＝（室内側透湿抵抗の和R’r）÷（外気側透湿抵抗の和R’o）＝（r’4＋r’5＋r’6）÷（r’1＋r’2＋r’3）
透湿抵抗比の値を大きくする（すなわち、室内側の透湿抵抗を大きくする、または、外気側の透湿抵抗を小さくする）ことにより、壁体内が結露しにくい状況となります。

==== 気流止め：
断熱効果を十分に発揮させるためには、床下から壁（外壁・間仕切り壁）への気流と、壁から小屋裏への気流を止めることが必要です。そのために、壁の上下端部に「気流止め」を設置します。

==== 防湿フィルム：
別張り防湿フィルムについては厚さ0.1㎜以上のものを使用するのが一般的。防湿フィルム付き断熱材については0.05㎜以上の防湿フィルムが付属しているものの使用が推奨されます。いずれの場合も長期的な耐久性を考慮して、JISA6930（住宅用プラスチック系防湿フィルム）を満たす防湿フィルムを使用します。→図（温ガp179図39）
