== 用語解説（簡易版）

[[guide_ip_gaihi]]
==== 外皮：
外気に接する天井、壁、床及び開口部

[[guide_ip_nisshanetsushutoku]]
==== 日射取得熱：
窓から日射の熱を得ること

[[guide_ip_naibuhatsunetsu]]
==== 内部発熱：
生活の中で発生する熱。調理や人体から発生する熱。

[[guide_ip_shizenshitsuon]]
==== 自然室温：
暖房していない部屋の室温

[[guide_ip_hidanboushitsu]]
==== 非暖房室：
暖房していない部屋

[[guide_ip_taikanondo]]
==== 体感温度：
人が感じる温度

[[guide_ip_heikinhoushaondo]]
==== 平均放射温度：
窓・壁・床等の表面温度

[[guide_ip_q]]
==== 熱損失係数：
一般的には「Ｑ値」と呼ばれ、住宅の断熱性能を表す指標。値が小さいほど断熱性能が高い。

[[guide_ip_ua_value]]
==== 外皮平均熱貫流率（UA値）：
外皮の断熱性の評価。住宅の内部から、床、外壁、屋根、開口部などを通過して外部へ逃げる熱量を外皮全体の面積で除した値。小さいほど熱が逃げにくく、省エネルギー性能が高い。

[[guide_ip_netsudendoritsu]]
==== 熱伝導率：
熱の伝わりやすさを表す値。裏表の温度差1度の場合に厚み1mの材料1㎡あたりに伝わる熱量。値が小さいほど伝わる熱が少なく、断熱性能が高いことになる。（旭化成の断熱材HPより）

[[guide_ip_r]]
==== 熱抵抗（Ｒ値）：
材料の熱の伝えにくさの指標（単位：㎡・K/W)。値が大きいほど熱が伝わりにくく、断熱性能が高いことになる。熱抵抗値R（単位：㎡K/W）=断熱材の厚み（単位：ｍ）÷熱伝導率λ（単位：W/m・K）

[[guide_ip_u_value]]
==== 熱貫流率（Ｕ値）：
室内と外気温の差が1度の場合に、1㎡あたり1秒間に伝わる熱量のこと。建物の部位の熱の伝わりやすさを表した値（旭化成の断熱材HPより）。熱の伝わる方向に材料の種類、厚さ、熱橋により貫流する熱量等を勘案して算出する（省エネ基準解説書p.207）。

[[guide_ip_psi_value]]
==== 線熱貫流率（Ψ値）：

[[guide_ip_dannetsusou]]
==== 断熱層の基本構成：
→図（温ガp164図13）

[[guide_ip_jutendannetsu]]
==== 充填断熱：
柱・間柱の間、垂木の間、根太の間など、構造材の間に断熱材を充填する断熱工法。→図（温ガp141図９）

[[guide_ip_sotobaridannetsu]]
==== 外張断熱：
軸組、構造体の外側に断熱層を設ける断熱工法。→図（温ガp141図９）

[[guide_ip_heiyoudannetsu]]
==== 併用断熱：
部位により、充填断熱と外張断熱を使い分けること。

[[guide_ip_tenjodannetsu]]
==== 天井断熱：
最上階や下屋の天井上に断熱材を敷設する断熱工法。
→図（図47天井断熱-1、図48天井断熱-2、図49天井垂木工法による天井断熱、図50ブローイング工法による天井断熱）

[[guide_ip_yanedannetsu]]
==== 屋根断熱：
屋根構造のなかに断熱材を仕込む断熱工法。垂木や登り梁の間に断熱材を仕込む充填断熱と、野地板の上に敷きこむ外張断熱がある。→図（温ガp185図52屋根断熱）

[[guide_ip_ketauedannetsu]]
==== 桁上断熱：
桁や小屋梁の上端を揃えて合板を張り、その上に断熱材を施工して外張断熱とする断熱手法。断熱材の種類や厚さが限定されない、容易に施工ができる、間仕切り壁の気流止め対策が不要になるなどの長所がある。→図（温ガp184図51桁上断熱）

[[guide_ip_yukadannetsu]]
==== 床断熱：
床下に断熱材を敷設する断熱工法。根太や大引の間に断熱材を敷きこむ。→図（温ガp179図41ボード状断熱材の施工状況）

[[guide_ip_yukadannetsujuko]]
==== 床断熱住戸：
玄関等及び浴室を除いた部分の外皮を床とする住戸

[[guide_ip_kisodannetsu]]
==== 基礎断熱：
基礎の立ちあがり部分に断熱をする工法。基礎の内側に断熱材を張る場合と外側に張る場合がある。→図（温ガp180図42基礎断熱、図43基礎断熱（浴室土間部分））

[[guide_ip_kisodannetsujuko]]
==== 基礎断熱住戸：
浴室を除いた部分の外皮を土間床等の外周部の基礎とする住戸

[[guide_ip_domayukadannetsu]]
==== 土間床断熱：
土間下に透水性の小さな断熱材を施工する。施工の容易さや確実さを考えると、玄関土間などには土間床断熱が適しています。→図（温ガp181図44土間床断熱）

[[guide_ip_ondosakeisu]]
==== 温度差係数：
部位の接する隣接空間等との温度差を考慮し、当該部位の熱損失量を補正する係数（省エネ基準解説書p.205）

[[guide_ip_kankinetsusonshitsu]]
==== 換気熱損失：
換気による熱損失

[[guide_ip_yukakankisystem]]
==== 床下換気システム：
床下空間を経由して外気を室内へ導入する換気方式を採用したシステム

[[guide_ip_bourosochi]]
==== 防露措置：
壁体内の結露を防止する対策。室内から壁体内への水蒸気の浸入を防止し（防湿）、躯体内の水分を速やかに排出する（排湿）ように壁を構成する。

[[guide_ip_toushituteikouhi]]
==== 透湿抵抗比：
室内側と外気側の湿気の通りにくさの比率。透湿抵抗比が大きいほど、室内側は湿気を通しにくく、外気側は湿気を排出しやすいことになり、壁体内に結露が発生しにくい状態になる。透湿抵抗比＝室内側の透湿抵抗の合計÷外気側の透湿抵抗の合計

[[guide_ip_kiryudome]]
==== 気流止め：
断熱効果を十分に発揮させるため、床下からの冷たい空気が壁内（外壁・間仕切り壁）へ流れ込むこと、壁から小屋裏へ温まった空気が流れ出ることを止めるために、壁の上下端部に空気の出入りを止める措置をすること。

[[guide_ip_boushitsufilm]]
==== 防湿フィルム：
壁内に室内から湿気が入り込まないように断熱材と壁材の間に施工するフィルム。断熱材と一体化されている製品もある。施工時に隙間が生じない、穴をあけないように注意する。→図（温ガp179図39）


