

== 日射遮蔽手法 Aパート：
WEB プログラムのメニュー情報（要素技術を考えるにあたり大切な情報と、評価に必要な最低限の情報）


=== 日射遮蔽手法とは
日射遮蔽手法とは、夏期・中間期において建物内に入る日射を上手に遮蔽することにより、太陽熱の過度な流入を抑制し、冷房エネルギー消費量の削減と快適性の向上を実現することを目的とした技術です。

=== 目標レベル
  ☆☆☆☆☆　暖房設備の目標レベルと参考仕様を記載
  ☆☆☆
  ☆
  
=== 冷房期の日射熱取得率
・冷房期平均日射熱取得率(ηAC)　4.3 (有効数値：小数点以下1桁) 

NOTE: どういった入力にするか検討が必要。省エネ基準に合わせるのがプログラム上は楽か？？ μ値を記入するか検討
 
=== 設計上の配慮事項・暮らし方の留意点

==== 日射熱取得の部位別比率
　窓ガラスのような透明部位と、屋根・外壁などの不透明部位とを比べると、透明部位からの日射量がはるかに大きくなります。したがって透明部位の窓については、十分な日射遮蔽対策が必要となります。また不透明部位については、高断熱化をはかることにより日射遮蔽効果が高まります。次いで日射反射率の高い材料を用いるなどの手法を検討します。
 
==== 建物周囲の状況による日射熱取得の変化
　水平面に対する各方位の垂直面の日射量の比率が方位係数ですが、その方位係数が隣棟間隔や周囲の状況によって変化します。壁面の高さに対する隣棟との間隔の比率が小さくなるにしたがって、方位係数は減少します。省エネ基準では日射遮蔽性能の評価は、隣棟が無いことを前提としていますが、隣棟を加味した冷房エネルギー消費量の推定を行いたいときには図5と表7を参考として、μCを補正することも一法です。
 
NOTE: 新築版P197図5、表７
  
==== 照返し防止や庭木による日射遮蔽措置
　地表面やベランダ、バルコニー、近隣建物の屋根や壁などからの照返しによる開口部を通しての室内への受熱も考えられます。こうした室内への受熱をできるだけ軽減できるように、照返し面の材料・仕上げについて検討が必要です。また、庭のある家では、建物周囲の樹木も日射遮蔽に有効な役割を果たすことが期待できます。落葉樹は、夏期に日射を遮り、冬期には落葉して日差しをそれほど遮らないので、室内の快適性向上に役立てることができます（図29）。
 
NOTE: 新築版P208図29
