== 日射遮蔽手法 Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野

== 自立循環型住宅オプションについての解説

本プログラムの計算結果は設計実務に活用することを目的としています。

したがって、省エネ基準とは異なり、以下の内容を考慮したηAH値、ηAC値を計算に用いることが可能です。

・開口部の付属部材を、夏と冬で変更することができます。

・開口部の付属部材に、レースカーテンや内付けブラインドを評価することができます。

TIP: 温暖地版P195 表4　ガラス種別および付属部材に応じた日射熱取得率の表を掲載

・ηAC値の計算時に、建物周囲の隣棟の影響を加味した方位係数を使って評価することができます。

TIP: 温暖地版P197 図5 冷房期における方位係数と隣棟間隔による変化、表7 立地条件による下記日射熱取得率の補正比率の例

・ηAH値の計算時に、立地条件毎の隣棟遮蔽係数を使って補正することができます。

TIP: 温暖地版P90 表3 隣棟遮蔽係数


== 省エネルギー手法の解説（入力ガイド説明文）

=== 日射熱取得率
NOTE: 『当該住戸の外皮面積を用いて外皮性能を評価する』または『当該住戸の外皮面積を用いず外皮性能を評価する（別途計算）』の場合に表示される選択肢

[[shuho_nissha_ss_eta_d_window_1]]
==== 暖房期平均日射熱取得率(ηAH)

・暖房期平均日射熱取得率とは、屋根、外壁、窓等の外皮の各部位から入射する日射量を外皮面積の合計で除した値で、下式によって求められます。
*

・計算した結果は、小数点第2位以下を切り下げて、小数点以下1桁で入力してください。

[[shuho_nissha_sw_eta_d_window_1]]
==== 冷房期平均日射熱取得率(ηAC)

・冷房期平均日射熱取得率とは、屋根、外壁、窓等の外皮の各部位から入射する日射量を外皮面積の合計で除した値で、下式によって求められます。
*

・計算した結果は、小数点第2位以下を切り上げて、小数点以下1桁で入力してください。


=== 日射熱取得率

NOTE: 『当該住戸の外皮面積を用いず外皮性能を評価する（ここで計算）』の場合に表示される選択肢

[[shuho_nissha_ss_eta_d_window_2]]
==== 冷房期の窓の垂直面日射熱取得率

・窓の垂直面日射熱取得率は、枠とガラスの種類の組み合わせにより、表1または表2に示す値から選択することができます。あるいは、ガラスの垂直面日射熱取得率を用いて計算した値とすることもできます。

・なお、複数の異なる仕様を有する場合は、窓の垂直面日射熱取得率が最も大きい部位の垂直面日射熱取得率の値を入力します。その際に、窓の面積（当該窓が2以上の場合においては、その合計の面積）が単位住戸の床面積に0.04を乗じた数値以下となるものは計算対象から除くことができます。

===== 【表1もしくは表2より読み取る】

====== 表1 枠が木製建具又は樹脂製建具の場合

NOTE: 技術情報の表を挿入

====== 表2 枠が木と金属の複合材料製建具、樹脂と金属の複合材料製建具、金属製熱遮断構造建具又は金属製建具の場合

NOTE: 技術情報の表を挿入

===== 【ガラスの垂直面日射熱取得率を用いて計算する】

窓の垂直面日射熱取得率は、枠とガラスの種類の組み合わせにより、以下のように計算します。

====== 1) 枠が木製建具又は樹脂製建具の場合

η_(d,i)＝η_(g,i)×0.72

====== 2) 枠が木と金属の複合材料製建具、樹脂と金属の複合材料製建具、金属製熱遮断構造建具又は金属製建具の場合

η_(d,i)＝η_(g,i)×0.8

====== 3) 枠が木製建具又は樹脂製建具の場合

η_(d,i)＝η_(g,i)

η_(d,i)：開口部𝑖の垂直面日射熱取得率

η_(g,i)：開口部𝑖のガラスの垂直面日射熱取得率

ガラスの垂直面日射熱取得率η_(g,i)は、以下のいずれかで確認した値を入力してください。

1) JIS R3106（板ガラス類の透過率・反射率・放射率・日射熱取得率の試験方法）に定める値

2) ISO 9050（Glass in building ‒ Determination of light transmittance, solar direct　transmittance, total solar energy transmittance, ultraviolet transmittance and related glazing factors）に定める値

3) 下表に示す値

表3 ガラスの垂直面日射熱取得率 

NOTE: 技術情報の表を挿入

注1）「単板ガラス 2 枚を組み合わせたもの」は、中間部にブラインドが設置されたものを含むものとする。

注2）日射取得型、日射遮蔽型の区分については、JIS R3106 の夏期の日射熱取得率の値が 0.5 以上のものを「日射取得型」、0.5 未満のものを「日射遮蔽型」と判断する。なお、ガラスの層数、ガラスの厚み、中空層厚み、Low-E ガラスの配置、中空層の気体の種類等によらず、次に示す基本構成の Low-E 複層ガラスの日射熱取得率の値で日射区分を判断してもよい。（以下、同じ。）

基本構成の Low-E 複層ガラス：[室内側]Low-E ガラス(3mm)＋空気層(12mm)＋透明フロート板ガラス(3mm)[室外側]


==== 暖房期の窓の垂直面日射熱取得率

※冷房期と同じ

[[shuho_nissha_window_f_input]]
==== 窓の取得日射熱補正係数の指定方法
地域、ガラスの種別並びに暖房期又は冷房期の別ごとに、ひさし等のオーバーハング型の日除けの効果を、ガラスの入射角特性及び地表面反射を考慮して定めた係数のことです。規定値を用いない場合は、計算した値を入力することができます。

[[shuho_nissha_window_ss_f]]
==== 冷房期の窓の取得日射熱補正係数

・窓の取得日射補正係数の計算方法は、こちら（技術情報リンク）を参照してください。

・冷房期の窓の取得日射熱補正係数は、当該住戸で最も大きい値を用いるか、又は、ガラス区分を1、開口部の上部に日除けが設置されていない場合として、地域の区分に応じて、南西、北西、北東及び南東の値をこちら（技術情報リンク）により計算した値としてください。

[[shuho_nissha_window_sw_f]]
==== 暖房期の窓の取得日射熱補正係数

・窓の取得日射補正係数の計算方法は、こちら（技術情報リンク）を参照してください。

・暖房期の窓の取得日射熱補正係数は、当該住戸で最も小さい値を用いるか、または、ガラス区分を7、l1＝0、l2＝1/0.3 として、地域の区分に応じて、南西、北西、北東及び南東の値をこちら（技術情報リンク）により計算した値としてください。
