
== 暖房設備計画マニュアル Aパート：
WEB プログラムのメニュー情報（要素技術を考えるにあたり大切な情報と、評価に必要な最低限の情報）


=== 暖房設備計画とは
住宅におけるエネルギー消費量を用途別にみると、暖房が占める割合は大きく、暖房設備を計画する上で省エネルギーのための技術を適用する意味は大きいといえます。 省エネルギーを踏まえた暖房設備の計画・設計を行うためには、適切な設備機器の選定や配置のための基本的な知識が必要となります。 暖冷房方式の選択と目標レベルの設定は、住宅の断熱仕様、世帯構成や在宅時間、住まい手が求める快適性の水準とコストとのバランス等に配慮して行います。 暖冷房方式の選択の前に、建物外皮の断熱性能 、世帯構成及び在宅時間 、熱交換換気の採用の有無 を事前に確認してください。

=== 目標レベル
  ☆☆☆☆☆　暖房設備の目標レベルと参考仕様を記載
  ☆☆☆
  ☆
  
  モデル住宅による標準的なエネルギー消費量　10.9GJ
TIP: 概要の地域選択を反映させて切り替えられると良い。

=== 暖房方式の選択
 ・住戸全体を暖房する
 ・居室のみを暖房する
 
==== 住戸全体を暖房する場合
NOTE: 選択により切り替え

 暖房設備機器の種類
 ・ダクト式セントラル空調機(ヒートポンプ熱源)
 
 定格能力および定格消費電力の入力
 ・入力しない
 ・定格能力および定格消費電力を入力することにより省エネルギー効果を評価する
 
 風量補正
 ・風量補正なし
 ・風量補正あり
  
 消費電力量補正係数(風量補正なし)
 ・　　　　 [-] (小数点以下2桁)

==== 居室のみを暖房する
NOTE: 選択により切り替え

 主たる居室の暖房設備
 ・ルームエアコンディショナー
 ・FF暖房機
 ・パネルラジエーター
 ・温水床暖房
 ・ファンコンベクター
 ・電気蓄熱暖房機
 ・電気ヒータ床暖房
 ・ルームエアコンディショナー付温水床暖房機
 ・その他の暖房設備機器
 ・暖房設備機器または放熱器を設置しない
 
 省エネルギー対策の有無および種類
 ・特に省エネルギー対策をしない
 ・エネルギー消費効率の区分を入力することにより省エネルギー効果を評価する
 
  その他の居室の暖房設備
 ・ルームエアコンディショナー
 ・FF暖房機
 ・パネルラジエーター
 ・温水床暖房
 ・ファンコンベクター
 ・電気蓄熱暖房機
 ・電気ヒータ床暖房
 ・ルームエアコンディショナー付温水床暖房機
 ・その他の暖房設備機器
 ・暖房設備機器または放熱器を設置しない
 
 省エネルギー対策の有無および種類
 ・特に省エネルギー対策をしない
 ・エネルギー消費効率の区分を入力することにより省エネルギー効果を評価する
 
=== 設計上の配慮事項・暮らし方の留意点

==== 世帯構成および在宅時間
・世帯構成や在宅時間については、例えば単身世帯のように不在がちで在宅時間の短い場合と、在宅勤務や高齢者のいる世帯のように在宅時間の長い場合とで、選択すべき暖冷房方式と運転方法は異なってきます。
・単身世帯のように在宅時間が短い場合であれば、間歇運転で十分といえます。連続運転を採用すると、不在時に無駄になるエネルギー消費が生じます。
・在宅勤務や高齢者を含む世帯のように比較的在宅時間の長い世帯では、室内環境が良くなる連続運転や、住宅全体の温度差が少ない温熱環境のバリアフリー化を目指した住戸連続運転方式を検討するのもよいでしょう。
