== 用語解説（簡易版）

[[guide_hs_houhou]]
==== 暖房方式：
住宅のどの部分を暖房する範囲とするかということ。自立循環型住宅の設計ガイドラインでは、「居室のみを暖房する方式」と「住戸全体を暖房する方式」に分けて考えます。

[[guide_hs_untenhouhou]]
==== 運転方法：
暖房の機器の稼働の仕方。自立循環型住宅の設計ガイドラインでは、「居室間歇運転」と「住戸連続運転」に分けて考えます。

[[guide_hs_kanketsuunten]]
==== 間歇運転：
居室を使用するときだけ暖房機器を稼働する。

[[guide_hs_renzokuunten]]
==== 連続運転：
居室を使用していないときも暖房機器を稼働させる。

[[guide_hs_ldk]]
==== 主たる居室：
リビング、ダイニング、台所など、在室時間の長い居室

[[guide_hs_nldk]]
==== その他居室：
子供室や寝室など、主たる居室以外の在室時間が短い居室。ただし寝室は除く。


[[guide_hs_heatpump]]
==== ヒートポンプ：
コンプレッサーなどで冷媒を圧縮し、集熱部・放熱部での熱移動を行うことで、消費エネルギーより多くの熱を得ることが可能な技術。


[[guide_hs_sennetsukaishugata]]
==== 潜熱回収型：
従来はそのまま捨てていた排気ガス中に含まれる水蒸気分の熱を回収して、熱を得るのに有効利用する高効率の機器。

[[guide_hs_ff]]
==== FF（強制給排気式）暖房：
電動ファンなどで強制的に給気と排気を行う暖房システム。FFはForced Flue(強制通気)の略で、機械換気機能の付いた暖房システムのこと。暖房機の背面から屋外に配管を通して、給排気を行うタイプが一般的。燃焼時に発生する二酸化炭素や窒素酸化物などを自動的に屋外に出し、外からは新鮮な空気を入れるため、室内の空気を汚さない。


[[guide_hs_roomaircon]]
==== ルームエアコンディショナー：
ヒートポンプ技術により、効率よく室内の空気の温度や湿度などを調整する機器。



[[guide_hs_onsuidanbou]]
==== 温水暖房：
熱源機で暖められた温水を循環させ、パネルラジエーター・ファンコンベクター・床暖房などの放熱器により室内を暖める暖房方式。

[[guide_hs_panelradiator]]
==== パネルラジエーター：
ファンなどの動力を使用せずに、フィンに温水を回して部屋を暖めるもの。


[[guide_hs_yukadanbou]]
==== 床暖房：
床を加温することで部屋を暖める暖房方法。

[[guide_hs_central]]
==== ダクト式セントラル空調機：
住宅全体で1台もしくは各階に1台のヒートポンプ熱源から、冷温風をダクトで各居室に運び、換気システムと組み合せて住戸全体の暖冷房・換気を行う空調機。


[[guide_hs_fusetsu]]
==== 敷設率：
暖房室の面積に占める床暖房を敷設した面積の割合。

[[guide_hs_joumenhounetsuristu]]
==== 上面放熱率：
床暖房パネルに使用した熱量に対する居室（上部）に放熱される熱量の割合。

[[guide_hs_kaihougatadanbou]]
==== 開放型暖房機器：
燃料を燃焼させて熱を取り出す時に生じる燃焼ガスを室内に排出する暖房機。燃焼の際に、二酸化窒素や二酸化炭素といった空気を汚す物質が発生するため、多量の換気を必要とする。


[[guide_hs_sainetsujoshitsu]]
==== 再熱除湿：
一度冷却して除湿した空気を再び暖めた後に室内に送る技術。除湿時の不快感を改善したもの。通常の冷房運転よりも多くのエネルギーを要する。


[[guide_hv_houshiki]]
==== 熱交換換器：
排気の際に屋外に捨てられる熱を回収することができ、冬期に暖房エネルギーを抑制することができるシステムのこと。

[[guide_hs_hojotekidanbou]]
==== 補助的暖房器具：
こたつ、電気パネルヒーター、電気ストーブ、電気カーペット、セラミックヒーター、ハロゲンヒータ―など、冬期において主な暖房機以外に使用される補助的なもの。


[[guide_hs_tenjousen]]
==== 天井扇：
天井に取り付けるファン。全般的に体感温度を下げる効果が期待できる。上部に溜りやすい暑い空気を撹拌することで、天井付近の表面温度の上昇が抑制され、居住域の体感温度を下げる効果も期待できる。


[[guide_hs_shitunaikuukiosenbusshitsu]]
==== 室内空気汚染物質：
建材、内装材（接着剤、塗料など）などから放散されるアルデヒド類、揮発性有機化合物。

