== 用語解説（簡易版）

[[guide_hs_houhou]]
==== 暖冷房方式：
住宅のどの部分を暖房する範囲とするかということ。自立循環型住宅の設計ガイドラインでは、「居室のみを暖房する方式」と「住戸全体を暖房する方式」に分けて考えます。

[[guide_hs_untenhouhou]]
==== 運転方法：
暖冷房の機器の稼働の仕方。自立循環型住宅の設計ガイドラインでは、「居室間歇運転」と「住戸連続運転」に分けて考えます。

[[guide_hs_kanketsuunten]]
==== 間歇運転：
居室を使用するときだけ暖冷房機器を稼働する。例えば、「居室間歇暖房」「居室間歇冷房」のように運転方法を考えます。

[[guide_hs_renzokuunten]]
==== 連続運転：
居室を使用していないときも暖冷房機器を稼働させる。「住戸連続暖房」「住戸連続冷房」のように運転方法を考えます。

[[guide_hs_ldk]]
==== 主たる居室：
リビング、ダイニング、台所など、在室時間の長い居室

[[guide_hs_nldk]]
==== その他の居室：
子供室や寝室など、主たる居室以外の在室時間が短い居室。ただし寝室は除く。

[[guide_hs_hikyoshitu]]
==== 非居室：
廊下や浴室、便所などの居室以外の空間

[[guide_hs_netsugen]]
==== 熱源、熱源機：
暖房のための熱を供給するところ、または供給する機器。

[[guide_hs_heatpump]]
==== ヒートポンプ：
コンプレッサーなどで冷媒を圧縮し、集熱部・放熱部での熱移動を行うことで、消費エネルギーより多くの熱を得ることが可能な技術。

TIP: 図（温ガp297図10）

[[guide_hs_sennetsukaishugata]]
==== 潜熱回収型：
従来はそのまま捨てていた排気ガス中に含まれる水蒸気分の熱を回収して、熱を得るのに有効利用する高効率の機器。

TIP: （温ガp.282）

[[guide_hs_ff]]
==== FF（強制給排気式）暖房：
電動ファンなどで強制的に給気と排気を行う暖房システム。FFはForced Flue(強制通気)の略で、機械換気機能の付いた暖房システムのこと。暖房機の背面から屋外に配管を通して、給排気を行うタイプが一般的。燃焼時に発生する二酸化炭素や窒素酸化物などを自動的に屋外に出し、外からは新鮮な空気を入れるため、室内の空気を汚さない。

TIP: 図（東京ガスHPより）　 

[[guide_hs_roomaircon]]
==== ルームエアコンディショナー：
ヒートポンプ技術により、効率よく室内の空気の温度や湿度などを調整する機器。

TIP: (温ガp.238)

[[guide_hs_aircon_dualcompressor]]
==== 容量可変型コンプレッサー：
一回転あたりのシリンダ容積（押のけ量）を変化させて単位時間あたりの冷媒循環量を制御する機械式容量制御を採用したコンプレッサー

[[guide_hs_onsuidanbou]]
==== 温水暖房：
熱源機で暖められた温水を循環させ、パネルラジエーター・ファンコンベクター・床暖房などの放熱器により室内を暖める暖房方式。

TIP: 図（温ガp.237図５）

[[guide_hs_panelradiator]]
==== パネルラジエーター：
ファンなどの動力を使用せずに、フィンに温水を回して部屋を暖めるもの（温ガp.236）。

TIP: 図（温ガp.237図６）

[[guide_hs_yukadanbou]]
==== 床暖房：
床を加温することで部屋を暖める暖房方法。

[[guide_hs_central]]
==== ダクト式セントラル空調機：
住宅全体で1台もしくは各階に1台のヒートポンプ熱源から、冷温風をダクトで各居室に運び、換気システムと組み合せて住戸全体の暖冷房・換気を行う空調機。

TIP: 図(温ガp.238図７)

[[guide_hs_dc_hosei]]
==== 風量補正：

[[guide_hs_cpl_value]]
==== 消費電力量補正係数：
ダクト等の圧力損失によって増加する消費電力を考慮するための係数で、風量補正の有無やダクトの断熱被覆の状況を考慮して計算する。

[[guide_hs_roomaircononsuiyukadanbou]]
==== ルームエアコンディショナー付温水床暖房機：

[[guide_hs_hounetsuki]]
==== 放熱器：
放射熱で部屋を暖めるための機器。主に、床暖房、パネルラジエーター方式、ファンコンベクター方式がある。

TIP: 図（温ガp.237図６）

[[guide_hs_hounetsumenseki]]
==== 放熱面積：
放熱部の面積

[[guide_hs_fusetsu]]
==== 敷設率：
暖房室の面積に占める床暖房を敷設した面積の割合。

[[guide_hs_joumenhounetsuristu]]
==== 上面放熱率：
床暖房パネルに使用した熱量に対する居室（上部）に放熱される熱量の割合。

[[guide_hs_kaihougatadanbou]]
==== 開放型暖房機器：
燃料を燃焼させて熱を取り出す時に生じる燃焼ガスを室内に排出する暖房機。燃焼の際に、二酸化窒素や二酸化炭素といった空気を汚す物質が発生するため、多量の換気を必要とする。

TIP: (温ガp.242)

[[guide_hs_mippeigatadanbou]]
==== 密閉型暖房機器：
燃料を燃焼させ熱を取り出す時に生じる燃焼ガスを室内に排出せずに屋外に直接排出する暖房機。

TIP: (温ガp.242)

[[guide_hs_sainetsujoshitsu]]
==== 再熱除湿：
一度冷却して除湿した空気を再び暖めた後に室内に送る技術。除湿時の不快感を改善したもの。通常の冷房運転よりも多くのエネルギーを要する。

TIP: (温ガp.246)

[[guide_hs_teikakukouritsu_e]]
==== 定格効率（エネルギー消費効率）: 
Coefficient Of Performance(成長係数)の略。一定の条件で計測された暖冷房能力を消費電力で除した値。値が大きいほど、より少ない消費電力で暖冷房できることを示す。

[[guide_hs_toprunner]]
==== トップランナー基準：
自動車の燃焼基準や電気・ガス石油機器（家電・OA機器など）の省エネルギー基準を、各々の機器においてエネルギー消費効率が現在商品化されている製品のうち、最も優れている機器の性能レベルのこと。
APF（AnnualPerformanceFactor通年エネルギー消費効率）：東京に建つある建物をエアコンで暖冷房した時に、通年でどれだけのエネルギー効率となるかを表した指標。

TIP: （温ガp.249）

[[guide_hv_houshiki]]
==== 熱交換換気：
排気の際に屋外に捨てられる熱を回収することができ、冬期に暖房エネルギーを抑制することができるシステムのこと。

TIP: （改p264）

[[guide_hs_hojotekidanbou]]
==== 補助的暖房器具：
こたつ、電気パネルヒーター、電気ストーブ、電気カーペット、セラミックヒーター、ハロゲンヒータ―など、冬期において主な暖房機以外に使用される補助的なもの。

TIP: （温ガp.256）

[[guide_hs_tenjousen]]
==== 天井扇：
天井に取り付けるファン。全般的に体感温度を下げる効果が期待できる。上部に溜りやすい暑い空気を撹拌することで、天井付近の表面温度の上昇が抑制され、居住域の体感温度を下げる効果も期待できる。

TIP: 図(温ガp.247図9)

[[guide_hs_fukushanetsu]]
==== 輻射熱：
高温の物体から低温の物体に、直接電磁波の形で伝わる(輻射)熱のこと。太陽の自然な暖かさや、薪ストーブの熱なども輻射熱。

[[guide_hs_hattei]]
==== 発停：
スイッチを入れたり、切ったりすること。

[[guide_hs_heikinhoushaondo]]
==== 平均放射温度（MeanRadiantTemperature）：
周囲の全方向から受ける熱放射を平均化した温度表示のこと。

[[guide_hs_sayouondo]]
==== OT（作用温度:OperativeTemperature）：
効果温度ともいう。人体に対する温熱環境を評価する指標のひとつ。

[[guide_hs_taikanondo]]
==== 体感温度：
人が感じる温度

TIP: （温ガp.134）

[[guide_hs_shitunaikuukiosenbusshitsu]]
==== 室内空気汚染物質：
建材、内装材（接着剤、塗料など）などから放散されるアルデヒド類、揮発性有機化合物。

[[guide_hs_colddraft]]
==== コールド・ドラフト：
冬期に、外気に接する外壁や窓ガラス面で冷却された空気が起こす下降気流。発生した冷たい気流は床表面を移動し、足下の冷気不快感に繋がる。

TIP: 図(YKKAPより https://www.ykkap.co.jp/apw/apw330/detail/index.html)
 
[[guide_hs_netsudendoritsu]]
==== 熱伝導率：
熱の伝わりやすさを表す値。裏表の温度差1度の場合に厚み1mの材料1㎡あたりに伝わる熱量。値が小さいほど伝わる熱が少なく、断熱性能が高いことになる。

TIP: （旭化成の断熱材HPより）

[[guide_hs_netsuteiko]]
==== 熱抵抗：
材料の熱の伝えにくさの指標（単位：㎡・K/W)。値が大きいほど熱が伝わりにくく、断熱性能が高いことになる。熱抵抗値R（単位：㎡K/W）=断熱材の厚み（単位：ｍ）÷熱伝導率λ（単位：W/m・K）

[[guide_hs_soutousukimamenseki]]
==== 相当隙間面積(C値)：
自然給気口、レンジフードなどの換気に関わる開口を除いた住宅全体の隙間面積を、延べ面積で除した値。単位は㎠/㎡。

TIP: (温ガp.62)
