
== 暖房設備計画マニュアル Aパート：
WEB プログラムのメニュー情報（要素技術を考えるにあたり大切な情報と、評価に必要な最低限の情報）


=== 暖房設備計画とは
住宅におけるエネルギー消費量を用途別にみると、暖房が占める割合は大きく、暖房設備を計画する上で省エネルギーのための技術を適用する意味は大きいといえます。 省エネルギーを踏まえた暖房設備の計画・設計を行うためには、適切な設備機器の選定や配置のための基本的な知識が必要となります。 暖冷房方式の選択と目標レベルの設定は、住宅の断熱仕様、世帯構成や在宅時間、住まい手が求める快適性の水準とコストとのバランス等に配慮して行います。 暖冷房方式の選択の前に、建物外皮の断熱性能 、世帯構成及び在宅時間 、熱交換換気の採用の有無 を事前に確認してください。

=== 目標レベル
  ☆☆☆☆☆　暖房設備の目標レベルと参考仕様を記載
  ☆☆☆
  ☆
  
  モデル住宅による標準的なエネルギー消費量　10.9GJ
TIP: 概要の地域選択を反映させて切り替えられると良い。

=== 暖房方式の選択
 ・住戸全体を暖房する
 ・居室のみを暖房する
 
==== 住戸全体を暖房する場合
NOTE: 選択により切り替え（住戸全体を暖房する場合）

 暖房設備機器の種類
 ・ダクト式セントラル空調機(ヒートポンプ熱源)
 
 定格能力および定格消費電力の入力
 ・入力しない
 ・定格能力および定格消費電力を入力することにより省エネルギー効果を評価する
 
 風量補正
 ・風量補正なし
 ・風量補正あり
  
 消費電力量補正係数(風量補正なし)
 ・　　　　 [-] (小数点以下2桁)

==== 居室のみを暖房する
NOTE: 選択により切り替え（居室のみを暖房する場合）

 主たる居室の暖房設備
・ルームエアコンディショナー
       省エネルギー対策の有無および種類
          ・特に省エネルギー対策をしない
          ・エネルギー消費効率の区分を入力することにより省エネルギー効果を評価する
                エネルギー消費効率の区分
                      ・区分(い)
                      ・区分(ろ)
                      ・区分(は)
                容量可変コンプレッサー
                      ・搭載しない
                      ・搭載する
 ・FF暖房機
        省エネルギー対策の有無および種類
          ・特に省エネルギー対策をしない
          ・エネルギー消費効率を入力することにより省エネルギー効果を評価する
                ・　　　[%] (小数点以下1桁)
 ・パネルラジエーター
          温水暖房機の種類
              ・温水暖房専用型
              ・給湯・温水暖房一体型を使用する
              ・コージェネレーションを使用する
              ・その他の温水暖房機
              ・温水暖房機を設置しない
 ・温水床暖房
          敷設率
              ・　　 [%] (小数点以下1桁)
          仮想床の床面積を除いた敷設率を入力する
              ・入力しない
              ・入力する
                    仮想床の床面積を除いた敷設率
                          ・　　 [%] (小数点以下1桁)
          床の断熱(上面放熱率)
              ・　　 [%] (小数点以下1桁)
          温水暖房機の種類
              ・温水暖房専用型
              ・給湯・温水暖房一体型を使用する
              ・コージェネレーションを使用する
              ・その他の温水暖房機
              ・温水暖房機を設置しない
 ・ファンコンベクター
           温水暖房機の種類
              ・温水暖房専用型
              ・給湯・温水暖房一体型を使用する
              ・コージェネレーションを使用する
              ・その他の温水暖房機
              ・温水暖房機を設置しない
 ・電気蓄熱暖房機
 ・電気ヒータ床暖房
           敷設率
              ・　　 [%] (小数点以下1桁)
          仮想床の床面積を除いた敷設率を入力する
              ・入力しない
              ・入力する
                    仮想床の床面積を除いた敷設率
                          ・　　 [%] (小数点以下1桁)
          床の断熱(上面放熱率)
              ・　　 [%] (小数点以下1桁)
 ・ルームエアコンディショナー付温水床暖房機
           敷設率
              ・　　 [%] (小数点以下1桁)
          仮想床の床面積を除いた敷設率を入力する
              ・入力しない
              ・入力する
                    仮想床の床面積を除いた敷設率
                          ・　　 [%] (小数点以下1桁)
          床の断熱(上面放熱率)
              ・　　 [%] (小数点以下1桁)
          断熱配管の採用
              ・採用する
              ・採用しない
 ・その他の暖房設備機器
           その他の設備機器の名称
              ・　　　　（直接入力）
 ・暖房設備機器または放熱器を設置しない
 
 省エネルギー対策の有無および種類
 ・特に省エネルギー対策をしない
 ・エネルギー消費効率の区分を入力することにより省エネルギー効果を評価する
 
 NOTE: 選択により切り替え（エアコンの選択時）
 
  その他の居室の暖房設備
 ・ルームエアコンディショナー
       省エネルギー対策の有無および種類
          ・特に省エネルギー対策をしない
          ・エネルギー消費効率の区分を入力することにより省エネルギー効果を評価する
                エネルギー消費効率の区分
                      ・区分(い)
                      ・区分(ろ)
                      ・区分(は)
                容量可変コンプレッサー
                      ・搭載しない
                      ・搭載する
 ・FF暖房機
        省エネルギー対策の有無および種類
          ・特に省エネルギー対策をしない
          ・エネルギー消費効率を入力することにより省エネルギー効果を評価する
                ・　　　[%] (小数点以下1桁)
 ・パネルラジエーター
          温水暖房機の種類
              ・温水暖房専用型
              ・給湯・温水暖房一体型を使用する
              ・コージェネレーションを使用する
              ・その他の温水暖房機
              ・温水暖房機を設置しない
 ・温水床暖房
          敷設率
              ・　　 [%] (小数点以下1桁)
          仮想床の床面積を除いた敷設率を入力する
              ・入力しない
              ・入力する
                    仮想床の床面積を除いた敷設率
                          ・　　 [%] (小数点以下1桁)
          床の断熱(上面放熱率)
              ・　　 [%] (小数点以下1桁)
          温水暖房機の種類
              ・温水暖房専用型
              ・給湯・温水暖房一体型を使用する
              ・コージェネレーションを使用する
              ・その他の温水暖房機
              ・温水暖房機を設置しない
 ・ファンコンベクター
           温水暖房機の種類
              ・温水暖房専用型
              ・給湯・温水暖房一体型を使用する
              ・コージェネレーションを使用する
              ・その他の温水暖房機
              ・温水暖房機を設置しない
 ・電気蓄熱暖房機
 ・電気ヒータ床暖房
           敷設率
              ・　　 [%] (小数点以下1桁)
          仮想床の床面積を除いた敷設率を入力する
              ・入力しない
              ・入力する
                    仮想床の床面積を除いた敷設率
                          ・　　 [%] (小数点以下1桁)
          床の断熱(上面放熱率)
              ・　　 [%] (小数点以下1桁)
 ・ルームエアコンディショナー付温水床暖房機
           敷設率
              ・　　 [%] (小数点以下1桁)
          仮想床の床面積を除いた敷設率を入力する
              ・入力しない
              ・入力する
                    仮想床の床面積を除いた敷設率
                          ・　　 [%] (小数点以下1桁)
          床の断熱(上面放熱率)
              ・　　 [%] (小数点以下1桁)
          断熱配管の採用
              ・採用する
              ・採用しない
 ・その他の暖房設備機器
           その他の設備機器の名称
              ・　　　　（直接入力）
 ・暖房設備機器または放熱器を設置しない
 
=== 設計上の配慮事項・暮らし方の留意点

==== 運転方法の違いによる室内環境
　間歇運転は連続運転よりエネルギー消費は少ないですが、室内環境は連続運転の方が良好に保たれます。例えば、連続運転は室内表面温度が空気温度に近いので、空気温度が同じでも放射熱の影響で快適に感じます。また、間歇運転は起床時や帰宅時には部屋が冷えているので、運転開始しから適切な室温に達するまでに多少の時間がかかります。（新築版P235図）

==== 世帯構成や在宅時間に合わせた運転方法の選択
　単身世帯のように不在がちで在宅時間の短い場合や、在宅勤務や高齢者のいる世帯のように在宅時間の長い場合など、世帯構成や在宅時間に合わせて運転方法を検討します。在宅時間が短い場合であれば、不在時に無駄なエネルギーが少ない間歇運転で十分といえます。また、比較的在宅時間の長い世帯では、室内環境が良くなる連続運転や、住宅全体の温度差が少ない温熱環境のバリアフリー化を目指した住戸連続運転方式を検討するのもよいでしょう。

==== 空間の特徴に適した方式の採用
　天井高が高い場合や吹き抜けがある場合は、室内の上下温度差が大きくなる傾向にあるため、足元を暖める床暖房が適しています。また、天井扇など空気を撹拌する機器を用いて室内の上下温度差を解消させるのもよい方法といえます。
 
==== 補助的暖房器具の併用や開放型暖房機器の仕様の制限
　こたつやホットカーペットなどの補助的暖房器具は、効率が悪いため併用を止めるか、併用するにしても最小限の使用にとどめるべきです。
　また、灯油ストーブやガスファンヒーターなどの開放型暖房機器は、二酸化窒素や二酸化炭素といった室内空気汚染物質を発生したり、燃焼に伴う多量の水蒸気は、結露の主因となり、内装の汚れやカビの発生を助長する傾向があるため、開放型暖房機器を用いることは避けるべきです。
