
== 暖房設備計画マニュアル Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野


== 省エネルギー手法の説明
NOTE: 「エネルギー消費性能計算プログラム(住宅版) 」のヘルプボタンの説明を簡潔にし、図表を追加する

NOTE: 自立テキストの補足情報（省エネになる方法）を追記する

=== 暖房方式と運転方法の分類
・暖房方式には、居室のみを暖房する方式と、住戸全体を暖房する方式があります。 

・居室のみを暖房する方式とは、暖房期間中、居室のみを暖房する一方で、廊下や脱衣室等の非居室は暖房しない方式をいいます。 さらに、それぞれの居室の運転方法として、連続運転と間歇運転に分けられます。

・住戸全体を暖冷房する方式とは、暖冷房期間中、居室すべてと、クローゼット、倉庫、食品庫などを除く廊下などの非居室を暖冷房する方式です。 住戸全体を暖房・冷房するには時間がかかるため、通常、連続運転が採用されます。

NOTE: 表 暖冷房方式と運転方法 

・間歇運転とは、住まい手が在室している時間のみ暖房を行う方法です。 この場合、就寝時に暖房を運転する場合としない場合があります。 連続運転とは、住まい手が部屋に居ない時間も含めて24 時間暖房を運転したままにしておく方法です。 ただし、旅行などの長期外出時には停止します。 また、就寝時のみ停止するか、温度設定を変えるなどして暖房を弱めるなどの措置が行われる場合もあります。

・主たる居室とは、リビング・ダイニング・台所などの比較的在室時間の長い居室を指し、その他の居室とは、子供室や寝室など主たる居室以外の就寝時を除き比較的在室時間が短い居室を指します。 また、非居室とは、廊下や浴室・便所等の居室以外の空間を指します。

・暖房設備機器を設置しない場合は「設置しない」を選択してください。「設置しない」を選択した場合は、地域の区分や建て方に応じて予め定められた暖房方式及び暖房設備機器により暖房するものと想定した一次エネルギー消費量が計算されます。

=== 住戸全体を暖房する

・「住戸全体を暖房する」は、ヒートポンプを熱源とし、機外静圧を持った状態で運転されることを想定して、ダクト等により住戸全体を空調するように計画された家庭用のダクト式セントラル空調（循環用送風機が室内機と一体となっているもの）で暖房する場合のみ選択することができます。なお、クローゼットや納戸等の一部の空間を除いた非居室を含め、住宅全体を1以上のダクト式セントラル空調で暖房する場合も評価の対象となります。

・ヒートポンプ式熱源でないダクト式セントラル空調機を評価する場合は、以下の手順で条件を入力して計算して下さい。

　①「暖房方式の選択」で「居室のみを暖房する」を選択して下さい。
 
　②「主たる居室」および「その他の居室」に、「暖房設備機器または放熱器を設置しない」または「その他の暖房設備機器」を選択して下さい。
 
　③「その他の暖房設備機器」を選択した場合は、「主たる居室」および「その他の居室」に同じ機器名称を入力して下さい。
 
・複数のヒートポンプ式熱源によるダクト式セントラル空調機を設置する場合は、以下の方法で能力や係数を求め、評価してください。

　A：「定格暖房能力」は、設置する複数の機器の定格暖房能力を合計した値としてください。
 
　B：「定格暖房消費電力」は、①で合計した定格暖房能力を設置する機器のうち最も低い定格暖房エネルギー消費効率で除した値としてください。
 
　C：「暖房時におけるダクト等圧力損失による消費電力量補正係数」は、設置する複数の機器の暖房時におけるダクト等圧力損失による消費電力量補正係数のうち、最も大きい値としてください。

=== ダクト式セントラル空調機（ヒートポンプ熱源）

==== 定格能力および定格消費電力を入力することにより省エネルギー効果を評価する
・定格能力および定格消費電力は、JIS B 8615-2（エアコンディショナ−第2部：ダクト接続形エアコンディショナと空気対空気ヒートポンプ　定格性能及び運転性能試験）に基づいて測定された値を入力してください。
・機器のカタログ等を参考に、「定格暖房能力」「定格暖房消費電力」を入力してください。

==== 風量補正
・「風量補正なし」は、圧力損失によって送風機の出力が変わらない機器の場合に選択してください。

・「風量補正あり」は、圧力損失によって送風機の出力が変わる機器の場合に選択してください。

==== 消費電力量補正係数
・消費電力量補正係数とは、ダクト等の圧力損失によって増加する消費電力を考慮するための係数で、風量補正の有無やダクトの断熱被覆の状況を考慮して計算します。
・消費電力量補正係数は、風量補正の有無により下式により計算してください。なお、各式のbHの係数は、ダクトの断熱被覆の状況により判断してください。

NOTE: 計算方法へのリンク


=== 居室のみを暖房する
・「居室のみを暖房する」を選択した場合は、「主たる居室」と「その他の居室」ごとに、設置する暖房設備機器等を選択して下さい。

・暖房設備機器等を設置しない場合は、「設置しない」を選択して下さい。それぞれの居室で選択した暖房設備機器等より、機器に応じた運転方法に対応した暖房負荷に基づき、暖房設備の一次エネルギー消費量を計算します。

・設備機器等を設置しない場合、あるいは複数の設備機器等を設置する場合の運転方法の決定方法については、こちら（※）を参照して下さい。
※http://house.app.lowenergy.jp/img/help/07_hs_houhou.pdf

・「パネルラジエーター」、「温水床暖房」、「ファンコンベクター」を選択した場合は、画面下にある「温水式暖房を設置する場合」における入力項目も入力して下さい。

=== ルームエアコンディショナー

==== 評価方法の選択（ルームエアコンディショナー）
・「評価しない」は、省エネルギー対策に取り組んでいない場合、あるいは特に省エネルギー対策を評価しない場合に選択して下さい。ルームエアコンディショナーを居住者が設置予定などで、設置される機器が特定されない場合もこちらを選択して下さい。
・「エネルギー消費効率の区分を入力する」は、エネルギー消費効率の区分によって省エネルギー効果を評価する場合に選択して下さい。

==== エネルギー消費効率の区分（ルームエアコンディショナー）
・エネルギー消費効率の区分とは、冷房定格能力の大きさごとに定格冷房エネルギー消費効率の程度に応じて3段階に区分したものです。
・暖房運転についても「冷房定格能力」と「定格冷房エネルギー消費効率」に基づき、エネルギー消費効率の区分を設定していることに注意して下さい。

==== 容量可変型コンプレッサーの搭載
・容量可変型コンプレッサーとは、一回転あたりのシリンダ容積（押のけ量）を変化させて単位時間あたりの冷媒循環量を制御する機械式容量制御を採用したコンプレッサーのことです。
・複数のルームエアコンディショナーが設置される場合で、容量可変型コンプレッサーの搭載の有無が異なる場合は、「搭載しない」を選択して下さい。

NOTE: エネルギー消費効率の区分の表を掲載

=== FF暖房機

==== 評価方法の選択（FF暖房機）
・「評価しない」は、省エネルギー対策に取り組んでいない場合、あるいは特に省エネルギー対策を評価しない場合に選択して下さい。設置される機器のエネルギー消費効率が不明な場合もこちらを選択して下さい。
・「エネルギー消費効率を入力する」は、定格能力におけるエネルギー消費効率（熱効率）を入力することによって省エネルギー効果を評価する場合に選択して下さい。

==== 定格能力におけるエネルギー消費効率（FF暖房機）
・機器のカタログ等を参考に、「エネルギー消費効率（％）」（熱効率（％））を入力してください。
 TIP:  FF式ガス暖房機は JIS S 2122、FF 式石油暖房機は JIS S 3031 に定められた測定方法

=== パネルラジエーター
入力欄なし

=== 温水床暖房

==== 敷設率
・床暖房を設置する居室における床暖房パネルの敷設面積を当該居室の床面積で除した値を入力します。「その他の居室」で床暖房を設置する場合も、床暖房を設置する居室における床暖房パネルの敷設面積を当該居室の床面積で除した値を入力して下さい。
敷設率の計算方法は、こちら（10）を参照して下さい。
・「主たる居室」の 2 ヶ所以上に温水床暖房が設置される場合、「その他の居室」の 2 ヶ所以上に温水床暖房が設置される場合、又は複数の「その他の居室」においてそれぞれに温水床暖房が設置される場合、「主たる居室」及び「その他の居室」それぞれにおいて敷設率を計算した値のうち、最も小さい値を入力して下さい。ただし、当面の間、従前の方法（当該住戸の敷設面積の合計を、温水床暖房を設置する居室の床面積の合計で除した値を、敷設率とする方法）も用いることができます。
・温水床暖房と電気ヒーター式床暖房又はルームエアコンディショナー付床暖房が「主たる居室」及び「その他の居室」に併設される場合は、温水床暖房の床暖房パネルのみによる敷設率を求めて下さい。

==== 仮想床の床面積を除いた敷設率を入力する
・「主たる居室」に吹抜けを有する場合に、仮想床の床面積を除いた敷設率を入力することができます。ただし、温水床暖房が設置される「主たる居室」が2か所以上ある場合は、その全ての主たる居室に吹抜けがある場合に限ります。「主たる居室」それぞれにおいて敷設率を計算した値のうち、最も小さい値を入力して下さい。
・「吹抜け」とは、複数の階をまたいで床を設けず上下方向に連続した空間を指します。「仮想床」とは、天井の高さが4.2以上の場合に、高さ2.1mの部分に仮想床があるものとみなし、以下同様に、天井高さが 2.1m 増えるごとに仮想床があるとします。

==== 仮想床の床面積を除いた敷設率
・仮想床の床面積を除いた敷設率は以下の算出式により求めてください。 （床暖房パネルの敷設面積）／（主たる居室における仮想床の床面積を除いた床面積）×100
値は、小数点第二位を切り捨て、小数点第二位までの値を入力してください。

==== 上面放熱率
・床下側を断熱することにより、床下側への熱損失を減らすことができます。上面放熱率とは、床暖房パネルに投入した熱量に対する居室（上部）に放熱される熱量の割合を示し、ここでは、居室（上部）と床下等（下部）の温度は等しいと想定しています。

TIP: 上面放熱率の計算方法は、「エネルギー消費性能の算定方法」の「4 暖冷房設備　7 温水暖房付録L 温水床暖房」を参照して下さい。

・「主たる居室」において2か所以上に温水床暖房を設置する場合、又は「その他の居室」において 2か所以上に温水床暖房を設置する場合の上面放熱率は、それぞれの箇所で計算した値のうち、最も小さい値を入力して下さい。

　①「主たる居室」の2ヶ所以上に温水床暖房が設置される場合

　②「その他の居室」の2ヶ所以上に温水床暖房が設置される場合

　③ 複数の「その他の居室」においてそれぞれに温水床暖房が設置される場合
 
TIP: 上面放熱率の計算には「床暖房の上面放熱率の簡易計算プログラム」(別ウィンドウに表示されます)が利用できます。



=== ファンコンベクター
入力欄なし


=== 電気ヒーター床暖房
「温水床暖房」と同じ

=== 電気蓄熱暖房機
入力欄なし

=== ルームエアコンディショナー付温水床暖房機
「敷設率」～「床の断熱(上面放熱率)」は「温水床暖房」と同じ

==== 断熱配管の採用
・温水暖房機から放熱器までの温水配管における熱損失の状況を評価します。温水配管の周囲を断熱材で被覆している場合は、「採用する」を選択して下さい。
・断熱材の種類・厚さは問いませんが、温水暖房機から放熱器まで全部が断熱されていることが要件となります。なお、サヤ管等にできる空気層については、断熱材とは認めません。
・上記以外の場合は「採用しない」を選択して下さい。

=== 温水式暖房を設置する場合（「パネルラジエーター」、「温水床暖房」、「ファンコンベクター」を選択した場合）

==== 温水暖房機の種類

・温水暖房の放熱器のみに接続される「温水暖房専用型」と、台所、洗面、浴室などへの給湯用熱源を兼ねる「給湯・温水暖房一体型」、温水の供給に加えて発電も行う「コージェネレーション」などがあります。

===== 温水専用型　

・各居室に設置された放熱器と循環配管で1対1又は1対多で接続する温水暖房用の熱源機です。

===== 給湯・温水暖房一体型を使用する

・温水暖房用の放熱器への温水供給と、台所、洗面、浴室で使用する湯を供給する熱源機が一体型のものを使用する場合に選択して下さい。

・「給湯・温水暖房一体型」を使用する場合は、「給湯タブ」で詳細な仕様を入力します。

===== コージェネレーションを使用する

・温水暖房用の放熱器への温水供給を、コージェネレーションシステムによって行う場合に選択して下さい。


== 自立循環独自の手法
今後評価が可能になる？

==== 適切な機器容量の選択
