== 用語解説
==== 冷房設備計画:

==== 冷房方式：
住宅のどの部分を冷房する範囲とするかということ。自立循環型住宅の設計ガイドラインでは、「居室のみを冷房する方式」と「住戸全体を冷房する方式」に分けて考えます。

==== 運転方法：
暖冷房の機器の稼働の仕方。自立循環型住宅の設計ガイドラインでは、「居室間歇運転」と「住戸連続運転」に分けて考えます。

==== 間歇運転：
居室を使用するときだけ暖冷房機器を稼働する。例えば、「居室間歇暖房」「居室間歇冷房」のように運転方法を考えます。

==== 連続運転： 
居室を使用していないときも暖冷房機器を稼働させる。「住戸連続暖房」「住戸連続冷房」のように運転方法を考えます。

==== 潜熱回収型：
従来はそのまま捨てていた排気ガス中に含まれる水蒸気分の熱（潜熱）を回収して（温ガp.297）、有効利用することで高効率化を可能にした（温ガp.282）。

==== ルームエアコンディショナー：
ヒートポンプ技術により熱を作る効率が良い機器(温ガp.238)。空調設備の一つ。室内の空気の温度や湿度などを調整する機械。(参照元：https://ja.wikipedia.org/wiki/%E3%82%A8%E3%82%A2%E3%83%BB%E3%82%B3%E3%83%B3%E3%83%87%E3%82%A3%E3%82%B7%E3%83%A7%E3%83%8A%E3%83%BC)

====ダクト式セントラル空調機：
住宅全体で1台もしくは各階に1台のヒートポンプ熱源を用い、冷温風をダクトで各居室に運び、換気システムと組み合せて住戸全体の暖冷房・換気を行う集中暖冷房方式(温ガp.238)。→ 図(温ガp.238図７)

==== 再熱除湿：
一度冷却して除湿した空気を再び暖めた後に室内に送る技術。除湿時の不快感を改善したもの。ただし、通常の冷房運転よりも多くのエネルギーを要する(温ガp.246)。

==== 定格効率（エネルギー消費効率）:
定格条件において計測された暖冷房能力をその時の消費電力で除した値。カタログ上では、COPと表現される。この値が大きいほど、より少ない消費電力で暖冷房できるため、省エネであるといえる。定格条件とは、エアコンの省エネ性能を測定するために、JISであらかじめ定められた試験条件のこと（温ガp.240）。
COPは、Coefficient Of Performance(成長係数)の略。電力1kWを使ってどれだけの効果を得られるかという指標(参照：新電力ネットhttps://pps-net.org/glossary/21672)

==== トップランナー基準：
製造事業者などに、省エネ型の製品を製造するよう基準値を設けクリアするように課した「エネルギーの使用の合理化に関する法律（省エネ法）」の中の、機械器具にかかわる措置のこと。民生・運輸部門のエネルギー消費の増加を抑制するため、機械器具の製造段階でエネルギー消費効率を向上させることを掲げて「トップランナー基準」方式が採用された。トップランナーとは、自動車の燃焼基準や電気・ガス石油機器（家電・OA機器など）の省エネルギー基準を、各々の機器においてエネルギー消費効率が現在商品化されている製品のうち、最も優れている機器の性能以上にする、という考え方（参照元：(一財)省エネルギーセンターhttps://www.eccj.or.jp/machinery/toprunner/index.html）

==== APF（AnnualPerformanceFactor通年エネルギー消費効率）：
東京に建つある建物をエアコンで暖冷房した時に通年でどれだけのエネルギー効率となるかを表した指標。定格条件以外の効率、例えば外気温度や暖冷房負荷の大小によって効率が変化するなどの影響を組み込んだ指標であり、より実態に近い効率となるよう意図されている（温ガp.249）

==== 熱交換換気：
熱交換素子の狭い部分を空気が通過するため、一般の換気設備より換気動力が増加します。しかし排気の際に屋外に捨てられる熱を回収することができるため、主として暖房エネルギーを抑制することができます（改p264）。

==== 天井扇：
扇風機より広い範囲で気流を感じることができ、全般的に体感温度を下げる効果が期待できる。吹き抜けなど天井までの高さがある空間では、上部に溜りやすい暑い空気を撹拌することで、天井付近の表面温度上昇が抑制され、居住域の体感温度を下げる効果も期待できる（温ガp.247）。→図(温ガp.247図9)

==== 輻射熱：
高温の固体表面から低温の固体表面に、その間の空気その他の気体の存在に関係なく、 直接電磁波の形で伝わる伝わり方を輻射といい、その熱を輻射熱という。太陽の自然な暖かさや、薪ストーブの熱なども輻射熱によるもの。(参照元：Weblio辞書工学実用空調関連用語（提供：ダイキン工業）https://www.weblio.jp/cat/engineering/kchyg)

==== 発停：
スイッチを入れたり、切ったりすること。

==== 平均放射温度（MeanRadiantTemperature）：
周囲の全方向から受ける熱放射を平均化した温度表示のこと。MRTの値が気温よりも高いと、周囲から受ける放射熱による暑さを感じ、逆に気温よりも低いと涼しさを感じる。（参照元：環境省https://www.env.go.jp/air/report/h16-13/02.pdf#search=%27%E5%B9%B3%E5%9D%87%E6%94%BE%E5%B0%84%E6%B8%A9%E5%BA%A6%27

==== OT（作用温度:OperativeTemperature）：
効果温度ともいう。人体に対する温熱環境を評価する指標のひとつ。気温が同じ室内であっても、壁面温度と周囲気流の状態により体感温度は違うことを加味し、周囲壁面との放射熱伝達と周囲気流との対流熱伝達と同じ量の熱交換を行なう様な均一温度の閉鎖空間での仮想気温のこと。(参照元：Wilipedia　https://ja.wikipedia.org/wiki/%E4%BD%9C%E7%94%A8%E6%B8%A9%E5%BA%A6)
乾球温度（一般の寒暖計で計った温度）、気流速度、 平均放射温度、および有効体表面積などから算出する生理的温度指標です。(参照元：ヒガノ㈱https://www.higano.co.jp/faq/ot/)

==== 体感温度：
人が感じる温度（温ガp.134）

==== 室内空気汚染物質：
建材、内装材（接着剤、塗料など）などから放散されるアルデヒド類、揮発性有機化合物。家具、防虫剤、芳香剤、冷房器具、タバコの煙などにも含まれる。(参照元：㈱環境技術研究所http://www.etlabo.co.jp/hyouka.html)

==== 熱伝導率：
材料の熱の伝えやすさの指標。材料の両側の表面温度差が１℃のとき、単位面積、単位厚さの材料を単位時間に伝わる熱量（単位：W/m・K）.(温ガp.142)

==== 熱抵抗：
材料の熱の伝えにくさの指標（単位：㎡・K/W)。材料厚さを熱伝導率で除した値。断熱材など均質な材料に対して用いる（温ガp.142）。

== 項目の追加（中野:Cパートより）

=== 主たる居室
・リビング・ダイニング・台所などの比較的在室時間の長い居室を指します。

=== その他の居室
・子供室や寝室など主たる居室以外の就寝時を除き比較的在室時間が短い居室を指します。 

=== 非居室
・非居室とは、廊下や浴室・便所等の居室以外の空間を指します。
