== 冷房設備計画マニュアル Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野


== 省エネルギー手法の説明
NOTE: 「エネルギー消費性能計算プログラム(住宅版) 」のヘルプボタンの説明を簡潔にし、図表を追加する

NOTE: 自立テキストの補足情報（省エネになる方法）を追記する

[[shuho_cs_houhou]]
==== 冷房方式と運転方法の分類
・冷房方式には、居室のみを冷房する方式と、住戸全体を冷房する方式があります。 

・居室のみを冷房する方式とは、冷房期間中、居室のみを暖房する一方で、廊下や脱衣室等の非居室は冷房しない方式をいいます。 さらに、それぞれの居室の運転方法として、連続運転と間歇運転に分けられます。

・住戸全体を暖冷房する方式とは、暖冷房期間中、居室すべてと、クローゼット、倉庫、食品庫などを除く廊下などの非居室を暖冷房する方式です。 住戸全体を暖房・冷房するには時間がかかるため、通常、連続運転が採用されます。

NOTE: 表 暖冷房方式と運転方法 

・間歇運転とは、住まい手が在室している時間のみ冷房を行う方法です。 この場合、就寝時に暖房を運転する場合としない場合があります。 連続運転とは、住まい手が部屋に居ない時間も含めて24 時間冷房を運転したままにしておく方法です。 ただし、旅行などの長期外出時には停止します。 また、就寝時のみ停止するか、温度設定を変えるなどして暖房を弱めるなどの措置が行われる場合もあります。

・主たる居室とは、リビング・ダイニング・台所などの比較的在室時間の長い居室を指し、その他の居室とは、子供室や寝室など主たる居室以外の就寝時を除き比較的在室時間が短い居室を指します。 また、非居室とは、廊下や浴室・便所等の居室以外の空間を指します。

・冷房設備機器を設置しない場合は「設置しない」を選択してください。「設置しない」を選択した場合は、地域の区分や建て方に応じて予め定められた暖房方式及び暖房設備機器により暖房するものと想定した一次エネルギー消費量が計算されます。

==== 住戸全体を冷房する

・「住戸全体を冷房する」は、ヒートポンプを熱源とし、機外静圧を持った状態で運転されることを想定して、ダクト等により住戸全体を空調するように計画された家庭用のダクト式セントラル空調（循環用送風機が室内機と一体となっているもの）で冷房する場合のみ選択することができます。なお、クローゼットや納戸等の一部の空間を除いた非居室を含め、住宅全体を1以上のダクト式セントラル空調で冷房する場合も評価の対象となります。

・ヒートポンプ式熱源でないダクト式セントラル空調機を評価する場合は、以下の手順で条件を入力して計算して下さい。

　①「冷房方式の選択」で「居室のみを冷房する」を選択します。

　②「主たる居室」および「その他の居室」に、「冷房設備機器を設置しない」または「その他の冷房設備機器」を選択します。

　③「その他の冷房設備機器」を選択した場合は、「主たる居室」および「その他の居室」に同じ機器名称を入力します。

・複数のダクト式セントラル空調機を設置する場合は、以下の方法で能力や係数を求め、評価してください。

　A：「定格冷房能力」は、設置する複数の機器の定格冷房能力を合計した値としてください。

　B：「定格冷房消費電力」は、①で合計した定格冷房能力を設置する機器のうち最も低い定格冷房エネルギー消費効率で除した値としてください。

　C：「冷房時におけるダクト等圧力損失による消費電力量補正係数」は、設置する複数の機器の冷房時におけるダクト等圧力損失による消費電力量補正係数のうち、最も大きい値としてください。
 
==== 居室のみを冷房する
・「居室のみを冷房する」を選択した場合は、「主たる居室」と「その他の居室」ごとに、設置する冷房設備機器等を選択します。冷房設備機器等を設置しない場合は、「冷房設備機器を設置しない」を選択して下さい。
 
 
===ダクト式セントラル空調機(ヒートポンプ式熱源)
 NOTE:  暖房と同じ
 
== ルームエアコンディショナー
 NOTE:  暖房と同じ
 
 
== 自立循環独自の手法
今後評価が可能になる？

== 扇風機・天井扇の利用

 
