== 用語解説（簡易版）

[[guide_cs_houhou]]
==== 冷房方式：
冷房する範囲により、「居室のみを冷房する方式」と「住戸全体を冷房する方式」二つの方式に分けられている。

[[guide_cs_untenhouhou]]
==== 運転方法：
冷房の機器の稼働の仕方。「居室間歇運転」と「住戸連続運転」。

[[guide_cs_kanketsuunten]]
==== 間歇運転：
必要なときだけ冷房機器を稼働する運転方法。

[[guide_cs_renzokuunten]]
==== 連続運転： 
居室を使用していないときも冷房機器を稼働させる運転方法。

[[guide_cs_ldk]]
==== 主たる居室：
リビング、ダイニング、台所など、在室時間の長い居室

[[guide_cs_nldk]]
==== その他の居室：
子供室や寝室など、主たる居室以外の在室時間が短い居室。ただし寝室は除く。

[[guide_cs_roomaircon]]
==== ルームエアコンディショナー：
ヒートポンプ技術により、効率よく室内の空気の温度や湿度などを調整する機器


[[guide_cs_central]]
==== ダクト式セントラル空調機：
住宅全体で1台もしくは各階に1台のヒートポンプ熱源から、冷温風をダクトで各居室に運び、換気システムと組み合せて住戸全体の暖冷房・換気を行う空調機。


[[guide_cs_sainetsu]]
==== 再熱除湿：
一度冷却して除湿した空気を再び暖めた後に室内に送る技術。除湿時の不快感を改善したもの。通常の冷房運転よりも多くのエネルギーを要する。


[[guide_cs_teikakukouritsu_e]]
==== エネルギー消費効率: 
Coefficient Of Performance(成長係数)の略。一定の条件で計測された暖冷房能力を消費電力で除した値。値が大きいほど、より少ない消費電力で暖冷房できることを示す。


[[guide_cs_annualperformancefactor]]
====エネルギー消費効率：
東京に建つある建物をエアコンで暖冷房した時に、通年でどれだけのエネルギー効率となるかを表した指標。


[[guide_hv_houshiki]]
==== 熱交換換器：
排気の際に屋外に捨てられる熱を回収することができ、冬期に暖房エネルギーを抑制することができるシステムのこと。


[[guide_cs_tenjousen]]
==== 天井扇：
天井に取り付けるファン。全般的に体感温度を下げる効果が期待できる。上部に溜りやすい暑い空気を撹拌することで、天井付近の表面温度の上昇が抑制され、居住域の体感温度を下げる効果も期待できる。


