== 用語解説（簡易版）

[[guide_cs_houhou]]
==== 暖冷房方式：
冷房する範囲により、「居室のみを冷房する方式」と「住戸全体を冷房する方式」二つの方式に分けられている。

[[guide_cs_untenhouhou]]
==== 運転方法：
暖冷房の機器の稼働の仕方。「居室間歇運転」と「住戸連続運転」。

[[guide_cs_kanketsuunten]]
==== 間歇運転：
必要なときだけ暖冷房機器を稼働する運転方法。

[[guide_cs_renzokuunten]]
==== 連続運転： 
居室を使用していないときも暖冷房機器を稼働させる運転方法。

[[guide_cs_ldk]]
==== 主たる居室：
リビング、ダイニング、台所など、在室時間の長い居室

[[guide_cs_nldk]]
==== その他の居室：
子供室や寝室など、主たる居室以外の在室時間が短い居室。ただし寝室は除く。

[[guide_cs_hikyoshitu]]
==== 非居室：
廊下や浴室、便所などの居室以外の空間

[[guide_cs_roomaircon]]
==== ルームエアコンディショナー：
ヒートポンプ技術により、効率よく室内の空気の温度や湿度などを調整する機器(温ガp.238)。

[[guide_cs_aircon_dualcompressor]]
==== 容量可変コンプレッサー：
一回転あたりのシリンダ容積（押のけ量）を変化させて単位時間あたりの冷媒循環量を制御する機械式容量制御を採用したコンプレッサー

[[guide_cs_central]]
==== ダクト式セントラル空調機：
住宅全体で1台もしくは各階に1台のヒートポンプ熱源から、冷温風をダクトで各居室に運び、換気システムと組み合せて住戸全体の暖冷房・換気を行う空調機。→ 図(温ガp.238図７)

== 風量補正：

[[guide_cs_sainetsu]]
==== 再熱除湿：
一度冷却して除湿した空気を再び暖めた後に室内に送る技術。除湿時の不快感を改善したもの。通常の冷房運転よりも多くのエネルギーを要する。(温ガp.246)

[[guide_cs_teikakukouritsu_e]]
==== 定格効率（エネルギー消費効率COP）: 
Coefficient Of Performance(成長係数)の略。一定の条件で計測された暖冷房能力を消費電力で除した値。値が大きいほど、より少ない消費電力で暖冷房できることを示す。

[[guide_cs_toprunner]]
==== トップランナー基準：
自動車の燃焼基準や電気・ガス石油機器（家電・OA機器など）の省エネルギー基準を、各々の機器においてエネルギー消費効率が現在商品化されている製品のうち、最も優れている機器の性能レベルのこと。

[[guide_cs_annualperformancefactor]]
==== APF（AnnualPerformanceFactor通年エネルギー消費効率）：
東京に建つある建物をエアコンで暖冷房した時に、通年でどれだけのエネルギー効率となるかを表した指標。（温ガp.249）

[[guide_hv_houshiki]]
==== 熱交換換気：
排気の際に屋外に捨てられる熱を回収することができ、冬期に暖房エネルギーを抑制することができるシステムのこと。（改p264）

[[guide_cs_tenjousen]]
==== 天井扇：
天井に取り付けるファン。全般的に体感温度を下げる効果が期待できる。上部に溜りやすい暑い空気を撹拌することで、天井付近の表面温度の上昇が抑制され、居住域の体感温度を下げる効果も期待できる。→図(温ガp.247図9)

[[guide_cs_hattei]]
==== 発停：
スイッチを入れたり、切ったりすること。

[[guide_cs_heikinhoushaondo]]
==== 平均放射温度（MeanRadiantTemperature）：
周囲の全方向から受ける熱放射を平均化した温度表示のこと。

[[guide_cs_sayouondo]]
==== OT（作用温度:OperativeTemperature）：
効果温度ともいう。人体に対する温熱環境を評価する指標のひとつ。

[[guide_cs_taikanondo]]
==== 体感温度：
人が感じる温度（温ガp.134）

[[guide_cs_shitunaikuukiosenbusshitsu]]
==== 室内空気汚染物質：
建材、内装材（接着剤、塗料など）などから放散されるアルデヒド類、揮発性有機化合物。 (参照元：㈱環境技術研究所http://www.etlabo.co.jp/hyouka.html)

[[guide_cs_netsudendoritsu]]
==== 熱伝導率：
熱の伝わりやすさを表す値。裏表の温度差1度の場合に厚み1mの材料1㎡あたりに伝わる熱量。値が小さいほど伝わる熱が少なく、断熱性能が高いことになる。（旭化成の断熱材HPより）

[[guide_cs_netsuteiko]]
==== 熱抵抗：（Ｒ値）：
材料の熱の伝えにくさの指標（単位：㎡・K/W)。値が大きいほど熱が伝わりにくく、断熱性能が高いことになる。熱抵抗値R（単位：㎡K/W）=断熱材の厚み（単位：ｍ）÷熱伝導率λ（単位：W/m・K）

[[guide_cs_soutousukimamenseki]]
==== 相当隙間面積(C値)：
自然給気口、レンジフードなどの換気に関わる開口を除いた住宅全体の隙間面積を、延べ面積で除した値。単位は㎠/㎡。(温ガp.62)


