
== 冷房設備計画マニュアル Aパート：
WEB プログラムのメニュー情報（要素技術を考えるにあたり大切な情報と、評価に必要な最低限の情報）


=== 冷房設備計画とは
省エネルギーを踏まえた冷房設備の計画・設計を行うためには、適切な設備機器の選定や配置のための基本的な知識が必要となります。冷房方式の選択と目標レベルの設定は、住宅の断熱仕様、日射熱制御手法、世帯構成や在宅時間、住まい手が求める快適性の水準とコストとのバランス等に配慮して行います。
冷房方式の選択の前に、建物外皮の断熱性能、世帯構成及び在宅時間 、を事前に確認してください。
なお、本評価方法では、熱交換換気を採用することによる冷房（顕熱または潜熱）負荷の低減は見込んでおりません。

=== 目標レベル
  ☆☆☆☆☆　暖房設備の目標レベルと参考仕様を記載
  ☆☆☆
  ☆
  
  モデル住宅による標準的なエネルギー消費量　10.9GJ
TIP: 概要の地域選択を反映させて切り替えられると良い。

=== 冷房方式の選択
 ・住戸全体を暖房する
 ・居室のみを暖房する
 
==== 住戸全体を冷房する場合
NOTE: 選択により切り替え

 暖房設備機器の種類
 ・ダクト式セントラル空調機(ヒートポンプ熱源)
 
 定格能力および定格消費電力の入力
 ・入力しない
 ・定格能力および定格消費電力を入力することにより省エネルギー効果を評価する
 
 風量補正
 ・風量補正なし
 ・風量補正あり
  
 消費電力量補正係数(風量補正なし)
 ・　　　　 [-] (小数点以下2桁)

==== 居室のみを冷房する
NOTE: 選択により切り替え

 主たる居室の暖房設備
 ・ルームエアコンディショナー
 ・その他の冷房設備機器
 ・冷房設備機器を設置しない
 
 省エネルギー対策の有無および種類
 ・特に省エネルギー対策をしない
 ・エネルギー消費効率の区分を入力することにより省エネルギー効果を評価する
 
  その他の居室の冷房設備
 ・ルームエアコンディショナー
 ・その他の冷房設備機器
 ・冷房設備機器を設置しない
 
 省エネルギー対策の有無および種類
 ・特に省エネルギー対策をしない
 ・エネルギー消費効率の区分を入力することにより省エネルギー効果を評価する
 
=== 設計上の配慮事項・暮らし方の留意点

==== 光色の検討
　光色も重要な光の要素で、白色光を用いると活動的な雰囲気になり、暖色光を用いると落ち着いた雰囲気になりますので、昼間に多く使用する居室は白色光主体、夜間の使用が多い寝室は暖色光主体というように室の用途によって使い分けると効果的です。
