== 用語解説（簡易版）

[[guide_vn_kanki]]
==== 換気：
室内の汚れた空気を排出し、新鮮な外気と入れ替えること。

TIP: （改p270）

[[guide_vn_hitsuyoukankiryou]]
==== 必要換気量：
室内の空気をきれいな状態に保つために、1時間に外気と何回入れ替わることができる量で換算される。室によって必要な換気量が定められている。

[[guide_vn_sekkeifuuryou]]
==== 設計(換気)風量：
有効換気量のこと。設計している建物全体の換気システムによる「有効換気量」を合計したもの。必要換気量を上回るように換気システム、ファンの選定を行います。

[[guide_vn_zentaikanki]]
==== 全般換気：
住宅全体を換気すること。居室と隣接する換気経路上の空間を２４時間換気できるように計画する。

TIP: （改p270）

[[guide_vn_kyokushokanki]]
==== 局所換気：
台所、便所、浴室などを使用時のみ換気すること。燃焼排ガス、臭気、水蒸気などの室内の空気を汚す発生源を局所的に換気すること。

[[guide_vn_shizenkanki]]
==== 自然換気：
換気口により電力を使用せずに換気すること。風力や内外温度差に起因する浮力により換気量が変動しやすい。

[[guide_vn_kikaikanki]]
==== 機械換気：
機械力を使って、給気と排気の両方、またはどちらかに換気ファンなどを用いて換気すること。安定した換気量の確保が可能。組み合わせにより、第一種～第三種の3種類の方式に大別される。

TIP: （改p270図２）

[[guide_vn_ondosakanki]]
==== 温度差換気：
温度差による煙突効果（暖かい空気が上昇する力）による自然換気のこと。

NOTE: 図（温ガp56図９(自然風の高窓)）

[[guide_vn_ductkankisystem]]
==== ダクト式換気システム：
ダクトを用いることで計画した場所への給気又は計画した場所からの排気を行うこと。

NOTE: 図（温ガp262図１）

[[guide_vn_kabetsukekankisystem]]
==== 壁付け式換気システム：
居室や水廻り等の各所(壁面)に換気扇を設け、外気から直接排気、給気を行うこと。

NOTE: 図（温ガp264図２）

[[guide_vn_hybridkanki]]
==== ハイブリッド換気：
室内外の温度差がある時期には、煙突現象を利用した自然換気を行い、十分な室内外温度差がない時期には、機械換気装置を稼働させる換気計画のこと。

NOTE: 図（温ガp273図4）

[[guide_vn_duct1]]
==== ダクト式第一種換気：
給気と排気を機械で集中的に管理し、ダクト配管で各部屋まで給排気を行う。

[[guide_vn_duct2]]
==== ダクト式第二種換気：
機械を使って給気し、ダクト配管で各部屋へ新鮮な空気を送りこむ。室内が正圧になり、壁の排気口から自然排気する。

[[guide_vn_duct3]]
==== ダクト式第三種換気：
各部屋に配管されたダクトから機械を使って排気する。室内が負圧になり、壁の給気口から自然給気する。

[[guide_vn_kabetsuke1]]
==== 壁付け式第一種換気：
壁に取り付けられた換気設備により、給気と排気を行う。

[[guide_vn_kabetsuke2]]
==== 壁付け式第二種換気：
壁に取り付けられた換気設備で給気し、壁の排気口から自然排気する。

[[guide_vn_kabetsuke3]]
==== 壁付け式第三種換気：
壁に取り付けられた換気設備で排気し、壁の給気口から自然給気する。

[[guide_vn_atsuryokusonshitsu]]
==== 圧力損失：
流体が機械装置などを通過する際のエネルギー損失のこと。摩擦損失とも呼ばれる。抵抗が大きいとその分だけエネルギーを消費することになる。

[[guide_vn_koukouritsufan]]
==== 高効率ファン：
エネルギー効率の高いファン

TIP: （改p279）

[[guide_hv_houshiki]]
==== 熱交換換気：
排気の際に屋外に捨てられる熱を回収することができ、冬期に暖房エネルギーを抑制することができるシステムのこと。

TIP: （改p264）

[[guide_vn_ondokoukanritsu]]
==== 温度交換率：
熱交換型換気設備において、給気温度と外気温度の差が還気温度と外気温度の差にどれだけ近いかを表す指標

[[guide_vn_hishohidenryoku]]
==== 比消費電力：
換気設備のエネルギー効率を判断する指標。値の小さいほうが省エネルギー性能が高い。比消費電力（W(㎥/h)）＝消費電力÷風量

[[guide_vn_tanmatsubuzai]]
==== 端末部材：
屋外から外気の取り入れ口、屋外へ室内空気の排出口に取り付ける部材。省エネルギーのためには、圧力損失の小さいものを選定することが重要。

NOTE: 図（温ガp276表）

[[guide_vn_kimitsuseinou]]
==== 気密性能：
建物の隙間を図る住宅の性能的な目安。専用の測定器で計測し、相当隙間面積C値という指標で表される(改p73)。C値が大きいと建物の隙間から入ってくる外気が大きく、出ていく空気も大きい。

[[guide_vn_kankikeiro]]
==== 換気経路：
給気から排気に至る空気の流れのこと。

== 交流モーター(ACモーター)：

[[guide_vn_dc]]
==== 直流モーター（DCモーター）：
同じ風量を得るのに、入力電力が小さくてすむ省エネルギー型。

TIP: (温暖地改p267)

[[guide_vn_propellerfan]]
==== プロペラファン：
家庭で一般に使われている「換気扇」のこと。外壁などに直接取り付ける。

NOTE: 図（温ガp275図５）

[[guide_vn_siroccofan]]
==== シロッコファン：
水車と同じ原理で、羽根車には幅の狭い前向きの羽根が多数ついているタイプ。ダクト接続用のファンや台所レンジのファンなど多用途に用いられている。

NOTE: 図

[[guide_vn_turbofan]]
==== ターボファン：
シロッコファンと羽根の形態は似ていますが、幅広の後ろ向きの羽根がついているタイプ。

NOTE: 図（温ガp275図５）

[[guide_vn_doujikyuuhaikigata]]
==== 同時給排気型：
排気に見合った給気をレンジフードに送り込んで、換気システム全体の空気の流れを妨げないようにする仕組み

TIP: （suumo住宅用語大辞典）

[[guide_vn_kimitsushutter]]
==== 気密シャッター：
換気停止時の隙間風対策として使用される。ただし開放している時間は電力を消費している。

NOTE: 図（温ガp278図９）

TIP: (改p277)

[[guide_vn_fukuryugata]]
==== 輻流型：
給気された空気を壁面に沿って放射状に拡散させる形状のもの

NOTE: 図(温p278、図10)

[[guide_vn_yuukoukankiryouritsu]]
==== 有効換気量率：
第一種換気設備において、給気量に対して有効な換気量の比率のこと。

TIP: （改正省エネガイドライン第５章）



