== 用語解説（簡易版）

[[guide_vn_kanki]]
==== 換気：
室内の汚れた空気を排出し、新鮮な外気と入れ替えること。


[[guide_vn_zentaikanki]]
==== 全般換気：
住宅全体を換気すること。居室と隣接する換気経路上の空間を２４時間換気できるように計画する。



[[guide_vn_kyokushokanki]]
==== 局所換気：
台所、便所、浴室などを使用時のみ換気すること。燃焼排ガス、臭気、水蒸気などの室内の空気を汚す発生源を局所的に換気すること。


[[guide_vn_kikaikanki]]
==== 機械換気：
機械力を使って、給気と排気の両方、またはどちらかに換気ファンなどを用いて換気すること。安定した換気量の確保が可能。組み合わせにより、第一種～第三種の3種類の方式に大別される。



[[guide_vn_ductkankisystem]]
==== ダクト式換気設備：
ダクトを用いることで計画した場所への給気又は計画した場所からの排気を行うことができる設備。


[[guide_vn_kabetsukekankisystem]]
==== 壁付け式換気設備：
居室や水廻り等の各所(壁面)に換気扇を設け、外気から直接排気、給気を行うことができる設備。



[[guide_vn_duct1]]
==== ダクト式第一種換気：
給気と排気を機械で集中的に管理し、ダクト配管で各部屋まで給排気を行う。

[[guide_vn_duct2]]
==== ダクト式第二種換気：
機械を使って給気し、ダクト配管で各部屋へ新鮮な空気を送りこむ。室内が正圧になり、壁の排気口から自然排気する。

[[guide_vn_duct3]]
==== ダクト式第三種換気：
各部屋に配管されたダクトから機械を使って排気する。室内が負圧になり、壁の給気口から自然給気する。

[[guide_vn_kabetsuke1]]
==== 壁付け式第一種換気：
壁に取り付けられた換気設備により、給気と排気を行う。

[[guide_vn_kabetsuke2]]
==== 壁付け式第二種換気：
壁に取り付けられた換気設備で給気し、壁の排気口から自然排気する。

[[guide_vn_kabetsuke3]]
==== 壁付け式第三種換気：
壁に取り付けられた換気設備で排気し、壁の給気口から自然給気する。


[[guide_hv_houshiki]]
==== 熱交換型換気設備：
排気の際に屋外に捨てられる熱を回収することができ、冬期に暖房エネルギーを抑制することができるシステムのこと。


[[guide_vn_ondokoukanritsu]]
==== 温度交換率：
熱交換型換気設備において、給気温度と外気温度の差が還気温度と外気温度の差にどれだけ近いかを表す指標

[[guide_vn_hishohidenryoku]]
==== 比消費電力：
換気設備のエネルギー効率を判断する指標。値の小さいほうが省エネルギー性能が高い。比消費電力（W(㎥/h)）＝消費電力÷風量

[[guide_vn_tanmatsubuzai]]
==== 屋外端末：
屋外から外気の取り入れ口、屋外へ室内空気の排出口に取り付ける部材。省エネルギーのためには、圧力損失の小さいものを選定することが重要。

[[guide_vn_kimitsuseinou]]
==== 気密性能：
建物の隙間を図る住宅の性能的な目安。専用の測定器で計測し、相当隙間面積C値という指標で表される(改p73)。C値が大きいと建物の隙間から入ってくる外気が大きく、出ていく空気も大きい。


[[guide_vn_fukuryugata]]
==== 輻流型：
給気された空気を壁面に沿って放射状に拡散させる形状のもの


[[guide_vn_yuukoukankiryouritsu]]
==== 有効換気量率：
第一種換気設備において、給気量に対して有効な換気量の比率のこと。




