== 用語解説（簡易版）
==== 換気：
室内の汚れた空気を排出し、新鮮な外気と入れ替えること。（改p270）

==== 必要換気量：
室内の空気をきれいな状態に保つために、1時間に外気と何回入れ替わることができる量で換算される。室によって必要な換気量が定められている。

==== 設計(換気)風量：
有効換気量のこと。設計している建物全体の換気システムによる「有効換気量」を合計したもの。必要換気量を上回るように換気システム、ファンの選定を行います。

==== 全般換気：
住宅全体を換気すること。居室と隣接する換気経路上の空間を２４時間換気できるように計画する。（改p270）

==== 局所換気：
台所、便所、浴室などを使用時のみ換気すること。燃焼排ガス、臭気、水蒸気などの室内の空気を汚す発生源を局所的に換気すること。

==== 自然換気：
換気口により電力を使用せずに換気すること。風力や内外温度差に起因する浮力により換気量が変動しやすい。

==== 機械換気：
機械力を使って、給気と排気の両方、またはどちらかに換気ファンなどを用いて換気すること。安定した換気量の確保が可能。組み合わせにより、第一種～第三種の3種類の方式に大別される（改p270図２）。

==== 温度差換気：
温度差による煙突効果（暖かい空気が上昇する力）による自然換気のこと。→図（温ガp56図９(自然風の高窓)）

==== ダクト式換気システム：
ダクトを用いることで計画した場所への給気又は計画した場所からの排気を行うこと。→図（温ガp262図１）

==== 壁付け式換気システム：
居室や水廻り等の各所(壁面)に換気扇を設け、外気から直接排気、給気を行うこと。→図（温ガp264図２）

==== ハイブリッド換気：
室内外の温度差がある時期には、煙突現象を利用した自然換気を行い、十分な室内外温度差がない時期には、機械換気装置を稼働させる換気計画のこと。→図（温ガp273図4）


==== ダクト式第一種換気：
給気と排気を機械で集中的に管理し、ダクト配管で各部屋まで給排気を行う。

==== ダクト式第二種換気：
機械を使って給気し、ダクト配管で各部屋へ新鮮な空気を送りこむ。室内が正圧になり、壁の排気口から自然排気する。

==== ダクト式第三種換気：
各部屋に配管されたダクトから機械を使って排気する。室内が負圧になり、壁の給気口から自然給気する。

==== 壁付け式第一種換気：
壁に取り付けられた換気設備により、給気と排気を行う。

==== 壁付け式第二種換気：
壁に取り付けられた換気設備で給気し、壁の排気口から自然排気する。

==== 壁付け式第三種換気：
壁に取り付けられた換気設備で排気し、壁の給気口から自然給気する。

==== 圧力損失：
流体が機械装置などを通過する際のエネルギー損失のこと。摩擦損失とも呼ばれる。抵抗が大きいとその分だけエネルギーを消費することになる。

==== 高効率ファン：
エネルギー効率の高いファン（改p279）

==== 熱交換換気：
排気の際に屋外に捨てられる熱を回収することができ、冬期に暖房エネルギーを抑制することができるシステムのこと（改p264）。

==== 温度交換率：
熱交換型換気設備において、給気温度と外気温度の差が還気温度と外気温度の差にどれだけ近いかを表す指標


==== 比消費電力：
換気設備のエネルギー効率を判断する指標。値の小さいほうが省エネルギー性能が高い。比消費電力（W(㎥/h)）＝消費電力÷風量

==== 端末部材：
屋外から外気の取り入れ口、屋外へ室内空気の排出口に取り付ける部材。省エネルギーのためには、圧力損失の小さいものを選定することが重要。→図（温ガp276表）

==== 気密性能：
建物の隙間を図る住宅の性能的な目安。専用の測定器で計測し、相当隙間面積C値という指標で表される(改p73)。C値が大きいと建物の隙間から入ってくる外気が大きく、出ていく空気も大きい。

==== 換気経路：
給気から排気に至る空気の流れのこと。

==== 交流モーター(ACモーター)：

==== 直流モーター（DCモーター）：
同じ風量を得るのに、入力電力が小さくてすむ省エネルギー型(温暖地改p267)。

==== プロペラファン：
家庭で一般に使われている「換気扇」のこと。外壁などに直接取り付ける。→図（温ガp275図５）

==== シロッコファン：
水車と同じ原理で、羽根車には幅の狭い前向きの羽根が多数ついているタイプ。ダクト接続用のファンや台所レンジのファンなど多用途に用いられている。→図

==== ターボファン：
シロッコファンと羽根の形態は似ていますが、幅広の後ろ向きの羽根がついているタイプ。→図（温ガp275図５）

==== 同時給排気型：
排気に見合った給気をレンジフードに送り込んで、換気システム全体の空気の流れを妨げないようにする仕組み（suumo住宅用語大辞典）

==== 気密シャッター：
換気停止時の隙間風対策(改p277)として使用される。ただし開放している時間は電力を消費している。→図（温ガp278図９）

==== 輻流型：
給気された空気を壁面に沿って放射状に拡散させる形状のもの→図(温p278、図10)

==== 有効換気量率：
第一種換気設備において、給気量に対して有効な換気量の比率のこと。（改正省エネガイドライン第５章）


== (修正前：詳細版）
== 用語解説
==== 換気：
室内に空気がある状態で汚れた空気を排出し、新鮮な外気と入れ替える（改p270）

==== 必要換気量：
建築基準法施工令第20条の２第２号による。室内の空気が1時間に何回外気と入れ替わるかで表される（一財ベターリビング）。室によって必要換気量が定められている。

==== 設計(換気)風量：
有効換気量のこと。設計している建物全体の換気システムによる「有効換気量」を合計したもの。必要換気量を上回るように換気システム、ファンの選定を行う。

==== 全般換気：
住宅全体を換気すること（居室及び隣接する換気経路上の空間を２４時間換気する）（改p270）

==== 局所換気：
住宅の一部（台所、便所、浴室など）を使用時のみ換気すること。燃焼排ガス、臭気、水蒸気などの換気対象物質が場所的に集中して発生する場合に用いられる換気手法。（改p270換気ブックレットp2）

==== 自然換気：
換気口により換気する。風力及び内外温度差に起因する浮力により換気量が変動しやすい（改p270）

==== 機械換気：換
気ファンなどにより換気する。機械力により強制的に排気、給気を行うため、安定した換気量の確保が可能（改p270）給気と排気の両方、またはどちらかにファンが必要（ブックレットp3）。組み合わせにより、第一種～第三種の3種類の方式に大別される（ブックレットp3）

==== 温度差換気：
室内温度と外気温度の差が大きい冬期には、温度差による煙突効果（暖かい空気が上昇する力）による自然換気を行い、温度差が小さい夏期・中間期には機械換気設備を利用する換気(換気ブックレットp6)　→図（温ガp56図９(自然風の高窓)）

==== 機械換気：
換気ファンなどにより換気。給気と排気の両方、またはどちらかを機械力により強制的に行う（一財ベータリビング）。その組み合わせにより「第一種換気」「第二種換気」「第三種換気」に分けられる。

==== ダクト式換気システム：
ダクトを用いることで意図した場所への給気又は意図した場所からの排気を行うこと。　→図（温ガp262図１）

==== 壁付け式換気システム：
室や水廻り等にいくつかの換気扇を設けることで換気システムを構成する(温暖地改p264)。→図（温ガp264図２）

==== ハイブリッド換気：
冬期など室内外の温度差がある条件で、煙突現象を利用した自然換気を行い、十分な室内外温度差がない条件では機械換気装置を稼働させるシステム(温暖地改p263)。→図（温ガp273図4）

==== 圧力損失：
流体が機械装置などを通過する際の単位時間単位流量あたりのエネルギー損失である。摩擦損失とも呼ばれる。損失は装置内の抵抗に打ち勝つためにその分だけエネルギーを消費することによる。（wikipedia）。圧力損失が小さいほうが省エネルギーである。

==== 高効率ファン：
エネルギー効率の高いファン（改p279）

==== 熱交換換気：
熱交換素子の狭い部分を空気が通過するため、一般の換気設備より換気動力が増加します。しかし排気の際に屋外に捨てられる熱を回収することができるため、主として暖房エネルギーを抑制することができます（改p264）。

==== 比消費電力：
換気設備のエネルギー効率を判断する指標。値が小さいほうが省エネルギー性能が高い。比消費電力（W(㎥/h)）＝消費電力÷風量

==== 端末部材：
屋外から外気の取り入れ口、屋外へ室内空気の排出口に取り付ける部材。圧力損失の小さいものを選定することが重要（改p276,280）。　→図（温ガp276表）

==== 気密性能：
建物に存在する隙間の程度を表したもの。専用の測定器で計測し、相当隙間面積C値という指標で表されます(改p73)。

==== 換気経路：
給気から排気に至る空気の流れのこと。排出された空気が再度外気として入ってくるのを防ぐ必要がある。（改p270）

==== 交流モーター(ACモーター)：

==== 直流モーター（DCモーター）：
同じ風量の場合に入力電力が小さく省エネルギー型である(温暖地改p267)。ただし圧力損失が大きいと必ずしも省エネルギーにはならない(温暖地改p269)。

==== プロペラファン：
家庭で一般に使われている「換気扇」。外壁などに直接取り付ける（一財ベターリビング）→図（温ガp275図５）

==== シロッコファン：
多翼送風機ともいう。水車と同じ原理で、羽根車には幅の狭い前向きの羽根が多数ついている。ダクト接続用のファンや台所レンジのファンなど多用途に用いられる（一財ベターリビング）。→図(探す）

==== ターボファン：
シロッコファンと羽根の形態はにているが、比較的広幅の後ろ向きの羽根がついている。他のファンに比較して最も静圧が高くできる（一財ベターリビング）。

==== 同時給排気型：
排気に見合った給気をレンジフードに送り込んで換気システム全体の空気の流れを妨げないようにする仕組み（suumo住宅用語大辞典）

==== 気密シャッター：
換気停止時の隙間風対策(改p277)。ただし開放している時間は電力を消費している。→図（温ガp278図９）

==== 輻流型：
壁面に沿って吸気が放射状に拡散する形状のもの(改p277)　→図(温p278、図10)
