
== 換気設備計画マニュアル Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野

== 省エネルギー手法の解説（入力ガイド説明文）
NOTE: 「エネルギー消費性能計算プログラム(住宅版) 」のヘルプボタンの説明を簡潔にし、図表を追加する

NOTE: 自立テキストの補足情報（省エネになる方法）を追記する


=== 換気設備の方式の選択
・24時間換気に用いる換気設備を対象とします。換気設備の種類を選択して下さい。

「第一種換気」とは、給気及び排気を換気設備で行う方式をいいます。

「第二種換気」とは、給気を換気設備で行い、排気は自然排気で行う方式をいいます。

「第三種換気」とは、給気を自然給気で行い、排気は換気設備で行う方式をいいます。

「ダクト式」とは、換気設備に長さ１ｍ以上のダクトを接続するものをいいます。

「壁付け式」とは、換気設備に長さ１ｍ以上のダクトを接続しないものをいいます。

局所換気設備が全般換気設備を兼ねる場合は、該当する設備の方式を選択して下さい。

TIP: 換気方式のイラスト【温暖地版P261】

=== ダクト式換気設備を設置する場合
==== 評価方法の選択
・「評価しない」は、換気設備について特に省エネルギー対策を実施していない場合、あるいは省エネルギー対策を評価しない場合に選択して下さい。設置される機器の省エネルギー対策が不明な場合もこちらを選択して下さい。

・「省エネルギー手法を選択する」は、換気設備の省エネルギー対策として、「径の太いダクトを使用」あるいは、「径の太いダクトを使用、かつ直流モーターを採用」のいずれかの措置について省エネルギー効果を評価する場合に選択して下さい。

・「比消費電力を入力する」は、換気設備の省エネルギー対策の効果を比消費電力（設計風量当たりの換気設備の消費電力）に基づいて評価する場合に選択して下さい。

==== 採用した省エネルギー手法を選択し省エネルギー効果を評価する
・ダクト式換気設備の省エネルギー対策として、内径の太いダクトを使用した場合と、直流モーターの電動機を採用した場合について、省エネルギー効果を評価することができます。省エネルギー手法の判断方法は下表のとおりです。

TIP: 表：WEBプログラムヘルプ

・施工性や省スペースを優先しすぎて細型のダクトを用いることがありますが、できるだけそうしたことを避け、風量に見合った適切な太さのダクトを用いることが重要です。住宅の場合、通常は主ダクトで直径 100 ㎜、枝ダクトで直径50 ㎜のダクトを用いることが一般的ですが、ダクト等の圧力損失を低減して省エネルギーをはかるには、主ダクトで直径100㎜以上、枝ダクトで直径75 ㎜以上のダクトを使用することが効果があります。

・ダクトの長さを短くしたり、曲りを少なくすることにより、圧力損失を抑えることができ、消費電力の小さい機種とすることが可能になります。

==== 比消費電力を入力し省エネルギー効果を評価する（ダクト式換気設備）

・換気設備の省エネルギー対策として、「省エネルギー手法を選択する」の項目に示される対策以外の手法に取り組む場合などで、省エネルギー効果を反映させることができます。

・比消費電力は、全般換気設備、ダクト及び電動機の種別に応じて定まる下表の数値を用いるか、または当該住戸において全般換気設備の消費電力及び全般換気設備の設計風量を求めて算出することができます。なお、異なる種別に該当する換気設備を複数用いる場合は、各々の比消費電力を比較して最も大きな値を使用することとします。

TIP: 比消費電力の計算例を追加する

・換気システムに採用されているモーターには交流モーター（ACモーター）と直流モーター（DCモーター）の 2つがあります。一般的に DCモーターは同じ風量の場合に入力電力が小さく省エネルギー型といえます。

・DCブラシレスモーターは消費電力が小さいほか、回転数などの制御性が高いため、一定の風量や一定の機外圧力に制御することが容易です。そのため外部風圧の変動などによってファンにかかる圧力が変動した場合にも一定の風量で制御できるような機器もあります。

・ACモーターも総合効率が高いものがあり、ファンの選定には、設計された風量における、1㎥/h の空気を搬送するために必要な入力電力を表す比消費電力の多寡で選択をすることが勧められます。

・DCモーターを用いた風量一定制御は、ダクトなどの圧力損失が小さい場合は、省エネとなりますが、圧力損失が大きいと必ずしも省エネとはなりません。ダクト等の圧力損失低減を適用することを高効率機器の要件とします。

=== 壁付け換気設備を設置する場合

==== 評価方法の選択

・特に省エネルギー対策をしていない」は、換気設備について特に省エネルギー対策を実施していない場合、あるいは省エネルギー対策を評価しない場合に選択して下さい。設置される機器の省エネルギー対策が不明な場合もこちらを選択して下さい。

・「比消費電力を入力することにより省エネルギー効果を評価する」は、換気設備の省エネルギー対策の効果を比消費電力（設計風量当たりの換気設備の消費電力）に基づいて評価する場合に選択して下さい。

==== 比消費電力を入力し省エネルギー効果を評価する（壁付け式換気設備）

・換気設備の省エネルギー対策として、「省エネルギー手法を選択する」の項目に示される対策以外の手法に取り組む場合などで、省エネルギー効果を反映させることができます。

・比消費電力は、全般換気設備、ダクト及び電動機の種別に応じて定まる下表の数値を用いるか、または当該住戸において全般換気設備の消費電力及び全般換気設備の設計風量を求めて算出することができます。なお、異なる種別に該当する換気設備を複数用いる場合は、各々の比消費電力を比較して最も大きな値を使用することとします。

TIP: 比消費電力の計算例を追加する

・エネルギー効率の高いファンと圧力損失の小さな屋外端末を使用し、ファンと屋外端末の組み合わせを適正化することが大切です。

・壁付け式換気システムの送風ファンの羽根形状は、主にプロペラファンとターボファンに分けられます。一般にターボファンは許容できる機外圧力が高く、フィルターの目詰まりによる風量減少の問題が比較的少ないといえます。換気メーカーのカタログには、ファンの形状（プロペラファンやターボファン）が示されているので、選択の参考にすることができます。

TIP: 温暖地版P275　図5　換気システム用換気扇の例

=== 換気回数

・評価対象住戸における換気回数を選択して下さい。換気回数は、建築基準法施行令第 20 条の 7 第 1 項第 2号の表における「住宅等の居室」の分類等に従い判断して下さい（下表）。

TIP: 換気回数の判断方法については、「2.エネルギー消費性能の算定方法」の「第五章換気設備」を参照して下さい。

TIP: 換気回数の選択肢の表【WEBプログラムヘルプボタン】

=== 有効換気量率

・有効換気量率とは、第一種換気設備において、有効換気量の給気量に対する比率のことです。第一種換気設備であって、還気が給気に混入することのない設備の場合は「1」を入力して下さい。

・給気量は JIS B 8628（全熱交換器）における附属書１「風量測定方法」におけるチャンバ方式またはダクト方式により計測された値になります。

・ダクト式第一種換気設備の有効換気量は、定格風量により以下の方法で求めてください。

　①小型全熱交換器（定格風量が 250m3/h 未満のもの）については JRA 4056「全熱交換器 有効換気量試験方法」におけるチャンバ内設置法

　②中型全熱交換器（定格風量が 250m3/h 以上 2000m3/h 以下のもの）については JRA 4056「全熱交換器 有効換気量試験方法」におけるダクト接続法

・壁付け式第一種換気設備の有効換気量は、JIS B 8628（全熱交換器）の附属書 3「有効換気量測定方法」における減衰法により測定及び計算される値を用いて求めます。

TIP: 有効換気量率の計算方法は、「2.エネルギー消費性能の算定方法」の「第五章換気設備」を参照して下さい。


=== 熱交換型換気設備を導入する
==== 熱交換型設備の設置
・熱交換換気設備を設置することにより、条件によって暖房負荷を削減することができます。評価対象住戸に、熱交換型換気設備を設置する場合に熱交換型換気を「設置する」を選択して下さい。

・8地域では、熱交換型換気を「設置する」を選択することはできません。

・熱交換型換気設備の「有効換気量率」、「温度交換効率」、計算対象とする住宅の「設計給気風量」及び「設計還気風量」又は「設計外気風量」及び「設計排気風量」の情報が不明な場合は、熱交換型換気を「設置する」を選択することはできません。

==== 温度交換効率
・熱交換型換気設備において、給気乾球温度と外気乾球温度の差が還気乾球温度と外気乾球温度の差にどれだけ近いかを表す指標です。

・JIS B 8628 （全熱交換器）に規定された温度交換効率を入力して下さい。顕熱交換型換気設備の場合も、JIS B 8628に規定された試験方法及び計算方法により計算で求めてください。

・値は、100分の1未満の端数を切り下げた小数第二位までの値とし、パーセント単位で入力してください（値に100を乗じてください）。ただし、値が95（％）を上回る場合は、95を入力してください。

・なお、以下の場合は熱交換型換気設備による暖房負荷の削減効果を見込むことはできません。

 ・温度交換効率ηtが0.4を下回る場合
　
 ・定格条件における給気風量が定格条件における排気風量の半分未満、若しくは2倍より大きい場合
 
==== 給気と排気の比率による温度交換効率の補正係数
NOTE: 省略（WEBプログラムヘルプ参照）

==== 排気過多時における住宅外皮経由の漏気による温度交換効率の補正係数 
NOTE: 省略（WEBプログラムヘルプ参照）


== エネルギー消費性能計算プログラムで現在評価できない手法

==== 温度差利用型ハイブリッド換気の導入

・温度差利用型ハイブリッド換気を計画的に設計するためには、住宅の気密性能は高いものとすることが必要です。

・給気口と排気口の合計面積が、住宅の床面積（吹き抜けがある場合はその部分も床があるとみなした面積とする）あたり、下表の必要有効開口面積となるようにします。1階または床下の給気口と2階または排気筒の排気口の面積は同程度になるようにします。

TIP: 温暖地版P272　表7　給気口・排気口の必要有効開口面積と動力削減効果

・給気口または排気口で、換気量が一定になるような制御を行います。制御を行わないと、内外温度差が大きくなったときや風が強いときに換気量が過大になり、換気負荷（暖房エネルギー）が増加します。

・便所や浴室等には別途局所換気装置を設けます。温度差ハイブリッド換気で行う全般換気の経路には含みません。

・床面開口や通気用開口、ドアのアンダーカットなど、給気口から排気口まで各室を経由して空気が流れるように十分な開口を設けます。
