
== 給湯設備計画マニュアル Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野


== 省エネルギー手法の解説（入力ガイド説明文）
NOTE: 「エネルギー消費性能計算プログラム(住宅版) 」のヘルプボタンの説明を簡潔にし、図表を追加する

NOTE: 自立テキストの補足情報（省エネになる方法）を追記する

=== 給湯設備

[[shuho_hw_yokushituumu]]
==== 給湯設備・浴室等の有無

・「浴室等」とは、浴室、その他浴槽または身体の清浄を目的とした設備を有する室のことです。

=== 給湯熱源機

[[shuho_hw_shurui]]
==== 熱源機の分類

・温水暖房用の温水供給を兼ねる場合は「給湯・温水暖房一体型」を、コージェネレーション設備を設置している場合は「コージェネレーションを使用する」選択して下さい。コージェネレーション設備の種類は、タブ「コージェネ」で選択できます。

・評価時点で給湯機を設置しない場合は「給湯設備機器を設置しない」を、また選択肢にない給湯機を設置する場合は、「その他の給湯設備機器」を選択し、その名称も入力して下さい。

NOTE: 平成28年省エネルギー基準に準拠したエネルギー消費性能の評価に関する技術情報（住宅）

給湯機を設置しない場合、あるいは複数の給湯機を設置する場合の決定方法については、「2.エネルギー消費性能の算定方法」の「第七章第一節給湯設備」の「付録A 複数の給湯機を設置する場合の評価において代表させる給湯機の決定方法 及び　付録 B 給湯機を設置しない場合に評価において想定する機器の種類と仕様」を参照して下さい。

NOTE: リンク or 説明をここに記載する


=== 熱源機(給湯専用型)の種類

[[shuho_hw_senyo_sr1_e]]
==== 効率(エネルギー消費効率)を入力する（ガス従来型給湯機）

・カタログ等を参照し、エネルギー消費効率を入力してください。

TIP: カタログのイラスト例

・設置する給湯機が複数あり、いずれもガス給湯機でかつ効率が異なる場合は、効率の小さい方の値を用いて評価して下さい。

・なお、エネルギー消費効率とは、「エネルギーの使用の合理化に関する法律」に基づく「特定機器の性能の向上に関する製造事業者等の判断の基準等」（ガス温水機器）に定義される「エネルギー消費効率」のことです。ただし、給湯温水暖房機でふろ機能の種類が「給湯単機能」あるいは「ふろ給湯機（追焚なし）」の場合は、JIS S 2109 による「（瞬間湯沸器の）熱効率」に基づき測定された値になります。

[[shuho_hw_senyo_sr1_emode]]
==== 効率(モード熱効率)を入力する（ガス従来型給湯機）

・カタログ等を参照し、モード熱効率を入力してください。

TIP: カタログのイラスト例

・なお、モード熱効率とは、JIS S 2075（家庭用ガス・石油温水機器のモード効率測定法）に定められた測定方法に基づく値です。

[[shuho_hw_senyo_sr7_e]]
==== 効率(エネルギー消費効率)を入力する（ガス潜熱回収型給湯機）

・カタログ等を参照し、エネルギー消費効率を入力してください。

TIP: カタログのイラスト例

・設置する給湯機が複数あり、いずれもガス給湯機でかつ効率が異なる場合は、効率の小さい方の値を用いて評価して下さい。

・なお、エネルギー消費効率とは、「エネルギーの使用の合理化に関する法律」に基づく「特定機器の性能の向上に関する製造事業者等の判断の基準等」（ガス温水機器）に定義される「エネルギー消費効率」のことです。ただし、給湯温水暖房機でふろ機能の種類が「給湯単機能」あるいは「ふろ給湯機（追焚なし）」の場合は、JIS S 2109 による「（瞬間湯沸器の）熱効率」に基づき測定された値になります。

[[shuho_hw_senyo_sr7_emode]]
==== 効率(モード熱効率)を入力する（ガス潜熱回収型給湯機）

・カタログ等を参照し、モード熱効率を入力してください。

TIP: カタログのイラスト例

・なお、モード熱効率とは、JIS S 2075（家庭用ガス・石油温水機器のモード効率測定法）に定められた測定方法に基づく値です。

[[shuho_hw_senyo_sr2_e]]
==== 効率(熱効率)を入力する（石油従来型給湯機）

・カタログ等を参照し、熱効率を入力してください。

TIP: カタログのイラスト例

・設置する給湯機が複数あり、いずれも石油給湯機でかつ効率が異なる場合は、効率の小さい方の値を用いて評価して下さい。

・なお、熱効率とは、JIS S 3031（石油燃焼機器の試験方法通則）の連続給湯効率試験方法あるいは湯沸効率試験方法に基づく「熱効率」の値です。

[[shuho_hw_senyo_sr2_emode]]
==== 効率(モード熱効率)を入力する（石油従来型給湯機）

・カタログ等を参照し、モード熱効率を入力してください。

TIP: カタログのイラスト例

・なお、モード熱効率とは、評価対象機器の JIS S 2075（家庭用ガス・石油温水機器のモード効率測定法）に基づくモード熱効率の値です。

[[shuho_hw_senyo_sr8_e]]
==== 効率(熱効率)を入力する（石油潜熱回収型給湯機）

・カタログ等を参照し、熱効率を入力してください。

TIP: カタログのイラスト例

・設置する給湯機が複数あり、いずれも石油給湯機でかつ効率が異なる場合は、効率の小さい方の値を用いて評価して下さい。

・なお、熱効率とは、JIS S 3031（石油燃焼機器の試験方法通則）の連続給湯効率試験方法あるいは湯沸効率試験方法に基づく「熱効率」の値です。

[[shuho_hw_senyo_sr8_emode]]
==== 効率(モード熱効率)を入力する（石油潜熱回収型給湯機）

・カタログ等を参照し、モード熱効率を入力してください。

TIP: カタログのイラスト例

・なお、モード熱効率とは、評価対象機器の JIS S 2075（家庭用ガス・石油温水機器のモード効率測定法）に基づくモード熱効率の値です

[[shuho_hw_senyo_sr4_e]]
==== JIS効率を入力する（電気ヒートポンプ給湯機(CO2冷媒)(太陽熱利用給湯設備を使用しないもの) ）

・カタログ等を参照し、JIS効率を入力してください。

TIP: カタログのイラスト例

・JIS 効率とは、評価対象機器の JIS C 9220：2011（家庭用ヒートポンプ給湯機） に基づく年間給湯保温効率（JIS）又は年間給湯効率（JIS）の値です。小数点以下1桁までの値を入力して下さい。なお、JIS C 9220：2018に基づく「ふろ熱回収機能」を含むJIS効率では、現時点では評価できませんので、JIS C 9220：2011に基づくJIS効率を確認の上、入力してください。

・設置する機種に、これらの値が表示されておらず、代わりに、日本冷凍空調工業会標準規格 JRA4050（家庭用ヒートポンプ給湯機）に基づく年間給湯効率（APF）が表示されている場合は、以下の方法で効率を求めてください。

① ふろ機能の種類が「給湯単機能」又は「ふろ給湯機（追焚なし）」の場合

JRA4050に基づく年間給湯効率（APF）の値を用いて下式より換算した値

JIS 効率（プログラムへの入力値） ＝ 年間給湯効率（APF）－ 0.5

② ふろ機能の種類が「ふろ給湯機（追焚あり）」の場合

JRA4050:2007R に基づく年間給湯効率（APF）の値を用いて下式より換算した値

JIS 効率（プログラムへの入力値） ＝ 年間給湯効率（APF）－ 0.7

・設置する給湯機が複数あり、いずれも電気ヒートポンプ給湯機でかつ効率が異なる場合は、効率の小さい方の値を用いて評価して下さい。

[[shuho_hw_senyo_sr4_m1see]]
==== M1スタンダードに基づくJIS相当効率を入力する（認定機種のみ）（電気ヒートポンプ給湯機(CO2冷媒)(太陽熱利用給湯設備を使用しないもの) ）

・「平成28年省エネルギー基準に準拠したエネルギー消費性能の評価に関する技術情報（住宅）」の2.2 算定方法「第七章 給湯設備」に添付する『電気ヒートポンプ給湯機（CO2冷媒）の M1 スタンダードに基づく JIS 相当効率について』に掲載されている機種に限ります。

[[shuho_hw_header_type]]
=== 配管方式

・給湯熱源機から各給湯先までの配管方式は、ヘッダー方式（給湯熱源機から給湯ヘッダーを介し、各給湯先まで配管する場合）を採用し、ヘッダー分岐後(分岐後、部分的に先分岐となっている場合も含む)のすべての配管径を小口径化（13A以下）することで、省エネルギー効果が認められます。

[[shuho_hw_suisen]]
=== 水栓

・台所、浴室、洗面に設置される水栓の種類をそれぞれ選択します。

・湯の使用量低減によって一次エネルギー消費量の削減に資する水栓を「節湯水栓」といいます。

・節湯水栓は、手元止水機構、小流量吐水機構、または水優先吐水機構を有するものを評価対象とします。なお、流量調節部及び温度調節部が使用者の操作範囲内にあるものを対象とします。

[[shuho_hw_daidokoro_suisen]]
==== 台所水栓

・台所水栓が複数ある場合は、以下の方法で水栓の仕様を選択してください。

・①１箇所でも「２バルブ水栓」があれば、「２バルブ水栓」を選択して下さい。

・②１箇所でも「手元止水機能」が付いていなければ、「無」を選択して下さい。

・③１箇所でも「水優先吐水機能」が付いていなければ、「無」を選択して下さい。

・「2バルブ水栓以外のその他の水栓」を選択した場合は、節湯水栓の機能（手元止水機能および水優先吐水機能）の採用の有無を選択して下さい。

[[shuho_hw_shower_suisen]]
==== 浴室シャワー水栓

・浴室シャワー水栓が複数ある場合は、以下の方法で水栓の仕様を選択してください。

・①１箇所でも「２バルブ水栓」があれば、「２バルブ水栓」を選択して下さい。

・②１箇所でも「手元止水機能」が付いていなければ、「無」を選択して下さい。

・③１箇所でも「小流量吐水機能」が付いていなければ、「無」を選択して下さい。

・「２バルブ水栓以外のその他の水栓」を選択した場合は、節湯水栓の機能（手元止水機能および小流量吐水機能）の採用の有無を選択して下さい。

[[shuho_hw_senmen_suisen]]
==== 洗面水栓

・洗面水栓が複数ある場合は、以下の方法で水栓の仕様を選択してください。

・①１箇所でも「２バルブ水栓」があれば、「２バルブ水栓」を選択して下さい。

・②１箇所でも「水優先吐水機能」が付いていなければ、「無」を選択して下さい。

・「２バルブ水栓以外のその他の水栓」を選択した場合には、節湯水栓 の機能（水優先吐水機能）の採用の有無を選択して下さい。

[[shuho_hw_daidokoro_temoto]]
==== 手元止水機能

・台所に設置された湯水混合水栓で、吐水切替機能や流量及び温度の調節機能と独立し、使用者の操作範囲内に設けられたボタンやセンサー等のスイッチにより、吐水及び止水操作ができる機構を有するものを評価対象とします。

NOTE: イラスト　hotwater003

[[shuho_hw_daidokoro_yusen]]
==== 水優先吐水機能

・台所水栓のうち、以下の機構を有し、水栓又は取扱説明書等に水栓の正面位置が判断できる表示がされているものを評価対象とします。

①吐水止水操作部と一体の温度調節を行うレバーハンドルが水栓の正面に位置するときに湯が吐出されない構造を有するもの

②吐水止水操作部と一体の温度調節を行うレバーハンドルが水栓の胴の左右側面に位置する場合は、温度調節を行う回転軸が水平で、かつレバーハンドルが水平から上方 45°に位置する時に湯が吐出されない構造を有するもの

③湯水の吐水止水操作部と独立して水専用の吐水止水操作部が設けられた湯水混合水栓

NOTE: イラスト hotwater004・hotwater005・hotwater006

[[shuho_hw_shower_shoryuryo]]
==== 小流量吐水機能

・小流量吐水機構を有する水栓とは、「設計一次エネルギー消費量算定方法」の「7. 給湯設備　付録K 小流量吐水機構を有する水栓の適合条件」の方法によって試験を行ったときの吐水力が、下表に適合する水栓をさします。

・吐水切替えが可能な浴室シャワー水栓については、主たる使用モードにおいて条件を満たしていればよいです。なお、主たる使用モードとは、体を洗い流すことを目的とするモードで、マッサージや温まり、掃除等を目的とする付加的なモードではありません。

TIP: 適合の条件

流水中に空気を混入させる構造を持たないもの　0.60（単位 N）以上

流水中に空気を混入させる構造を持つもの　0.55（単位 N）以上

=== 浴槽

[[shuho_hw_yokuso_hoon]]
==== 浴槽の保温措置

・浴槽本体からの熱損失を軽減するために浴槽を保温構造とすることです。

・JIS A 5532（浴槽）において「高断熱浴槽」と定義された浴槽の性能を満たしている場合に「高断熱浴槽を使用する」を選択することができます。


