== 用語解説（簡易版」

[[guide_hw_central]]
==== 住戸セントラル方式：
給湯機から配管で必要な場所に適時適量の湯を供給する給湯方式。熱源(給湯機)、配管、水栓、浴槽について、それぞれ省エネ措置を検討する必要がある。(『温暖地版 自立循環型住宅への設計ガイドライン』283ページ、図1を参考にしてください。）

TIP: 図（温ガp283図１）

[[guide_hw_kobetsu]]
==== 個別給湯方式：
台所の小型湯沸かし器や風呂釜など、各場所で給湯する方式。

[[guide_hw_netsugen]]
==== 熱源：
燃料別に、ガス、石油、電気の3種類がある。気候条件、世帯構成、使用状況などの条件に応じて、できるだけ効率の高くなる熱源を導入することが重要。

TIP: (温ガp.282)

[[guide_hw_shunkanshiki]]
==== 瞬間式：
瞬時に燃料を燃焼させて給湯の加熱を行うもの。

TIP: (温ガp.282)

[[guide_hw_sennetsu]]
==== 潜熱回収型：
排気ガス中の熱を有効利用することで高効率化をはかったもの。コンプレッサーで冷媒を圧縮して集熱部・放熱部での熱移動を行うことで、消費エネルギーより多くの熱を得ることができる仕組み。(『温暖地版 自立循環型住宅への設計ガイドライン』295ページ、図6を参考にしてください。）

TIP: 図（温ガp295図６）

[[guide_hw_heatpump]]
==== ヒートポンプ式（CO2HP）：
外気から集熱を行う高効率の熱源。瞬時の加熱能力が小さいため、貯湯タンクが必要。大量出湯時には湯切れする場合がある。『温暖地版 自立循環型住宅への設計ガイドライン』297ページ、図10を参考にしてください。）

TIP: 図（温ガp297図10）

[[guide_hw_co2hp]]
==== CO2HP：
高圧のCO2冷媒を利用するヒートポンプのこと。

TIP: (温ガp.297)

[[guide_hw_heatshock]]
==== ヒートショック：
極端な体温変化による血圧の急激な変化などによる体調不良のこと。冬期の入浴、トイレなど、温度変化のある場所で起こりやすい。

TIP: （温ガp.283、310）

[[guide_hw_sayakanheader]]
==== サヤ管ヘッダー方式：
ヘッダーから先の住宅設備機器に至る配管径を細くする給水方式。(『温暖地版 自立循環型住宅への設計ガイドライン』283ページ、図1を参考にしてください。）

TIP: 図（温ガp283図１）

[[guide_hw_setsuyukigu]]
==== 節湯器具：
湯の消費量を節約する器具。「手元止水」「小流量吐水」「水優先吐水」に分類されている。

TIP: 図（温ガp307表８）

[[guide_hw_setsuyugatasuisen]]
==== 節湯型水栓：
台所・洗面の水栓や浴室のシャワーなど湯を使う水栓で、湯消費を削減する工夫がされたもの。

TIP: 図（温ガp307表８）

[[guide_hw_yokuso_hoon]]
==== 高断熱浴槽：
断熱材で浴槽を覆うことで浴槽の湯が冷めにくくし、保温性能を高めているもの。放熱ロスが少ないため、追焚負荷の低減に有効。

TIP: 図（温ガp.309図16）

[[guide_hw_setsuyugatayokusou]]
==== 節湯型浴槽：
湯の消費量を削減する浴槽。ステップや手すりの形状が工夫されており、少ない湯量で水位を確保できる。

TIP: 図（温ガp.309図17）

[[guide_hw_jidouyuhari]]
==== 自動湯はり：
ボタンを押すだけで、浴槽に設定の量・温度の湯を自動的にはることができる機能。

TIP: (温ガp.291)

[[guide_hw_oidaki]]
==== 追焚：
冷めた湯を温め直す機能。

TIP: (温ガp.291)

[[guide_hw_gousuu]]
==== 号数：
ガス瞬間式給湯機の瞬時加熱能力。1号とは、1分間に1Lの水の温度を25℃上げる能力を指す。

TIP: (温ガp.289)

[[guide_hw_fullautoshunkan]]
==== フルオート(瞬間式): 
浴槽に湯を入れる際の水位レベルを指定する機種。 

TIP: (温ガp.289)

[[guide_hw_fullautochotou]]
==== フルオート(貯湯式):
浴槽の自動湯はりと追焚の両方が可能な機種。

TIP: (温ガp.289)

[[guide_hw_semiautoshunkan]]
==== セミオート(瞬間式)：
湯量（リットル）を指定する機種。

TIP: (温ガp.289)

[[guide_hw_semiautochotou]]
==== セミオート(貯湯式)：
自動湯はりのみ可能で追焚ができない機種。

TIP: (温ガp.289)

[[guide_hw_shizenjunkan]]
==== 自然循環式：
釜で温められた湯が浮力で循環すること。

TIP: (温ガp.291)

[[guide_hw_kyouseijunkan]]
==== 強制循環式：
浴槽と給湯機との間を2本の配管で接続して両方の配管で給湯を行い、追焚時には、片方の配管で浴槽の湯を給湯機にポンプ動力で引き込み、給湯機で昇温した湯を他方の配管で浴槽に戻す方式。風呂と給湯機の設置場所の自由度が高い。

TIP: (温ガp.291)

[[guide_hw_sashiyu]]
==== さし湯：
湯が冷めた際に熱い湯を足すこと。さし湯を上手に使うことで省エネ効果が期待できる。

TIP: (温ガp.291)

[[guide_hw_shuttoupattern]]
==== 出湯パターン：
一日の給湯の消費量を想定したパターン。

TIP: (温ガp.293)

[[guide_hw_ibeclmode]]
==== IBECLモード：
30年ほど前の湯消費実態を基に4人世帯を前提として作成された使用条件。1日に13回の出湯しか行わないなど、現状に即していない面がある。

TIP: (温ガp.293)

[[guide_hw_shuseim1mode]]
==== 修正M1モード：
4人家族を想定し、代表的な6日間から構成された全30日の使用条件。従来の試験条件に比べて、日変動を含めた実使用に近い条件での効率評価が可能になった。

TIP: (温ガp.293)

[[guide_hw_m1standardmode]]
==== M1スタンダードモード：
2012年施行の「低炭素認定基準」、2013年施行の「平成25年省エネルギー基準」において新たに定義された使用条件。短時間出湯、1～4人の世帯人数に応じた消費量、より実使用に近い効率評価が可能となった。

TIP: (温ガp.293)

[[guide_hw_nenkankyutoukouritsu]]
==== 年間給湯効率（APF）：
年間を通じて、1の電気により機器から取り出せる給湯の熱負荷の比率を表します。省エネには、値が大きい機種を選択する。ただし、東京・大阪の気象条件を想定しているため、寒冷地ではAPFより低い効率、蒸暑地ではAPFより高い効率になると考えられる。

TIP: (温ガp.299)

[[guide_hw_nenkanhoonkouritsu]]
==== 年間給湯保温効率（JIS）：
APFをベースに、浴槽の追焚を追加した出湯パターンによるシステム全体のエネルギー効率。省エネには、値が大きい機種を選択する。

TIP: (温ガp.300)

[[guide_hw_energyshouhikouritsu]]
エネルギー消費効率：
ヒートポンプユニット単体の性能。1の電気で得られる加熱量を示す。CO2HPは外気を熱源とするため、外気温度の季節変動に伴い大きく効率が変化する。

TIP: (温ガp.299)

[[guide_hw_modonetsukouritsu]]
==== モード熱効率：
JIS S2075（家庭用ガス・石油温水機器のモード効率測定法）に定められた測定方法に基づく値

[[guide_hw_jiskouritsu]]
==== JIS効率： 
JIS C 9220：2011（家庭用ヒートポンプ給湯機）に基づく年間給湯保温効率（JIS）又は年間給湯効率（JIS）の値

[[guide_hw_temotoshisui]]
==== 手元止水水栓：
タッチ式の機構やリモートセンサー・リモートスイッチにより、通常の操作よりも容易に止水を行うことができる水栓。

TIP: 図（温ガp307表８）

[[guide_hw_shouryoutosui]]
==== 小流量吐水水栓：
少ない流量で快適に使える工夫がされた水栓。

TIP: 図（温ガp307表８）

[[guide_hw_mizuyuusen]]
==== 水優先吐水：
通常の使用において水が優先的に出るように工夫された水栓。意図しない不必要な出湯を削減することが可能。

TIP: 図（温ガp308図15）

[[guide_hw_gas_jurai_kyutou_onsuidanbou]]
==== ガス従来型給湯温水暖房機：
ガスをエネルギー源とし、給湯機能と温水暖房機能を備えた熱源機。

[[guide_hw_gas_sennetsu_kyutou_onsuidanbou]]
==== ガス潜熱回収型給湯温水暖房機：
ガスをエネルギー源とし、給湯機能と温水暖房機能を備えた熱源機。従来型熱源機の一次熱交換器に加え二次熱交換器で排気中の水蒸気を水にすることにより、排気中の潜熱を回収して、熱効率を向上させた熱源機。

[[guide_hw_sekiyu_jurai_kyutou_onsuidanbou]]
==== 石油従来型給湯温水暖房機：
灯油をエネルギー源とし、給湯機能と温水暖房機能を備えた熱源機。

[[guide_hw_sekiyu_sennetsu_kyutou_onsuidanbou]]
==== 石油潜熱回収型給湯温水暖房機：
灯油をエネルギー源とし、給湯機能と温水暖房機能を備えた熱源機。従来型熱源機の一次熱交換器に加え二次熱交換器で排気中の水蒸気を水にすることにより、排気中の潜熱を回収して、熱効率を向上させた熱源機。

[[guide_hw_denkiheater_kyutou_onsuidanbou]]
==== 電気ヒーター給湯温水暖房機：
電気ヒーターにより電気を熱に変換して過熱する給湯温水暖房機。夜間時間帯の電気を利用して暖められた湯又は不凍液を貯湯タンクに貯める貯湯タイプが一般的。

[[guide_hw_denkiheatpump_gas_shunkanheiyougata_kyuutou_onsuidanbou]]
==== 電気ヒートポンプ・ガス瞬間式併用型給湯温水暖房機：
電気ヒートポンプと潜熱回収型ガス熱源機により構成された給湯温水暖房機。

