
== 給湯設備計画：

=== 給湯設備計画とは
熱源、配管システム、水栓・浴槽の3つで構成され、給湯機から配管で必要な場所に適時適量の湯を供給する「住戸セントラル方式」の技術です。
衛生的で快適な住生活をおくる上で、給湯設備は不可欠なものとなっています。住宅におけるエネルギー消費のうち、給湯に費やされる割合はたいへん大きく、給湯設備を計画するうえで省エネルギーに配慮することは非常に重要です。

===== 自立循環型住宅オプション（仮）
  ・節湯型浴槽の評価（未実装）

=== 目標レベル
  ☆☆☆☆☆　目標レベルと参考仕様を記載
  ☆☆☆☆
  ☆☆☆
  ☆☆
  ☆
  
  モデル住宅による標準的なエネルギー消費量　25.1GJ
TIP: 概要の地域選択を反映させて切り替えられると良い。

=== 熱源機の分類
 ・給湯専用型
 ・給湯・温水暖房一体型
 ・コージェネレーションを使用する
 ・その他の給湯設備機器
 ・給湯設備機器を設置しない
 
=== 熱源機（給湯専用型）の種類
 ・ガス従来型給湯機
 ・ガス潜熱回収型給湯機（通称：エコジョーズ）
 ・石油従来型給湯機
 ・石油潜熱回収型給湯機（通称：エコフィール）
 ・電気ヒーター温水器
 ・電気ヒートポンプ給湯機(CO2冷媒)(太陽熱利用給湯設備を使用しないもの)（通称：エコキュート）
 ・電気ヒートポンプ・ガス瞬間式併用型給湯機（通称：ハイブリッド）
 
=== 効率の入力
 ・入力しない
 ・効率(エネルギー消費効率)を入力
 ・効率(モード熱効率)を入力
 
=== ふろ機能の種類
 ・給湯単機能
 ・ふろ給湯機（追焚なし）
 ・ふろ給湯機（追焚あり）

=== 配管方式
 ・先分岐方式
 ・ヘッダー方式

=== 台所水栓
 ・2バルブ水栓
 ・2バルブ水栓以外のその他の水栓

=== 浴室シャワー水栓
 ・2バルブ水栓
 ・2バルブ水栓以外のその他の水栓

=== 洗面水栓
 ・2バルブ水栓
 ・2バルブ水栓以外のその他の水栓

=== 浴槽の保温措置
 ・高断熱浴槽を使用しない
 ・高断熱浴槽を使用する
 
NOTE: 節湯型浴槽は追加できないか？

=== 設計上の配慮事項・暮らし方の留意点

==== 世帯人数に合わせた機器容量の選定
　世帯人数が同じでも湯消費実態は住宅ごとに大きく異なります。また、湯消費は住宅差が大きいことから、設計時に住まい手に対し事前ヒアリングを行うことも有効です。過去の燃料（電気・ガス・石油）や水道の検針値をチェックすることもお奨めです。
水道の検針値は、通常2 カ月分の値で、4 人家族の平均的な消費では40 ～ 60 ㎥となります。湯消費はこのうちおおむね半分程度として推測することができます。

==== 瞬間式・瞬間貯湯式の能力決定
　ガス・石油を利用する熱源の多くは「瞬間式」で、給湯時に加熱を行うため、瞬時の最大給湯能力に上限があります。給湯の同時使用量によって能力を確認します。
　電気を利用する熱源（CO2HP・電気温水器等）のほとんどは、深夜電力利用の貯湯式です。貯湯式は1 日に使う湯量が制限されるため、貯湯タンクの容量を正しく選択することが重要です。
 
==== コストとの関係について
　省エネルギー型の給湯設備はイニシャルコストが相対的に高くなりますが、ランニングコストの低減効果や二酸化炭素排出量の削減効果を考慮して方式を選定することが望まれます。
