== 用語解説（簡易版」
==== 住戸セントラル方式：
給湯機から配管で必要な場所に適時適量の湯を供給する給湯方式。熱源(給湯機)、配管、水栓、浴槽について、それぞれ省エネ措置を検討する必要がある。→図（温ガp283図１）

==== 個別給湯方式：
台所の小型湯沸かし器や風呂釜など、各場所で給湯する方式。

==== 熱源：
燃料別に、ガス、石油、電気の3種類がある。気候条件、世帯構成、使用状況などの条件に応じて、できるだけ効率の高くなる熱源を導入することが重要。(温ガp.282)

==== 瞬間式：
瞬時に燃料を燃焼させて給湯の加熱を行うもの。(温ガp.282)

==== 潜熱回収型：
排気ガス中の熱を有効利用することで高効率化をはかったもの。コンプレッサーで冷媒を圧縮して集熱部・放熱部での熱移動を行うことで、消費エネルギーより多くの熱を得ることができる仕組み。→図（温ガp295図６）

==== ヒートポンプ式（CO2HP）：
外気から集熱を行う高効率の熱源。瞬時の加熱能力が小さいため、貯湯タンクが必要。大量出湯時には湯切れする場合がある。→図（温ガp297図10）

==== CO2HP：高圧のCO2冷媒を利用するヒートポンプのこと。(温ガp.297)

==== ヒートショック：
極端な体温変化による血圧の急激な変化などによる体調不良のこと（温ガp.283、310）。冬期の入浴、トイレなど、温度変化のある場所で起こりやすい。

==== サヤ管ヘッダー方式：
ヘッダーから先の住宅設備機器に至る配管径を細くする給水方式。→図（温ガp283図１）

==== 節湯器具：
湯の消費量を節約する器具。「手元止水」「小流量吐水」「水優先吐水」に分類されている。→図（温ガp307表８）

==== 節湯型水栓：
台所・洗面の水栓や浴室のシャワーなど湯を使う水栓で、湯消費を削減する工夫がされたもの→図（温ガp307表８）

==== 高断熱浴槽：
断熱材で浴槽を覆うことで浴槽の湯が冷めにくくし、保温性能を高めているもの。放熱ロスが少ないため、追焚負荷の低減に有効。→図（温ガp.309図16）

==== 節湯型浴槽：
湯の消費量を削減する浴槽。ステップや手すりの形状が工夫されており、少ない湯量で水位を確保できる。→図（温ガp.309図17）

==== 自動湯はり：
ボタンを押すだけで、浴槽に設定の量・温度の湯を自動的にはることができる機能。(温ガp.291)

==== 追焚：
冷めた湯を温め直す機能。(温ガp.291)

==== 号数：
ガス瞬間式給湯機の瞬時加熱能力。1号とは、1分間に1Lの水の温度を25℃上げる能力を指す。(温ガp.289)

==== フルオート(瞬間式): 
浴槽に湯を入れる際の水位レベルを指定する機種。 (温ガp.289)

==== フルオート(貯湯式):
浴槽の自動湯はりと追焚の両方が可能な機種。(温ガp.289)

==== セミオート(瞬間式)：
湯量（リットル）を指定する機種。(温ガp.289)

==== セミオート(貯湯式)：
自動湯はりのみ可能で追焚ができない機種。(温ガp.289)

==== 自然循環式：
釜で温められた湯が浮力で循環すること。(温ガp.291)

==== 強制循環式：
浴槽と給湯機との間を2本の配管で接続して両方の配管で給湯を行い、追焚時には、片方の配管で浴槽の湯を給湯機にポンプ動力で引き込み、給湯機で昇温した湯を他方の配管で浴槽に戻す方式。風呂と給湯機の設置場所の自由度が高い。 (温ガp.291)

==== さし湯：
湯が冷めた際に熱い湯を足すこと。さし湯を上手に使うことで省エネ効果が期待できる。(温ガp.291)

==== 出湯パターン：
一日の給湯の消費量を想定したパターン。(温ガp.293)

==== IBECLモード：
30年ほど前の湯消費実態を基に4人世帯を前提として作成された使用条件。1日に13回の出湯しか行わないなど、現状に即していない面がある。(温ガp.293)

==== 修正M1モード：
4人家族を想定し、代表的な6日間から構成された全30日の使用条件。従来の試験条件に比べて、日変動を含めた実使用に近い条件での効率評価が可能になった。(温ガp.293)

==== M1スタンダードモード：
2012年施行の「低炭素認定基準」、2013年施行の「平成25年省エネルギー基準」において新たに定義された使用条件。短時間出湯、1～4人の世帯人数に応じた消費量、より実使用に近い効率評価が可能となった。 (温ガp.293)

==== 年間給湯効率（APF）：
年間を通じて、1の電気により機器から取り出せる給湯の熱負荷の比率を表します。省エネには、値が大きい機種を選択する。ただし、東京・大阪の気象条件を想定しているため、寒冷地ではAPFより低い効率、蒸暑地ではAPFより高い効率になると考えられる。(温ガp.299)

==== 年間給湯保温効率（JIS）：
APFをベースに、浴槽の追焚を追加した出湯パターンによるシステム全体のエネルギー効率。省エネには、値が大きい機種を選択する。(温ガp.300)

エネルギー消費効率：ヒートポンプユニット単体の性能。1の電気で得られる加熱量を示す。CO2HPは外気を熱源とするため、外気温度の季節変動に伴い大きく効率が変化する。(温ガp.299)

==== モード熱効率：
JIS S2075（家庭用ガス・石油温水機器のモード効率測定法）に定められた測定方法に基づく値

==== JIS効率： 
JIS C 9220：2011（家庭用ヒートポンプ給湯機）に基づく年間給湯保温効率（JIS）又は年間給湯効率（JIS）の値

==== 手元止水水栓：
タッチ式の機構やリモートセンサー・リモートスイッチにより、通常の操作よりも容易に止水を行うことができる水栓。→図（温ガp307表８）

==== 小流量吐水水栓：
少ない流量で快適に使える工夫がされた水栓。→図（温ガp307表８）

==== 水優先吐水：
通常の使用において水が優先的に出るように工夫された水栓。意図しない不必要な出湯を削減することが可能。→図（温ガp308図15）

==== ガス従来型給湯温水暖房機：
ガスをエネルギー源とし、給湯機能と温水暖房機能を備えた熱源機。

==== ガス潜熱回収型給湯温水暖房機：
ガスをエネルギー源とし、給湯機能と温水暖房機能を備えた熱源機。従来型熱源機の一次熱交換器に加え二次熱交換器で排気中の水蒸気を水にすることにより、排気中の潜熱を回収して、熱効率を向上させた熱源機。

==== 石油従来型給湯温水暖房機：
灯油をエネルギー源とし、給湯機能と温水暖房機能を備えた熱源機。

==== 石油潜熱回収型給湯温水暖房機：
灯油をエネルギー源とし、給湯機能と温水暖房機能を備えた熱源機。従来型熱源機の一次熱交換器に加え二次熱交換器で排気中の水蒸気を水にすることにより、排気中の潜熱を回収して、熱効率を向上させた熱源機。

==== 電気ヒーター給湯温水暖房機：
電気ヒーターにより電気を熱に変換して過熱する給湯温水暖房機。夜間時間帯の電気を利用して暖められた湯又は不凍液を貯湯タンクに貯める貯湯タイプが一般的。

==== 電気ヒートポンプ・ガス瞬間式併用型給湯温水暖房機：
電気ヒートポンプと潜熱回収型ガス熱源機により構成された給湯温水暖房機。


== （修正前：詳細版）
== 用語解説
==== 住戸セントラル方式：
新築やリフォームで最も普及している一般的な形式。給湯機から配管で必要な場所に適時適量の湯を供給します。熱源、配管システム、水栓・浴槽の3つで構成されます。それぞれについて省エネ措置を検討する必要があります。（温ガp.282,283）　→図（温ガp283図１）
　
==== 個別給湯方式：
小型湯沸かし器や風呂釜による給湯の仕組み。

==== 熱源：
燃料種別により、ガス、石油および電気の3つに分類されます。それぞれの特徴を理解した上で、気候条件、世帯構成や使用状況などの諸条件に応じて、できるだけ効率の高くなる熱源を導入することが重要です。(温ガp.282)

==== 瞬間式： 
ガスを熱源とする場合、瞬時に燃料を燃焼させて給湯の加熱を行うもの。(温ガp.282)

==== 潜熱回収型：
排気ガス中の熱を有効利用することで高効率化をはかったもの。コンプレッサーで冷媒を圧縮し集熱部・放熱部での熱移動を行うことで、消費エネルギーより多くの熱を得ることができる仕組み。(温ガp.282、297)　→図（温ガp295図６）

==== ヒートポンプ式：
外気から集熱を行う高効率の熱源。瞬時の加熱能力が小さく貯湯が必要なため本体サイズが大きくなり、大量出湯時には湯切れする場合があります。（温ガp.282）→図（温ガp297図10）

==== ヒートショック：
水まわりの室温は非常に低い場合が多いため、入浴に伴う極端な体温変化による血圧の急激な変化などによる体調不良のこと（温ガp.283、310）

==== サヤ管ヘッダー方式：
ヘッダーから先の住宅設備機器に至る配管径を細くすることができる給水方式。（温ガp.305）　→図（温ガp283図１）

==== CO2HP：
高圧のCO2冷媒を利用するヒートポンプのこと。(温ガp.297)

==== 節湯器具：
湯の消費量そのものを節約する器具。「手元止水」「小流量吐水」「水優先吐水」の3つが定められています。（温ガp.306）→図（温ガp307表８）

==== 節湯型水栓：
台所・洗面の水栓や浴室のシャワーにおいて、使用者に負担をかけることなく湯消費を削減する工夫がされたもの（温ガp.306）→図（温ガp307表８）

==== 高断熱浴槽：
ウレタン等断熱材を浴槽に吹き付けたもの、断熱材で二重に覆うことで保温性能を高めているものなど、浴槽の湯が冷めにくくなるような断熱がほどこされたもの（図16）。JI雰囲気温度10℃の中に置かれた浴槽に40℃の湯を浴槽深さの70％だけ満たし、4時間放置した際の温度低下が2.5℃以内のものをさします。放熱ロスが少ないため、追焚負荷の低減に有効です。→図（温ガp.309図16）

==== 節湯型浴槽：
湯消費を削減する浴槽。ステップや手すりの形状が工夫されており、少ない湯量で水位を確保できます。→図（温ガp.309図17）

==== 自動湯はり：
ボタンを押すだけで、浴槽に設定の量・温度の湯を自動的にはることができます(温ガp.291)

==== 追焚：
冷めた湯を温め直す(温ガp.291)

==== 号数：
ガス瞬間式の瞬時加熱能力。1号とは、1分間に1Lの水の温度を25℃上げる能力を指します。(温ガp.289)

==== フルオート(瞬間式): 
瞬間式では水位レベルを指定するもの。水位検知を行うため、水位が下がった場合に自動的に補給することができます。(温ガp.289)

==== フルオート(貯湯式):
浴槽の自動湯はりと追焚の両方が可能な機種。(温ガp.289)

==== セミオート(瞬間式)：
湯量（リットル）を指定するもの(温ガp.289)

==== セミオート(貯湯式)：
自動湯はりのみ可能で追焚ができない機種(温ガp.289)

==== 自然循環式：
浴槽内の湯が釜で温められ浮力で循環すること。(温ガp.291)

==== 強制循環式：
風呂と給湯機の設置場所の自由度が高い。浴槽の中に設置したアダプターと給湯機との間を2本の配管で接続し、湯はり時には両方の配管で給湯を行い、追焚時には、片方の配管で浴槽の湯を給湯機にポンプ動力で引き込み、給湯機で昇温した湯を他方の配管で浴槽に戻すもの。(温ガp.291)

==== さし湯：
浴槽の湯が冷めた際に熱い湯を足すこと。追焚回路よりも給湯回路の方がより効率が高いため、さし湯を上手に使うことで省エネ効果が期待できます。(温ガp.291)

==== 出湯パターン：
給湯消費の実使用を想定した一日の給湯のパターン。(温ガp.293)

==== IBECLモード：
30年ほど前の湯消費実態を基に4人世帯を前提として作成された使用条件であり、1日に13回の出湯しか行わないなど、現状に即していない面がありました。(温ガp.293)

==== 修正M1モード：
4人家族を想定し、代表6日間から構成された全30日の使用条件です。従来の試験条件に比べて、日変動を含めた実使用に近い条件での効率評価が可能になりました。(温ガp.293)

==== M1スタンダードモード：
2012年施行の「低炭素認定基準」、2013年施行の「平成25年省エネルギー基準」において新たに定義された使用条件。短時間出湯など最新の調査知見を反映した、より実使用に近い効率評価が可能となりました。また、修正M1モードが4人家族のみであったのに対し、1～4人の世帯人数に応じた消費量を規定しています(温ガp.293)

==== 年間給湯効率（APF）：
年間を通じて、1の電気により機器から取り出せる給湯の熱負荷の比率を表します。値が大きい（＝エネルギー効率が高い）機種を選択することが省エネにつながります。通年での効率を表している点が特徴的です。エネルギー消費効率のように季節ごとの値はありません。ただし、東京・大阪の気象条件を想定しているため、寒冷地ではAPFより低い効率、蒸暑地ではAPFより高い効率になると考えられますので、注意が必要です。(温ガp.299)

==== 年間給湯保温効率（JIS）：
APFをベースに、浴槽追焚を追加した新しい出湯パターンによるシステム全体のエネルギー効率。値が大きい（＝エネルギー効率が高い）機種を選択することが省エネにつながります。(温ガp.300)

==== エネルギー消費効率：
ヒートポンプユニット単体の性能を示し、1の電気で得られる加熱量を示します。CO2HPは外気を熱源とするため、外気温度の季節変動に伴い大きく効率が変化します(温ガp.299)

==== 手元止水（A/A1）水栓：
タッチ式の機構やリモートセンサー・リモートスイッチにより、通常の操作よりも容易に止水を行うことができます。出しっ放しによる無駄な出湯を抑制します(温ガp.308)　→図（温ガp307表８）

==== 小流量吐水（B/B1）水栓：
少ない流量で快適に使える工夫がされています。(温ガp.308)　→図（温ガp307表８）

==== 水優先吐水（C1）：
通常の使用において湯ではなく水が優先的に出るように工夫されたもの。意図しない不必要な出湯を削減することが可能です　→図（温ガp308図15）


== 項目の追加（中野:Cパートより）

===== ガス従来型給湯機

・ガス給湯機のうち、瞬間的に加熱して給湯する、JIS S2109 （家庭用ガス温水機器）における「先止め式の瞬間湯沸器」に該当する瞬間式のみを評価対象とします（給湯時より前にあらかじめ加熱を行う貯湯式等は評価対象外です）。

===== ガス潜熱回収型給湯機

・ガス給湯機のうち、瞬間的に加熱して給湯する、JIS S2109 （家庭用ガス温水機器）における「先止め式の瞬間湯沸器」に該当する瞬間式のみを評価対象とします（給湯時より前にあらかじめ加熱を行う貯湯式等は評価対象外です）。

===== 石油従来型給湯機

・石油給湯機のうち、瞬間的に加熱して給湯する瞬間式（JIS S3024（石油小型給湯機）における瞬間形）及び小型の貯湯槽を有する瞬間貯湯式（JIS S3024 における貯湯式急速加熱形）を評価対象とします（貯湯式は評価対象外です）。

===== 石油潜熱回収型給湯機

・石油給湯機のうち、瞬間的に加熱して給湯する瞬間式（JIS S3024（石油小型給湯機）における瞬間形）及び小型の貯湯槽を有する瞬間貯湯式（JIS S3024 における貯湯式急速加熱形）を評価対象とします（貯湯式は評価対象外です）。

===== 電気ヒーター給湯機

・JIS C9219（貯湯式電気温水器）に該当する機種のみを評価対象とします（瞬間式等は評価対象外です）。

===== 電気ヒートポンプ給湯機(CO2冷媒)(太陽熱利用給湯設備を使用しないもの)

・JIS C9220：2011（家庭用ヒートポンプ給湯機）又は一般社団法人日本冷凍空調工業会標準規格 JRA4050 （家庭用ヒートポンプ給湯機）に該当する機種を評価対象とします。

・太陽熱利用給湯設備に接続して使用するものは、評価対象外です。

===== 電気ヒートポンプ・ガス瞬間式併用型給湯機

・電気ヒートポンプと潜熱回収型ガス熱源機により構成された給湯機です。ヒートポンプユニットや貯湯ユニットの品番、貯湯槽容量の大きさ、また暖房部と給湯部の構成によって分類されています。

・各分類に該当する機器の型番は、一般社団法人住宅性能評価・表示協会の「温熱・省エネ設備機器等ポータル（住宅版）」にて公表されていますのでこちらのサイトをご確認ください。


===== ガス従来型給湯温水暖房機：
液化石油ガス又は都市ガスを主たるエネルギー源とする給湯温水暖房機。給湯機能と温水暖房機能を持ちます。給湯機能において本計算方法では瞬間的に加熱して給湯する、JIS S2109 における「先止め式の瞬間湯 沸器」に該当する瞬間式のみをさし、給湯時より前にあらかじめ加熱を行う貯湯式等は除きます。温水暖房機能に おいては、ガスの燃焼熱により温水又は不凍液を暖める機器であり、潜熱回収を行わない機器をいいます。

===== ガス潜熱回収型給湯温水暖房機：
液化石油ガス又は都市ガスを主たるエネルギー源とする給湯温水暖房機。給湯機能と温水暖房機能を持ちます。給湯機能において本計算方法では瞬間的に加熱して給湯する、JIS S2109 における「先止め式の瞬間湯 沸器」に該当する瞬間式のみをさし、給湯時より前にあらかじめ加熱を行う貯湯式等は除きます。温水暖房機能に おいては、ガスの燃焼熱により温水又は不凍液を暖める機器であり、従来型の一次熱交換器に加え二次熱交 換器で排気中の水蒸気を水にすることにより、排気中の潜熱を回収して、熱効率を向上させた熱源機のことです。

===== 石油従来型給湯温水暖房機：
灯油を主たるエネルギー源とする給湯温水暖房機。給湯機能と温水暖房機能を持ちます。給湯機能において 本計算方法では、瞬間的に加熱して給湯する瞬間式（JIS S3024 における瞬間形）及び小型の貯湯槽を有する瞬間貯湯式（JIS S3024 における貯湯式急速加熱形）をさし、貯湯式は除きます。温水暖房機能においては、灯油 の燃焼熱により温水又は不凍液を暖める機器であり、潜熱回収を行わない機器をいいます。

===== 石油潜熱回収型給湯温水暖房機：
灯灯油を主たるエネルギー源とする給湯温水暖房機。給湯機能と温水暖房機能を持ちます。給湯機能において 本計算方法では、瞬間的に加熱して給湯する瞬間式（JIS S3024 における瞬間形）及び小型の貯湯槽を有する瞬間貯湯式（JIS S3024 における貯湯式急速加熱形）をさし、貯湯式は除く。温水暖房機能においては、灯油 の燃焼熱により温水又は不凍液を暖める機器であり、従来型の一次熱交換器に加え二次熱交換器で排気中の水蒸気を水にすることにより、排気中の潜熱を回収して、熱効率を向上させた熱源機のことです。

===== 電気ヒーター給湯温水暖房機：
電気ヒーターにより電気をジュール熱に変換して過熱する給湯温水暖房機であり、通常、夜間時間帯の電 気を利用して暖められた湯又は不凍液を貯湯タンクに貯める貯湯タイプが一般的です。給湯機能において、 本計算方法では「JIS C9219 貯湯式電気温水器」に該当する機種のみをさし、その他の瞬間式等は除きます。

===== 電気ヒートポンプ・ガス瞬間式併用型給湯温水暖房機：
電気ヒートポンプと潜熱回収型ガス熱源機により構成された給湯温水暖房機。電気ヒートポンプの熱を給湯のみ、暖房のみ、又は給湯及び暖房に利用する機種があります。
