== 用語解説（簡易版」

[[guide_hw_central]]
==== 住戸セントラル方式：
給湯機から配管で必要な場所に適時適量の湯を供給する給湯方式。熱源(給湯機)、配管、水栓、浴槽について、それぞれ省エネ措置を検討する必要がある。


[[guide_hw_netsugen]]
==== 熱源：
燃料別に、ガス、石油、電気の3種類がある。気候条件、世帯構成、使用状況などの条件に応じて、できるだけ効率の高くなる熱源を導入することが重要。


[[guide_hw_shunkanshiki]]
==== 瞬間式：
瞬時に燃料を燃焼させて給湯の加熱を行うもの。


[[guide_hw_sennetsu]]
==== 潜熱回収型：
排気ガス中の熱を有効利用することで高効率化をはかったもの。コンプレッサーで冷媒を圧縮して集熱部・放熱部での熱移動を行うことで、消費エネルギーより多くの熱を得ることができる仕組み。

[[guide_hw_heatpump]]
==== ヒートポンプ式（CO2HP）：
外気から集熱を行う高効率の熱源。瞬時の加熱能力が小さいため、貯湯タンクが必要。大量出湯時には湯切れする場合がある。


[[guide_hw_co2hp]]
==== CO2HP：
高圧のCO2冷媒を利用するヒートポンプのこと。


[[guide_hw_sayakanheader]]
==== ヘッダー方式：
ヘッダーから先の住宅設備機器に至る配管径を細くする給水方式。


[[guide_hw_setsuyukigu]]
==== 節湯器具：
湯の消費量を節約する器具。「手元止水」「小流量吐水」「水優先吐水」に分類されている。


[[guide_hw_setsuyugatasuisen]]
==== 節湯型水栓：
台所・洗面の水栓や浴室のシャワーなど湯を使う水栓で、湯消費を削減する工夫がされたもの。


[[guide_hw_yokuso_hoon]]
==== 高断熱浴槽：
断熱材で浴槽を覆うことで浴槽の湯が冷めにくくし、保温性能を高めているもの。放熱ロスが少ないため、追焚負荷の低減に有効。


[[guide_hw_oidaki]]
==== 追焚：
冷めた湯を温め直す機能。


[[guide_hw_modonetsukouritsu]]
==== モード熱効率：
JIS S2075（家庭用ガス・石油温水機器のモード効率測定法）に定められた測定方法に基づく値


[[guide_hw_temotoshisui]]
==== 手元止水水栓：
タッチ式の機構やリモートセンサー・リモートスイッチにより、通常の操作よりも容易に止水を行うことができる水栓。


[[guide_hw_mizuyuusen]]
==== 水優先吐水：
通常の使用において水が優先的に出るように工夫された水栓。意図しない不必要な出湯を削減することが可能。


[[guide_hw_gas_jurai_kyutou_onsuidanbou]]
==== ガス従来型給湯温水暖房機：
ガスをエネルギー源とし、給湯機能と温水暖房機能を備えた熱源機。

[[guide_hw_gas_sennetsu_kyutou_onsuidanbou]]
==== ガス潜熱回収型給湯温水暖房機：
ガスをエネルギー源とし、給湯機能と温水暖房機能を備えた熱源機。従来型熱源機の一次熱交換器に加え二次熱交換器で排気中の水蒸気を水にすることにより、排気中の潜熱を回収して、熱効率を向上させた熱源機。

[[guide_hw_sekiyu_jurai_kyutou_onsuidanbou]]
==== 石油従来型給湯温水暖房機：
灯油をエネルギー源とし、給湯機能と温水暖房機能を備えた熱源機。

[[guide_hw_sekiyu_sennetsu_kyutou_onsuidanbou]]
==== 石油潜熱回収型給湯温水暖房機：
灯油をエネルギー源とし、給湯機能と温水暖房機能を備えた熱源機。従来型熱源機の一次熱交換器に加え二次熱交換器で排気中の水蒸気を水にすることにより、排気中の潜熱を回収して、熱効率を向上させた熱源機。

[[guide_hw_denkiheater_kyutou_onsuidanbou]]
==== 電気ヒーター給湯温水暖房機：
電気ヒーターにより電気を熱に変換して過熱する給湯温水暖房機。夜間時間帯の電気を利用して暖められた湯又は不凍液を貯湯タンクに貯める貯湯タイプが一般的。

[[guide_hw_denkiheatpump_gas_shunkanheiyougata_kyuutou_onsuidanbou]]
==== 電気ヒートポンプ・ガス瞬間式併用型給湯温水暖房機：
電気ヒートポンプと潜熱回収型ガス熱源機により構成された給湯温水暖房機。

