
== 照明設備計画：

=== 照明設備計画とは
昼間の昼光利用での明るさの不足分を補い、夜間の光環境を良好に保つことを目的とすると同時に、人工照明エネルギー消費の削減を実現することを目的とした技術です。省エネルギーを実現しつつ、快適性を維持、向上させることが求められます。明るさの感じ方は年齢や視力によって個人差があるだけでなく、明・暗順応の状況により同一人物でも異なります。居住空間内の安全性にも関係するため、慎重な検討が必要です。

===== 自立循環型住宅オプション（仮）
  特になし
  
=== 目標レベル
  ☆☆☆☆☆　目標レベルと参考仕様を記載
  ☆☆☆☆
  ☆☆☆
  ☆☆
  ☆
  
  モデル住宅による標準的なエネルギー消費量　10.9GJ
TIP: 概要の地域選択を反映させて切り替えられると良い。

=== 主たる居室（LDK）
 ・照明を計画しない
 ・照明を計画する
 
==== 照明を計画する場合
NOTE: 選択により切り替え

 照明器具の種類
 ・すべての機器において白熱灯を使用していない
 ・すべての機器において白熱灯以外を使用している
 ・いずれかの機器において白熱灯を使用している
 
 調光が可能な制御
 ・採用する
 ・採用しない
 
 多灯分散照明方式の採用
 ・採用する
 ・採用しない

=== その他の居室
 ・照明を計画しない
 ・照明を計画する
 
==== 照明を計画する場合
NOTE: 選択により切り替え

 照明器具の種類
 ・すべての機器において白熱灯を使用していない
 ・すべての機器において白熱灯以外を使用している
 ・いずれかの機器において白熱灯を使用している
 
 調光が可能な制御
 ・採用する
 ・採用しない
 
=== 非居室
 ・照明を計画しない
 ・照明を計画する
 
==== 照明を計画する場合
NOTE: 選択により切り替え

 照明器具の種類
 ・すべての機器において白熱灯を使用していない
 ・すべての機器において白熱灯以外を使用している
 ・いずれかの機器において白熱灯を使用している
 
 人感センサー
 ・採用する
 ・採用しない
 
=== 設計上の配慮事項・暮らし方の留意点

==== 部屋の状態や明るさレベル応じた器具選定
　照明器具記載の適用畳数を目安に選択する簡易的な方法か、要望する明るさレベル、部屋の大きさ、内装仕上げ材の反射率に応じて、必要光束を算定し、照明器具を選択する方法（単位光束法）など、適切な明るさとなるように器具を選定します。

==== メンテナンスへの配慮
　清掃や交換などのメンテナンスが容易かどうかについても配慮し、ランプ交換式の照明器具の場合、使用するランプは、住まい手が入手しやすいものとします。

==== 安全性の確認
　階段や段差が存在する通路部分の安全性にはとくに注意し、明るさを十分に確保します。照明を設置しても、立ち位置によって足元が影になる場合などがありますので、いろいろな視点を想定して検討することが重要です。また、照度を十分に確保しても、明るい空間から暗い空間へ移動する場合には見えにくくなることが多いため、そうした動線上には段差等のない計画をすることが大切です。さらに高齢者の安全性確保への配慮も忘れないようにします。

==== 光色の検討
　光色も重要な光の要素で、白色光を用いると活動的な雰囲気になり、暖色光を用いると落ち着いた雰囲気になりますので、昼間に多く使用する居室は白色光主体、夜間の使用が多い寝室は暖色光主体というように室の用途によって使い分けると効果的です。
