== 用語解説（簡易版）

[[guide_ls_chuukou]]
====  昼光：
昼間の自然光。自然光をうまく取り入れることにより、住宅室内の昼間の明るさを適切に確保できる。

[[guide_ls_saikoushuhou]]
====  採光手法：
開口部から光を直接採り入れる方法。

TIP: （改修ガ、p.208）

[[guide_ls_doukoushuhou]]
====  導光手法：
開口部から取り入れた光を、空間構成の工夫、仕上げ面の反射などを利用して、居住空間に導く方法。

TIP: （温ガp76改修、ガp.208）

[[guide_ls_choukou]]
====  調光：
最適な明るさ、必要な明るさに調節すること。

TIP: （改修ガ、p.339）。

[[guide_ls_tekijitekikou]]
====  適時適光：
必要な明るさを必要な時間供給すること。

TIP: （温ガp312ポイント）

[[guide_ls_tekishotekikou]]
====  適所適光：
必要な場所に必要な明るさを供給すること。

TIP: （温ガp312ポイント）

[[guide_ls_isshituittoushoumei]]
====  一室一灯照明方式：
一室の天井中央付近に照明器具を一灯配置する方式。（温暖地版ガイドライン313ページ、図1手法２を参考にしてください。）

TIP: 図（温ガ、p.313図1、手法2）

[[guide_ls_tatoubunsan]]
====  多灯分散照明方式：
様々な生活行為が想定される居室において、複数の照明器具を分散して配置し、生活行為に応じて点灯パターンを変えられる方式。（温暖地版ガイドライン313ページ、図1手法３を参考にしてください。）


TIP: 図（温ガp.313図1）。

[[guide_ls_jis_shoudokijun]]
====  JIS照度基準：
室毎に、空間全体の最低限の照度レベルとその室で行われる作業に必要と考えられる照度レベルを示したもの。

TIP: （温ガ、コラムp.318）

[[guide_ls_meishishoumei]]
====  明視照明：
見ようとするもの（視対象）が、安全に、効率よく見えるための照明。

TIP: (温ガp.321、多灯分散照明の設計)

[[guide_ls_funnikishoumei]]
====  雰囲気照明：
空間全体の雰囲気を演出する照明。

TIP: (温ガp.321、多灯分散照明の設計)

[[guide_ls_kougen]]
====  光源：
ランプのこと。

TIP: （改修ガ、p.337）

TIP: 図（温ガp334,335の中からいくつかピックアップ）

[[guide_ls_lampkousoku]]
====  ランプ光束：
光源から全ての方向に放出する光の量［単位：lmルーメン］。

TIP: (温ガp316関連用語、改修ガp.335)

TIP: 図（改ガp.335図）

[[guide_ls_kigukousoku]]
====  器具光束：
照明器具から全ての方向に放出する光の量［単位：lmルーメン］。器具光束＝ランプ光束×器具効率。

TIP: 図（改ガp.335図）

[[guide_ls_kigukouritsu]]
====  器具効率：
器具光束／ランプ光束［単位：％］。照明器具の性能を測る指標となるが、現状ではデータが整備されていない。

TIP: (温ガ、関連用語)

[[guide_ls_sougoukouritsu_e]]
====  総合効率（エネルギー消費効率）：
ランプ光束／点灯回路の損失を含めた消費電力［単位：lm/Wルーメン毎ワット］。ランプおよび安定器（LEDの場合は電源装置）の性能を測る指標。カタログ等では単に「消費効率」と表記されていることが多い。

[[guide_ls_koyuuenergyshouhikouritsu]]
====  固有エネルギー消費効率：
器具光束／消費電力[単位：lm/W]。

TIP: （温ガp316欄外、改修ガp.335）

[[guide_ls_tanikousokuhou]]
====  単位光束法：
単位光束と明るさレベルを用いて必要なランプ光束を算出する一連の照明設計方法。

TIP: （温ガp.322）

[[guide_ls_akarusalevel]]
====  明るさレベル：
人の感覚に近い明るさの目安。（温暖地版ガイドライン317ページの表を参考にしてください。） 

TIP: 表（温ガp317表）

[[guide_ls_ls]]
====  最大光束：
室全体のランプ光束の上限値。

TIP: (温ガ、ステップ４)

[[guide_ls_haikou]]
====  配光：
ランプや照明器具から、光がどの方向にどの程度の強さ（光度）で出ているかを示した分布。照明器具メーカーのカタログやHPで確認できる。

TIP: （温ガ、手法１機器による手法-照明器具）

[[guide_ls_haikoukyokusenzu]]
====  配光曲線図：
器具から出る光の広がり方を断面的に示したもの。（各メーカーのカタログ、HPなどで見ることができます。）

TIP: 図（温ガp338の中からどれか）

[[guide_ls_kakusanhaikoukigu]]
====  拡散配光器具：
比較的面積の大きい範囲を照明できる配光のシーリングライトなど。（温暖地版ガイドライン323ページ、表５のaを参考にしてください。）

TIP: 図（温ガp323表5のa）

[[guide_ls_koushouhaikoukigu]]
====  広照配光器具：
比較的面積の小さい範囲を照明できる配光の照明器具のこと。光の広がりの大きいダウンライトなど。（温暖地版ガイドライン323ページ、表５のbを参考にしてください。）

TIP: 図（温ガp323表5のｂ）

[[guide_ls_chuushouhaikoukigu]]
====  中照配光器具：
比較的光が広がらない照明器具（温暖地版ガイドライン323ページ、表５のcを参考にしてください。）

TIP: （温ガ、p.322）

TIP: 図（温ガp323表5のｃ）

[[guide_ls_lanpittailed]]
====  ランプ一体型LED器具：
ランプとカバーが一体型になった照明器具。長寿命である（40000h）。消費電力が少なく、発熱も少ない。大きさを小さくできる。ランプの交換ができない。

[[guide_ls_hakunetsudenkyu]]
====  白熱電球：
ガラス球内のフィラメント（抵抗体）のジュール熱による輻射を利用した電球。

[[guide_ls_hakunetsutou]]
====  白熱灯：
白熱電球を光源に用いた照明器具。一般照明用白熱電球、ミニクリプトン電球、ハロゲン電球などを含む。

[[guide_ls_keikoulamp]]
====  蛍光ランプ（灯）：
放電で発生する紫外線を蛍光体に当てて可視光線に変換する光源。

[[guide_ls_denkyugatakeikoulamp]]
====  電球形蛍光ランプ：
消費電力が白熱電球の約1/5～1/6、寿命が白熱電球の6～13倍。光色が3色（昼光色、昼白色、電球色）あり、調光可能なタイプもある。E26口金およびE17口金に対応している。

TIP: （温ガp334）

[[guide_ls_denkyuugataledlamp]]
====  電球型LEDランプ：
寿命が一般電球の約40倍で、光色は3色（昼光色、昼白色、電球色）あり、調光可能タイプ及び光色切替タイプがある。E26口金およびE17口金に対応している。

TIP: （温ガp335手法１機器による手法）

[[guide_ls_hfkeikoulamp]]
====  Ｈｆ蛍光ランプ：
高周波点灯専用形蛍光ランプのこと。インバータを用いて高周波点灯することに加え、管径を細くしたり、管長を長くすることによって総合効率を高めている。長寿命で調光が可能。

TIP: （温ガp335手法１機器による手法）

[[guide_ls_koukouritsukiki]]
====  高効率機器：
省エネ性能に優れた電球形蛍光ランプやＬＥＤ照明等

[[guide_ls_hoshuritsu]]
====  保守率：
光源の経時変化や器具の汚れにより光束が減少することをあらかじめ見込んでおく係数。保守率＝光源の設計光束維持率×照明器具の設計光束維持率

[[guide_ls_entyokumennshoudo]]
====  鉛直面照度：
壁面など鉛直な面が受ける照度。視覚的には水平面照度よりも鉛直面照度の方が与える影響が大きくなる。

[[guide_ls_suiheimenshoudo]]
====  水平面照度：
水平な面に入る光の量のこと。一般に照度という場合は、この水平面照度をさす。

[[guide_ls_chokkashoudo]]
====  直下照度：
ランプの真下が照らす場所の明るさのこと。単位：ルクス(lx)。

[[guide_ls_jinkansensor]]
====  人感センサー：
人（熱）の動きを感知して自動的に点灯し、設定時間後に消灯させるためのセンサー。

TIP: 図（温ガp343）

[[guide_ls_shoudosensor]]
====  照度センサー：
明るさを感知して自動的に点灯および消灯するためのセンサー。

TIP: 図（温ガp343）

