=== 用語解説

====  昼光：
間の自然光（改修ガ、p.208）。自然光をうまく取り入れることにより、住宅室内の昼間の明るさを適切に確保する。

====  採光手法：
季節毎の太陽高度や隣棟の影響など日照条件としての敷地状況をふまえ、開口部の位置・形状や日照調整装置の選択などにより、開口部から光を直接採りいれる方法（改修ガ、p.208）

====  導光手法：
欄間など空間構成の工夫、仕上げ面の反射などにより、室奥へ光を間接的に導く方法（改修ガ、p.208）

====  調光：
最適な明るさ、必要な明るさに調節すること（改修ガ、p.339）。照明設備が光束を段階的または無段階で調節できる機能であり、設備本体が有する調光機能による場合と設備とは別の調光器による場合の2通りについて適用される。照明器具の点灯数の切り替えができる設備についても適用される（建研資料,becc）。

====  適時適光：
必要な明るさを必要な時間供給する（温ガ、ポイント）

====  適所適光：
必要な場所に必要な明るさを供給する（温ガ、ポイント）

====  一室一灯照明方式：
一室の天井中央付近に照明器具を一灯配置する →図（温ガ、p.313図1、手法2）

====  多灯分散照明方式：
様々な生活行為が想定されるリビングなどの多目的な居室において、複数の照明器具を分散して配置し、生活行為に応じて点灯パターンを変えるといった光環境のきめ細かい設定を行うこと→図（温ガp.313図1）。主たる居室で一室に複数の照明設備を消費電力の合計を制限し設置することで、運用時の消費電力量削減と光環境の向上を図る照明方式（建研資料、https://www.kenken.go.jp/becc/documents/house/6_20140303.pdf） 

====  JIS照度基準：
室毎に空間全体の最低限の照度レベルとその室で行われる作業に必要と考えられる照度レベルを示したもの（温ガ、コラムp.318）

====  明視照明：
種々の生活行為と作業において、見ようとするもの（視対象）が、安全に、健康的に、効率よく見えるための照明(温ガp.321、多灯分散照明の設計)

====  雰囲気照明：
空間が、種々の生活行為にふさわしい雰囲気をもつように見えるための照明(温ガp.321、多灯分散照明の設計)

====  光源：
ランプのこと（改修ガ、p.337）→図（温ガp334,335の中からいくつかピックアップ）

====  ランプ光束：
光源から全ての方向に放出する光の量［lm：ルーメン］(温ガ、関連用語) → 図（改ガp.335図）

====  器具光束：
照明器具から全ての方向に放出する光の量［lm：ルーメン］、器具光束＝ランプ光束×器具効率。ランプ光束のうち照明器具で吸収された分を差し引いた光束でランプ光束より小さくなる(温ガ、関連用語、コラム、改修ガp.335図)。

====  器具効率：
器具光束／ランプ光束［％］。照明器具の性能を測る指標となるが、現状ではデータが整備されておらず、不明であることが多い。(温ガ、関連用語) →図（改ガp.335図）

====  総合効率（エネルギー消費効率）：
ランプ光束／点灯回路の損失を含めた消費電力［lm/W：ルーメン毎ワット］。ランプおよび安定器（LEDの場合は電源装置）の性能を測る指標となる。カタログ等では単に「消費効率」と表記されていることが多い。「照明器具から放射される光束／ランプ光束」(温ガ、関連用語、手法１照明器具)

====  総合効率（lm/W）：
「ランプ光束／点灯回路の損失を含めた消費電力」のこと。ランプ及び安定器（LEDの場合は電源装置）の性能を測る指標となる。省エネ法におけるエネルギー消費効率に相当する。（温ガ、手法１機器による手法）

====  固有エネルギー消費効率：
器具光束／消費電力[lm/W]。（改修ガp.335）

====  単位光束法：
単位光束と明るさレベルを用いて必要なランプ光束を算出する一連の照明設計方法（温ガp.322）

====  明るさレベル：
人の感覚に近い明るさの目安(温ガ、ステップ２) →表（温ガp317表）

====  最大光束：
室全体のランプ光束の上限値(温ガ、ステップ４)

====  配光：
ランプや照明器具から、光がどの方向にどの程度の強さ（光度）で出ているかの分布。照明器具メーカーの配光データを参照する。（温ガ、手法１機器による手法-照明器具）

====  配光曲線図：
器具から出る光の広がり方を示したもの。照明器具から各方向に出る光度の値を極座標に表したもの。極座標の中心に照明器具があるとして、その照明器具を含む空間の断面を表している。（温ガ、手法１）→図（温ガp338の中からどれか）

====  拡散配光器具：
居室など、比較的面積の大きい範囲を照明するための配光を有するシーリングライトなどの照明器具のこと（建研becc）。→図（温ガp323表5のa）

====  広照配光器具：
廊下など、比較的面積の小さい範囲を照明するための配光を有する照明器具のこと。光の広がりの大きいダウンライトなど（建研becc）。→図（温ガp323表5のｂ）

====  中照配光器具：
1/2ビーム角が44°程度となっており、比較的光が広がらない照明器具（温ガ、p.322）→図（温ガp323表5のｃ）

====  ランプ一体型LED器具：
長寿命である（40000h）。消費電力が少ない。発熱が少ない。大きさを小さくできる。複数の光色が可能。ランプ交換ができない。

====  白熱電球：
ガラス球内のフィラメント（抵抗体）のジュール熱による輻射を利用した電球である。（Wikipedia）

====  白熱灯：
白熱電球を光源に用いた照明器具。一般照明用白熱電球、ミニクリプトン電球、ハロゲン電球などを含む（建研資料becc）。

====  蛍光ランプ（灯）：
放電で発生する紫外線を蛍光体に当てて可視光線に変換する光源である（wikipedia）

====  電球形蛍光ランプ：
白熱電球とほぼ同じ大きさである。光色が3色（昼光色、昼白色、電球色）ある。E26口金およびE17口金に対応する。消費電力が白熱電球の約1/5～1/6である。寿命が白熱電球の6～13倍である。調光可能タイプがある。

====  電球型LEDランプ：
白熱電球とほぼ同じ大きさである。光色が、主に3色（昼光色、昼白色、電球色）ある。E26口金およびE17口金に対応する。寿命が一般電球の約40倍である。調光可能タイプ及び光色切替タイプがある。（温ガ、手法１機器による手法）

====  Ｈｆ蛍光ランプ：
高周波点灯専用形蛍光ランプのこと。インバータを用いて高周波点灯することに加え、管径を細くしたり、管長を長くすることによって総合効率を高めている。長寿命で調光が可能（温ガ、手法１機器による手法）

====  高効率機器：
省エネ性能に優れた電球形蛍光ランプやＬＥＤ照明等

====  保守率：
光源の働程(経時変化)や光源や器具のほこり等の埋積などによる汚れにより光束が減少するため、これを補う目的であらかじめ見込んでおく係数を保守率といい、以下の式で算出されます。保守率（M） ＝ 光源の設計光束維持率（Ml） × 照明器具の設計光束維持率（Md）（東芝ライテックhttps://www.tlt.co.jp/tlt/lighting_design/legal_rules/guides/ieij_led_mf/ieij_led_mf.htm）

====  鉛直面照度：
壁面など鉛直な面が受ける照度。視覚的には水平面照度よりも鉛直面照度の方が与える影響が大きい。(Weblio,
https://www.weblio.jp/content/%E9%89%9B%E7%9B%B4%E9%9D%A2%E7%85%A7%E5%BA%A6)

照度とは、面に入る光の量（詳しくは、単位面積に入射する光束）、即ち一般的にはある面の明るさを示す言葉として使用されている。E＝F／A（E：照度lx、F：光束lm、A：面積m2）。このうち、鉛直な面のうける照度を鉛直面照度という。（パナソニックhttps://www2.panasonic.biz/es/lighting/sekkei/yougo/vertical.html）

====  水平面照度：
照度とは、面に入る光の量（詳しくは、単位面積に入射する光束）、即ち一般的にはある面の明るさを示す言葉として使用されている。E＝F／A（E：照度lx、F：光束lm、A：面積m 2）。このうち、水平な面のうける照度を水平面照度という。一般に照度という場合は、この水平面照度をさすことが多い。（パナソニックhttps://www2.panasonic.biz/es/lighting/sekkei/yougo/horizontal.html）

====  直下照度：
ランプの真下が照らされる場所の明るさのことで、単位はルクス(lx)で（三菱電機、http://faq01.mitsubishielectric.co.jp/faq/show/1451?category_id=418&site_domain=default）。

====  人感センサー：
人（熱）の動きを感知して自動的に点灯し、設定時間後に消灯する（温ガ、手法２）→図（温ガp343）

====  照度センサー：
明るさを感知して自動的に点灯および消灯する（温ガ、手法２）→図（温ガp343）
