
== 照明設備計画マニュアル Dパート：
要素技術に関連する留意点・注意事項等　主担当：辻

== Dパート：WEBの情報　設計上の配慮事項・暮らし方の留意点

==== 部屋の状態や明るさレベル応じた器具選定
　照明器具記載の適用畳数を目安に選択する簡易的な方法か、要望する明るさレベル、部屋の大きさ、内装仕上げ材の反射率に応じて、必要光束を算定し、照明器具を選択する方法（単位光束法）など、適切な明るさとなるように器具を選定します。

==== メンテナンスへの配慮
　清掃や交換などのメンテナンスが容易かどうかについても配慮し、ランプ交換式の照明器具の場合、使用するランプは、住まい手が入手しやすいものとします。

==== 安全性の確認
　階段や段差が存在する通路部分の安全性にはとくに注意し、明るさを十分に確保します。照明を設置しても、立ち位置によって足元が影になる場合などがありますので、いろいろな視点を想定して検討することが重要です。また、照度を十分に確保しても、明るい空間から暗い空間へ移動する場合には見えにくくなることが多いため、そうした動線上には段差等のない計画をすることが大切です。さらに高齢者の安全性確保への配慮も忘れないようにします。

==== 光色の検討
　光色も重要な光の要素で、白色光を用いると活動的な雰囲気になり、暖色光を用いると落ち着いた雰囲気になりますので、昼間に多く使用する居室は白色光主体、夜間の使用が多い寝室は暖色光主体というように室の用途によって使い分けると効果的です。




== Eパート：フル情報　設計上の配慮事項・暮らし方の留意点

=== ■設計上の配慮事項

==== ・照明方式の適切な選定（「一室一灯照明方式」か「多灯分散照明方式」）

==== ・部屋の状態や明るさレベル応じた器具選定
　照明器具記載の適用畳数を目安に選択する簡易的な方法か、要望する明るさレベル、部屋の大きさ、内装仕上げ材の反射率に応じて、必要光束を算定し、照明器具を選択する方法（単位光束法）など、適切な明るさとなるように器具を選定します。


=== ■暮らし方の配慮事項

==== メンテナンスへの配慮
　清掃や交換などのメンテナンスが容易かどうかについても配慮し、ランプ交換式の照明器具の場合、使用するランプは、住まい手が入手しやすいものとします。

==== 安全性の確認
　階段や段差が存在する通路部分の安全性にはとくに注意し、明るさを十分に確保します。照明を設置しても、立ち位置によって足元が影になる場合などがありますので、いろいろな視点を想定して検討することが重要です。また、照度を十分に確保しても、明るい空間から暗い空間へ移動する場合には見えにくくなることが多いため、そうした動線上には段差等のない計画をすることが大切です。さらに高齢者の安全性確保への配慮も忘れないようにします。

==== 光色の検討
　光色も重要な光の要素で、白色光を用いると活動的な雰囲気になり、暖色光を用いると落ち着いた雰囲気になりますので、昼間に多く使用する居室は白色光主体、夜間の使用が多い寝室は暖色光主体というように室の用途によって使い分けると効果的です。
