
== 照明設備計画マニュアル Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野

== 省エネルギー手法の解説（入力ガイド説明文）
NOTE: 「エネルギー消費性能計算プログラム(住宅版) 」のヘルプボタンの説明を簡潔にし、図表を追加する

NOTE: 自立テキストの補足情報（省エネになる方法）を追記する

=== 主たる居室
[[shuho_ls_main_setti]]
==== 設置の有無（主たる居室）
・居間（リビング）、食堂（ダイニング）、台所（キッチン）のいずれかに一か所にでも照明設備を設置する場合は、「設置する」を選択して下さい。

[[shuho_ls_main_design]]
==== 照明器具の種類
・主たる居室に一か所でも照明設備を設置している場合は評価の対象となります。

「すべての機器においてLEDを使用している」は、主たる居室のすべての照明設備にLEDを使用している場合に選択してください。

「すべての機器において白熱灯以外を使用している」は、主たる居室のすべての照明設備に白熱灯以外（すべての照明設備でLEDを使用している場合を除きます）を使用している場合に選択してください。

「いずれかの機器において白熱灯を使用している」は、主たる居室のすべての照明設備に白熱灯を使用している場合に選択して下さい。白熱灯とは、一般照明用白熱電球、ミニクリプトン電球、ハロゲン電球等の種類を含みます。なお、キッチンに設置するレンジフード内の手元灯については、白熱灯等以外の器具が設置されている製品が少ないため、当面の間は評価対象外とします。

・設置する照明設備機器の種別により、同じエネルギーでより高い効果、より明るい空間を実現することが可能です。機器によって特性や省エネルギーの手法は異なります。省エネルギーの観点からは、イニシャルコストがやや高くても消費電力量の少ない機器を選択することが望ましく、ランニングコストを考慮すれば、結局トータルコストは小さくなる傾向があります。機器についての情報を収集し、適切な選択を行うことが重要となります。

・照明設備機器は光源と照明器具に分類され、採用する部屋によって適切なものを選択することが省エネルギーにつながります。エネルギー消費の少ないものを選ぶだけでなく、求められる光環境を実現するために各機器の特徴を理解した上で採用することが求められます。

[[shuho_ls_main_multi]]
==== 多灯分散照明方式の採用
・多灯分散照明方式とは、主たる居室において、一室に複数の照明設備の消費電力の合計を制限して設置することで、運用時の消費電力量削減と光環境の向上を図る照明方式のことです。
・多灯分散照明方式は、評価対象住戸の主たる居室に設置された照明設備の消費電力の合計が、拡散配光器具（居室等、広い範囲を照らすための配光を有する照明器具。シーリングライト等）により必要な設計照度を得るための照明設備の消費電力の合計を超えないことを適用条件としています。

TIP: 多灯分散照明方式の適用条件については、「2.エネルギー消費性能の算定方法」の「第六章照明設備」の「6.7多灯分散照明方式による補正係数」を参照して下さい。

・多灯分散照明方式は、低い消費電力の照明器具を分散配置させ様々な点灯状況を可能にする照明手法で、リビングなどの多目的な部屋において光環境の質の向上と省エネルギーを両立させることを目的としています。低い消費電力の照明器具を前提としていることから、手法1の高効率な器具の採用と組み合わせて計画する必要があります。

・この手法は、住宅全体で約6％程度の照明エネルギー削減効果があります。

TIP: 温暖地版P〇〇　図〇

[[shuho_ls_main_dimming]]
==== 調光が可能な制御

・照明設備の光束を段階的または無段階で調節できる機能を有する制御です。減光することによってエネルギー削減効果が得られます。

・照明設備本体が有する調光機能による場合と、照明設備本体とは別の調光器による場合があります。2～3 本の蛍光灯がセットになった照明器具で、スイッチにより点灯本数を調整する「段調光」も評価対象とします。

・個別の機器の調光スイッチは、最適な明るさに調節することができるため、On-Oﬀのみのスイッチと比べて、明るさの無駄を防ぐことが可能です。

・複数の機器を一括で調光するシーン記憶式調光器は、一室に照明機器を複数設定する多灯分散照明方式を用いた場合に導入の効果があり、タイマー機能を内蔵しているタイプでは、自動で設定時刻に調光をすることが可能なシステムです。

・LEDと蛍光灯は調光対応タイプでないと調光はできませんので注意してください。なお、LEDには調光機能のほか、調色（光色を調整できる）機能をもつものもあります。

=== その他の居室

[[shuho_ls_general_setti]]
==== 設置の有無（その他の居室）
寝室、子ども室、和室等、その他の居室が複数ある場合は、 いずれかの居室に一か所でも設置する場合は、「設置する」を選択して下さい。 ※クローゼット・納戸等に設置する器具は「非居室」で評価します。

[[shuho_ls_general_device]]
==== 照明器具の種類
NOTE: 主たる居室と同じ

[[shuho_ls_general_dimming]]
==== 調光が可能な制御
NOTE: 主たる居室と同じ


=== 非居室

[[shuho_ls_other_setti]]
==== 設置の有無（非居室）
浴室・洗面所・トイレ・廊下・玄関・クローゼット・納戸等、非居室のうちいずれか一か所でも設置する場合は、「設置する」を選択して下さい。

[[shuho_ls_other_device]]
==== 照明器具の種類
NOTE: 主たる居室と同じ

[[shuho_ls_other_control]]
==== 人感センサー

・人感センサーとは、人を感知して自動で照明設備を点滅させる機能です。手動でスイッチをオン・オフさせる場合の消し忘れを防ぎ、また短時間の照明が必要な非居室等における区画においてエネルギー削減効果が得られます。

・こまめな照明のオン・オフは、省エネルギーに直結します。ただし、住まい手の意思にだけ頼る手動のシステムでは、消し忘れが頻繁に生じる可能性が高くなります。照明エネルギーの消費量を削減するためには、消し忘れを防ぐ自動の制御システムを導入することが必要となります。
