=== 用語解説

==== コージェネレーションシステム：
オンサイトで発電し、発電の際に発生する熱を住宅内で使用することによって、エネルギーの総合利用効率を高めることができる機器です。家庭で必要に応じて発電し、その排熱を給湯や床暖房に使用することで、投入エネルギーに対する取り出せるエネルギーの割合（総合エネルギー効率）を高めることができる機器です。

==== ガスエンジンGEC:
コージェネレーション設備のうち、発電ユニットにガスエンジン(Gas Engine Co-generation)を用いた機種を指します。一般的には、「エコウィル」と呼ばれています(温暖地版p.376,表１)。ガス駆動のエンジンによって発電機を回し、発電を行うシステムです。エンジンを回すことによって発生する排熱をタンクに貯め、給湯や床暖房に利用します(温暖地版p.377,表１)。排熱量が多く1日の中で発電・停止を繰り返す機種が一般的です。排熱利用の有無や方式、発電・排熱効率等の仕様により、GEC1、GEC２の２つに区分されています。（建研資料？付録8A）各メーカーの発電ユニット品番で区分されているので、カタログ等で確認してください。

==== 燃料電池コージェネレーションシステム：
ガスを改質して水素（H2）を取り出し、空気中の酸素（O2）と反応させて、水（H2O）を生成する化学反応の中で電気と熱を得るものです。水素の改質も発電ユニットの中で行われます。ガスには、炭素（C）も含まれていますので、運転することによって他のガス機器と同様に二酸化炭素（CO2）が発生します。固体高分子形燃料電池（PEFC）CGSと固体酸化物形燃料電池（SOFC）があります。一般的には、「エネファーム」と呼ばれています。

==== 固体酸化物形燃料電池（SOFC）：
コージェネレーション設備のうち、発電ユニットに固体酸化物型燃料電池(Solid Oxide Fuel Cell)を用いた機種を指す。定格の発電効率が高く常時発電を行う機種が一般的である。排熱利用の有無や方式、発電・排熱効率等の仕様により、PEFC1からPEFC6の６つに区分されています。（建研資料？付録8A）各メーカーの発電ユニット品番で区分されているので、カタログ等で確認してください。

==== 固体高分子形燃料電池（PEFC）：
コージェネレーション設備のうち、発電ユニットに 固体高分子形燃料電池 (Polymer electrolyte fuel cell)を用いた機種を指します。排熱量が多く1日の中で発電・停止を繰り返す機種が一般的です。排熱利用の有無や方式、発電・排熱効率等の仕様により、PEFC1からPEFC6の６つに区分されています。（建研資料？付録8A）各メーカーの発電ユニット品番で区分されているので、カタログ等で確認してください。

==== 補助熱源：
タンク内の湯が足りなくなったときは、補助熱源が稼働し、給湯や床暖房に必要な湯を供給します。補助熱源には従来型給湯機を採用しているものと潜熱回収型給湯機を採用しているものとがありますが、より効率の高い潜熱回収型の補助熱源を搭載しているコージェネレーションシステムを選択することが重要です。

