

== コージェネレーションシステムの導入 Aパート：
WEB プログラムのメニュー情報（要素技術を考えるにあたり大切な情報と、評価に必要な最低限の情報）


=== コージェネレーションとは
日中に自然エネルギーである太陽光で発電を行い、住宅内で消費する電力を自己生産するシステムです。夜間は通常どおり電力を購入する必要がありますが、日中の余剰電力は売電することができますので、トータルとして電力収支が改善されランニングコストを極めて低く抑えることが可能になります。

===== 自立循環型住宅オプション（仮）
  特になし

=== 目標レベル
  ☆☆☆☆☆　目標レベルと参考仕様を記載
  ☆☆☆☆
  ☆☆☆
  ☆☆
  ☆

=== コージェネレーション設備の設置
  ・設置しない
  ・設置する
  
=== コージェネレーションの種類
  ・PEFC(固体高分子形燃料電池)
  ・SOFC(固体酸化物形燃料電池)
  ・PEFC・SOFCに2015年度以前の評価方法またはGEC
  
=== コージェネレーション機器の指定
  ・指定する
  ・指定しない
  
=== 逆潮流の評価
  ・評価しない
  ・評価する

 note:コージェネレーション設備を設置する場合
  太陽光発電設備とコージェネレーション設備を同時に設置する場合の省エネルギー基準における評価はこちらを参考にしてください。
 
=== メーカ名、品番等の一部
  ・型番直接入力窓
  
=== 設計上の配慮事項・暮らし方の留意点

==== 設置方位と傾斜角
　方位による効率は、真南向きを利用効率を100%とすると、東西は85～89％程度、北は67～75％程度です。傾斜角は、10°（1 寸8 分勾配程度）から40°（8 寸4 分勾配程度）の範囲では、ほとんど差はありません。方位には多少注意が必要ですが、屋根の勾配について特別に配慮が必要になることはなく、好みのデザインの屋根に設置することが可能といえます（新築版P84図）

==== 局地的条件
　太陽光発電は、日影ではほとんど発電しません。そのため、北向きの傾斜地や山間部など、日照時間が短くなる場合や、降雪によって太陽電池モジュールが雪で覆われたままだと、期待される発電量が得られいため注意が必要です。また、近隣の将来状況も想定して検討する必要があります。

==== 太陽光発電システムの設置上の注意
　太陽電池モジュールを屋根に設置する場合、風の強い地域では、暴風による破損に注意が必要です。また、積雪地では、発電用の機器や部材が積雪による荷重に耐えるようにするとともに、太陽電池モジュールからの落雪に十分注意する必要があります。
