== 用語解説（簡易版）

[[guide_cogen_cogen]]
==== コージェネレーションシステム：
敷地内で発電し、発電の際に発生する熱を住宅内で使用することで、エネルギーの総合利用効率を高める機器。

[[guide_cogen_gec]]
==== ガスエンジンGEC:
発電ユニットにガスエンジン(Gas Engine Co-generation)を用いた機種。排熱利用の有無や方式、発電・排熱効率等の仕様により、GEC1、GEC２の２つに区分されている。一般的には、「エコウィル」と呼ばれているもの。→(温暖地版p.376,表１)

[[guide_cogen_nenryoudenchi]]
==== 燃料電池コージェネレーションシステム：
ガスを改質して水素（H2）を取り出し、空気中の酸素（O2）と反応させて、水（H2O）を生成する化学反応の中で電気と熱を得る機種。固体高分子形燃料電池（PEFC）CGSと固体酸化物形燃料電池（SOFC）がある。一般的には、「エネファーム」と呼ばれているもの。

[[guide_cogen_sofc]]
==== 固体酸化物形燃料電池（SOFC）：
発電ユニットに固体酸化物型燃料電池(Solid Oxide Fuel Cell)を用いた機種。定格の発電効率が高く、常時発電を行う機種が一般的。排熱利用の有無や方式、発電・排熱効率等の仕様により、PEFC1からPEFC6の６つに区分されている。

[[guide_cogen_pefc]]
==== 固体高分子形燃料電池（PEFC）：
発電ユニットに固体高分子形燃料電池 (Polymer electrolyte fuel cell)を用いた機種。排熱量が多く、1日の中で発電・停止を繰り返す機種が一般的。排熱利用の有無や方式、発電・排熱効率等の仕様により、PEFC1からPEFC6の６つに区分されている。

[[guide_cogen_hojonetsugen]]
==== 補助熱源：
タンク内の湯が足りなくなったときに、給湯や床暖房に必要な湯を供給するための補助的な熱源。効率の高い潜熱回収型の補助熱源を搭載しているコージェネレーションシステムを選択することが重要。

[[guide_cogen_gyakuchoryu]]
==== 逆潮流：
自家発電事業者の消費する電気よりも自家発電事業者が発電する電力が多くなったとき、余剰電力が電力会社線側に戻るように流れること。（みるみるわかるEnergy　https://www.sbenergy.jp/）

