
== 照明設備計画マニュアル Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野

== 室用途と省エネルギー手法

==== 主たる居室

・機器による手法

・運転・制御による手法（調光が可能な制御）

・設計による手法（多灯分散照明方式の採用）

==== その他の居室

・機器による手法

・運転・制御による手法（調光が可能な制御）

・設計による手法（多灯分散照明方式の採用）

==== 非居室

・機器による手法

・運転・制御による手法（人感センサー）

・設計による手法（多灯分散照明方式の採用）

== 省エネルギー手法の説明

==== 機器による手法

・設置する照明設備機器の種別により、同じエネルギーでより高い効果、より明るい空間を実現することが可能です。機器によって特性や省エネルギーの手法は異なります。省エネルギーの観点からは、イニシャルコストがやや高くても消費電力量の少ない機器を選択することが望ましく、ランニングコストを考慮すれば、結局トータルコストは小さくなる傾向があります。機器についての情報を収集し、適切な選択を行うことが重要となります。

・照明設備機器は光源と照明器具に分類され、採用する部屋によって適切なものを選択することが省エネルギーにつながります。エネルギー消費の少ないものを選ぶだけでなく、求められる光環境を実現するために各機器の特徴を理解した上で採用することが求められます。

==== 運転・制御による手法（調光が可能な制御）

・個別の機器の調光スイッチは、最適な明るさに調節することができるため、On-Oﬀのみのスイッチと比べて、明るさの無駄を防ぐことが可能です。

・複数の機器を一括で調光するシーン記憶式調光器は、一室に照明機器を複数設定する多灯分散照明方式を用いた場合に導入の効果があり、タイマー機能を内蔵しているタイプでは、自動で設定時刻に調光をすることが可能なシステムです。

・LEDと蛍光灯は調光対応タイプでないと調光はできませんので注意してください。なお、LEDには調光機能のほか、調色（光色を調整できる）機能をもつものもあります。

==== 運転・制御による手法（人感センサー）

・こまめな照明のオン・オフは、省エネルギーに直結します。ただし、住まい手の意思にだけ頼る手動のシステムでは、消し忘れが頻繁に生じる可能性が高くなります。照明エネルギーの消費量を削減するためには、消し忘れを防ぐ自動の制御システムを導入することが必要となります。


==== 設計による手法（多灯分散照明方式の採用）

・多灯分散照明方式は、低い消費電力の照明器具を分散配置させ様々な点灯状況を可能にする照明手法で、リビングなどの多目的な部屋において光環境の質の向上と省エネルギーを両立させることを目的としています。低い消費電力の照明器具を前提としていることから、手法1の高効率な器具の採用と組み合わせて計画する必要があります。

・この手法は、住宅全体で約6％程度の照明エネルギー削減効果があります。

TIP: 温暖地版P〇〇　図〇
