
== 照明設備計画マニュアル Aパート：
WEB プログラムのメニュー情報（要素技術を考えるにあたり大切な情報と、評価に必要な最低限の情報）


=== 照明設備計画とは
照明設備計画は、昼間の昼光利用での明るさの不足分を補い、夜間の光環境を良好に保つことを目的とすると同時に、人工照明エネルギー消費の削減を実現することを目的とした技術です。省エネルギーを実現しつつ、快適性を維持、向上させることが求められます。明るさの感じ方は年齢や視力によって個人差があるだけでなく、明・暗順応の状況により同一人物でも異なります。居住空間内の安全性にも関係するため、慎重な検討が必要です。

=== 目標レベル
  ☆☆☆☆☆　換気設備の目標レベルと参考仕様を記載
  ☆☆☆
  ☆
  
  モデル住宅による標準的なエネルギー消費量　10.9GJ
TIP: 概要の地域選択を反映させて切り替えられると良い。

=== 主たる居室（LDK）
 ・照明を計画しない
 ・照明を計画する
 
==== 照明を計画する場合
NOTE: 選択により切り替え

 照明器具の種類
 ・すべての機器において白熱灯を使用していない
 ・すべての機器において白熱灯以外を使用している
 ・いずれかの機器において白熱灯を使用している
 
 調光が可能な制御
 ・採用する
 ・採用しない
 
 多灯分散照明方式の採用
 ・採用する
 ・採用しない

=== その他の居室
 ・照明を計画しない
 ・照明を計画する
 
==== 照明を計画する場合
NOTE: 選択により切り替え

 照明器具の種類
 ・すべての機器において白熱灯を使用していない
 ・すべての機器において白熱灯以外を使用している
 ・いずれかの機器において白熱灯を使用している
 
 調光が可能な制御
 ・採用する
 ・採用しない
 
=== 非居室
 ・照明を計画しない
 ・照明を計画する
 
==== 照明を計画する場合
NOTE: 選択により切り替え

 照明器具の種類
 ・すべての機器において白熱灯を使用していない
 ・すべての機器において白熱灯以外を使用している
 ・いずれかの機器において白熱灯を使用している
 
 人感センサー
 ・採用する
 ・採用しない
 
=== 設計上の配慮事項・暮らし方等

==== 単位光束法による照明設計
　照明設備は
 
==== メンテナンスを意識した計画
　照明設備は、清掃や交換などのメンテナンスが容易かどうかについても配慮し、使用するランプは、住まい手が入手しやすいものとします。

==== 安全性への配慮
　階段や段差が存在する通路部分の安全性にはとくに注意し、明るさを十分に確保します。照明を設置しても、立ち位置によって足元が影になる場合などがありますので、いろいろな視点を想定して検討することが重要です。
