
== 換気設備計画マニュアル Cパート：
エネルギー消費量の多寡に与える影響度（より省エネを目指すための設計ツールとしての情報）　主担当：中野

== 表示方法
入力画面の項目ごとにボタンを設置し、その項目に対しての情報をポップアップで表示させる

==換気方式と省エネルギー手法
==== ダクト式第一種換気設備

・ダクト径の大口径化・長さ、曲がりによる圧力損失の低減
・高効率機器の導入
・比消費電力を入力し省エネルギー効果を評価する
・熱交換型換気設備を導入する

==== ダクト式第二種、第三種換気設備

・ダクト径の大口径化・長さ、曲がりによる圧力損失の低減
・高効率機器の導入
・比消費電力を入力し省エネルギー効果を評価する
・温度差利用型ハイブリッド換気の導入

==== 壁付け式第一種換気設備

・ファンと屋外端末の組み合わせを適正化する
・比消費電力を入力し省エネルギー効果を評価する
・熱交換型換気設備を導入する

==== 壁付け式第二種、第三種換気設備を設置する場合

・ファンと屋外端末の組み合わせを適正化する
・比消費電力を入力し省エネルギー効果を評価する

==省エネルギー手法の説明
===ダクト径の大口径化・長さ、曲がりによる圧力損失の低減

・施工性や省スペースを優先しすぎて細型のダクトを用いることがありますが、できるだけそうしたことを避け、風量に見合った適切な太さのダクトを用いることが重要です。住宅の場合、通常は主ダクトで直径 100 ㎜、枝ダクトで直径50 ㎜のダクトを用いることが一般的ですが、ダクト等の圧力損失を低減して省エネルギーをはかるには、主ダクトで直径100㎜以上、枝ダクトで直径75 ㎜以上のダクトを使用することが効果があります。
・ダクトの長さを短くしたり、曲りを少なくすることにより、圧力損失を抑えることができ、消費電力の小さい機種とすることが可能になります。
　
===高効率機器の導入

・換気システムに採用されているモーターには交流モーター（ACモーター）と直流モーター（DCモーター）の 2つがあります。一般的に DCモーターは同じ風量の場合に入力電力が小さく省エネルギー型といえます。
・DCブラシレスモーターは消費電力が小さいほか、回転数などの制御性が高いため、一定の風量や一定の機外圧力に制御することが容易です。そのため外部風圧の変動などによってファンにかかる圧力が変動した場合にも一定の風量で制御できるような機器もあります。
・ACモーターも総合効率が高いものがあり、ファンの選定には、設計された風量における、1㎥/h の空気を搬送するために必要な入力電力を表す比消費電力の多寡で選択をすることが勧められます。
・DCモーターを用いた風量一定制御は、ダクトなどの圧力損失が小さい場合は、省エネとなりますが、圧力損失が大きいと必ずしも省エネとはなりません。ダクト等の圧力損失低減を適用することを高効率機器の要件とします。

===比消費電力を入力し省エネルギー効果を評価する

・比消費電力を目安として、ダクト等の圧力損失低減を採用した上で、第一種換気システムでは0.4 W/（㎥ /h）以下、第二種・第三種換気システムでは0.2 W/（㎥ /h）以下となることを、高効率機器の導入の要件とします。


===熱交換型換気設備を導入する



===温度差利用型ハイブリッド換気の導入

温度差利用型ハイブリッド換気システムは、室内温度と外気温度の差が大きい冬期には、自然給排気口や排気筒を経由して行われる換気（自然換気）を用い、夏期・中間期には機械換気設備を利用する方式です。この方式には、外壁等に設置された給排気口による壁面換気口利用型と、床下の給気口と通常屋根部に設置される排気筒を利用する床下給気・排気筒排気型の2 つのタイプがあります（図4）。
・温度差利用型ハイブリッド換気を計画的に設計するためには、住宅の気密性能は高いものとすることが必要です。
・給気口と排気口の合計面積が、住宅の床面積（吹き抜けがある場合はその部分も床があるとみなした面積とする）あたり、表7 の必要有効開口面積となるようにします。1 階または床下の給気口と2 階または排気筒の排気口の面積は同程度になるようにします。
・給気口または排気口で、換気量が一定になるような制御を行います。制御を行わないと、内外温度差が大きくなったときや風が強いときに換気量が過大になり、換気負荷（暖房エネルギー）が増加します。
・便所や浴室等には別途局所換気装置を設けます。温度差ハイブリッド換気で行う全般換気の経路には含みません。
・床面開口や通気用開口、ドアのアンダーカットなど、給気口から排気口まで各室を経由して空気が流れるように十分な開口を設けます。

===ファンと屋外端末の組み合わせを適正化する

エネルギー効率の高いファンと圧力損失の小さな屋外端末を組み合せることを意味します。第一種については比消費電力（p.267 参照）が0.48W/（㎥ /h）以下、第二種・第三種については同じく0.16W/（㎥ /h）以下を要件とします。
壁付け式換気システムの送風ファンの羽根形状は、主にプロペラファンとターボファンに分けられます（図5）。一般にターボファンは許容できる機外圧力が高く、フィルターの目詰まりによる風量減少の問題が比較的少ないといえます。換気メーカーのカタログには、ファンの形状（プロペラファンやターボファン）が示されているので、選択の参考にすることができます。

