
== 照明設備計画マニュアル Aパート：
WEB プログラムのメニュー情報（要素技術を考えるにあたり大切な情報と、評価に必要な最低限の情報）


=== 照明設備計画とは
照明設備計画は、昼間の昼光利用での明るさの不足分を補い、夜間の光環境を良好に保つことを目的とすると同時に、人工照明エネルギー消費の削減を実現することを目的とした技術です。省エネルギーを実現しつつ、快適性を維持、向上させることが求められます。明るさの感じ方は年齢や視力によって個人差があるだけでなく、明・暗順応の状況により同一人物でも異なります。居住空間内の安全性にも関係するため、慎重な検討が必要です。

=== 目標レベル
  ☆☆☆☆☆　換気設備の目標レベルと参考仕様を記載
  ☆☆☆
  ☆
  
  モデル住宅による標準的なエネルギー消費量　10.9GJ
TIP: 概要の地域選択を反映させて切り替えられると良い。

=== 主たる居室（LDK）
 ・照明を計画しない
 ・照明を計画する
 
==== 照明を計画する場合
NOTE: 選択により切り替え

照明器具の種類
 ・すべての機器において白熱灯を使用していない
 ・すべての機器において白熱灯以外を使用している
 ・いずれかの機器において白熱灯を使用している
 
 調光が可能な制御
 ・採用する
 ・採用しない

=== その他の居室
 ・照明を計画しない
 ・照明を計画する
 
==== 照明を計画する場合
NOTE: 選択により切り替え

照明器具の種類
 ・すべての機器において白熱灯を使用していない
 ・すべての機器において白熱灯以外を使用している
 ・いずれかの機器において白熱灯を使用している
 
 調光が可能な制御
 ・採用する
 ・採用しない
 
=== 非居室
 ・照明を計画しない
 ・照明を計画する
 
==== 照明を計画する場合
NOTE: 選択により切り替え

照明器具の種類
 ・すべての機器において白熱灯を使用していない
 ・すべての機器において白熱灯以外を使用している
 ・いずれかの機器において白熱灯を使用している
 
人感センサー
 ・採用する
 ・採用しない
 
=== 設計上の配慮事項・暮らし方等

==== 気密性能と換気の関係
　気密性能が確保された住宅では、台所などの風量の大きな局所換気で全般換気を乱さないよう、同時給排気型の換気扇を用いるか、専用の給気口を設置する必要があります。第三種全般換気は、気密性能が低いと隙間からの空気進入が増え、計画的な換気が困難になります。気密性能（相当隙間面積）C値は2c㎡/㎡以下を目安に高めてください。

==== メンテナンスを意識した計画
　常時換気設備は、メンテナンスがしやすい位置に設置し、フィルターや羽根の点検・清掃を容易に行うことができる機種を選定します。また、屋外端末（外気取り入れ口）についてもメンテナンスができる場所に設置することが基本です。メンテナンスを怠ると適切な風量が得られない場合があります。住まい手に対して定期的な清掃が必要であることを伝えることも徹底します。

==== 給気位置および給気方式の配慮
　居住域に直接冷気が達することを防ぐために、給気口は高い位置に設置し、輻流型（壁面にそって給気が放射状に拡散する形状のもの）等の採用を検討します。また、人の居住位置から離すなどの工夫をします。

